package direct

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"strconv"
)

// Generate returns the Go source of readers.go: every override compiled
// against its locked model and schema. The same inputs always give the same
// bytes, which a test holds the checked-in file to.
func Generate() ([]byte, error) {
	readers, err := Compile()
	if err != nil {
		return nil, err
	}
	proven, err := provenTypes(files)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.\n\n")
	b.WriteString("package direct\n\n")
	b.WriteString("var readers = map[string]Reader{\n")
	for _, r := range readers {
		fmt.Fprintf(&b, "%s: {\n", strconv.Quote(r.Type))
		readerBody(&b, r, r.Complete && proven[r.Type] && len(r.Identifier) == 1)
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// readerBody writes r's fields as the body of a Reader literal.
func readerBody(b *bytes.Buffer, r Reader, production bool) {
	field(b, "Type", r.Type)
	field(b, "Protocol", r.Protocol)
	field(b, "SigningName", r.SigningName)
	if r.Complete {
		b.WriteString("Complete: true,\n")
	}
	if production {
		b.WriteString("Production: true,\n")
	}
	field(b, "Host", r.Host)
	field(b, "SigningRegion", r.SigningRegion)
	field(b, "Target", r.Target)
	field(b, "Method", r.Method)
	field(b, "URI", r.URI)
	field(b, "Action", r.Action)
	field(b, "Version", r.Version)
	field(b, "Wrapper", r.Wrapper)
	if len(r.Identifier) > 0 {
		b.WriteString("Identifier: []Binding{\n")
		for _, id := range r.Identifier {
			fmt.Fprintf(b, "{Property: %q, Member: %q, Location: %q", id.Property, id.Member, id.Location)
			if id.Name != "" {
				fmt.Fprintf(b, ", Name: %q", id.Name)
			}
			if id.JSONName != "" {
				fmt.Fprintf(b, ", JSONName: %q", id.JSONName)
			}
			if id.List {
				b.WriteString(", List: true")
			}
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	if len(r.Input) > 0 {
		b.WriteString("Input: []Binding{\n")
		for _, in := range r.Input {
			binding(b, in)
		}
		b.WriteString("},\n")
	}
	if len(r.Absent) > 0 {
		b.WriteString("Absent: []Condition{\n")
		for _, c := range r.Absent {
			b.WriteString("{Field: ")
			fieldLiteral(b, c.Field, "Field")
			fmt.Fprintf(b, ", Values: %#v},\n", c.Values)
		}
		b.WriteString("},\n")
	}
	if len(r.Response) > 0 {
		b.WriteString("Response: []Step{")
		for _, st := range r.Response {
			fmt.Fprintf(b, "{Name: %q", st.Name)
			if st.List {
				b.WriteString(", List: true")
			}
			if st.Item != "" {
				fmt.Fprintf(b, ", Item: %q", st.Item)
			}
			b.WriteString("}, ")
		}
		b.WriteString("},\n")
	}
	fields(b, r.Fields)
	lister(b, "List", r.List)
	lister(b, "Probe", r.Probe)
	if len(r.AbsentIDs) > 0 {
		fmt.Fprintf(b, "AbsentIDs: %#v,\n", r.AbsentIDs)
	}
	if len(r.Also) > 0 {
		b.WriteString("Also: []Reader{\n")
		for _, also := range r.Also {
			b.WriteString("{\n")
			readerBody(b, also, false)
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
}

func lister(b *bytes.Buffer, name string, l *Lister) {
	if l == nil {
		return
	}
	fmt.Fprintf(b, "%s: &Lister{\n", name)
	field(b, "Operation", l.Operation)
	field(b, "Target", l.Target)
	field(b, "Method", l.Method)
	field(b, "URI", l.URI)
	if len(l.Input) > 0 {
		b.WriteString("Input: []Binding{\n")
		for _, in := range l.Input {
			binding(b, in)
		}
		b.WriteString("},\n")
	}
	b.WriteString("Token: ")
	binding(b, l.Token)
	fmt.Fprintf(b, "NextToken: %#v,\nItems: %#v,\n", l.NextToken, l.Items)
	field(b, "Item", l.Item)
	field(b, "Property", l.Property)
	b.WriteString("},\n")
}

func binding(b *bytes.Buffer, in Binding) {
	fmt.Fprintf(b, "Binding{Member: %q, Location: %q", in.Member, in.Location)
	for _, f := range []struct{ name, value string }{{"Property", in.Property}, {"Name", in.Name}, {"JSONName", in.JSONName}, {"Value", in.Value}} {
		if f.value != "" {
			fmt.Fprintf(b, ", %s: %q", f.name, f.value)
		}
	}
	if in.List {
		b.WriteString(", List: true")
	}
	b.WriteString("},\n")
}

func field(b *bytes.Buffer, name, value string) {
	if value != "" {
		fmt.Fprintf(b, "%s: %q,\n", name, value)
	}
}

func fields(b *bytes.Buffer, fs []Field) {
	if len(fs) == 0 {
		return
	}
	b.WriteString("Fields: []Field{\n")
	for _, f := range fs {
		fieldLiteral(b, f, "")
		b.WriteString(",\n")
	}
	b.WriteString("},\n")
}

// fieldLiteral writes f as a composite literal, prefixed by typeName
// where the context does not already give the type.
func fieldLiteral(b *bytes.Buffer, f Field, typeName string) {
	fmt.Fprintf(b, "%s{Property: %q, Member: %q, Kind: %q", typeName, f.Property, f.Member, f.Kind)
	if len(f.Via) > 0 {
		b.WriteString(", Via: []Step{")
		for _, st := range f.Via {
			fmt.Fprintf(b, "{Name: %q", st.Name)
			if st.List {
				b.WriteString(", List: true")
			}
			if st.Item != "" {
				fmt.Fprintf(b, ", Item: %q", st.Item)
			}
			if st.Where != "" {
				fmt.Fprintf(b, ", Where: %q, Equals: %q", st.Where, st.Equals)
			}
			b.WriteString("}, ")
		}
		b.WriteString("}")
	}
	if f.Transform != "" {
		fmt.Fprintf(b, ", Transform: %q", f.Transform)
	}
	if f.Root {
		b.WriteString(", Root: true")
	}
	if f.JSONName != "" {
		fmt.Fprintf(b, ", JSONName: %q", f.JSONName)
	}
	for _, x := range []struct{ name, value string }{{"XMLName", f.XMLName}, {"Item", f.Item}, {"Scalar", f.Scalar}} {
		if x.value != "" {
			fmt.Fprintf(b, ", %s: %q", x.name, x.value)
		}
	}
	if len(f.Fields) > 0 {
		b.WriteString(",\n")
		fields(b, f.Fields)
	}
	b.WriteString("}")
}

// Readers returns every compiled reader, sorted by type.
func Readers() []Reader {
	out := make([]Reader, 0, len(readers))
	for _, typeName := range sortedKeys(readers) {
		out = append(out, readers[typeName])
	}
	return out
}

// provenTypes is every type whose recorded evidence shows parity on the
// instances read and on the identifiers probed as absent.
func provenTypes(files fs.FS) (map[string]bool, error) {
	raw, err := fs.ReadFile(files, "evidence/parity.json")
	if err != nil {
		return nil, err
	}
	var evidence Evidence
	if err := json.Unmarshal(raw, &evidence); err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, e := range evidence.Types {
		if e.Outcome == "parity" && e.Absence == "parity" {
			out[e.Type] = true
		}
	}
	return out, nil
}
