package direct

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// Generate returns the Go source of readers.go: every override compiled
// against its locked model and schema. The same inputs always give the same
// bytes, which a test holds the checked-in file to.
func Generate() ([]byte, error) {
	readers, err := Compile()
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.\n\n")
	b.WriteString("package direct\n\n")
	b.WriteString("var readers = map[string]Reader{\n")
	for _, r := range readers {
		fmt.Fprintf(&b, "%s: {\n", strconv.Quote(r.Type))
		field(&b, "Type", r.Type)
		field(&b, "Protocol", r.Protocol)
		field(&b, "SigningName", r.SigningName)
		field(&b, "EndpointPrefix", r.EndpointPrefix)
		field(&b, "Target", r.Target)
		field(&b, "Method", r.Method)
		field(&b, "URI", r.URI)
		field(&b, "Action", r.Action)
		field(&b, "Version", r.Version)
		field(&b, "Wrapper", r.Wrapper)
		if len(r.Identifier) > 0 {
			b.WriteString("Identifier: []Binding{\n")
			for _, id := range r.Identifier {
				fmt.Fprintf(&b, "{Property: %q, Member: %q, Location: %q", id.Property, id.Member, id.Location)
				if id.Name != "" {
					fmt.Fprintf(&b, ", Name: %q", id.Name)
				}
				if id.JSONName != "" {
					fmt.Fprintf(&b, ", JSONName: %q", id.JSONName)
				}
				if id.List {
					b.WriteString(", List: true")
				}
				b.WriteString("},\n")
			}
			b.WriteString("},\n")
		}
		if len(r.Response) > 0 {
			b.WriteString("Response: []Step{")
			for _, st := range r.Response {
				fmt.Fprintf(&b, "{Name: %q", st.Name)
				if st.List {
					b.WriteString(", List: true")
				}
				if st.Item != "" {
					fmt.Fprintf(&b, ", Item: %q", st.Item)
				}
				b.WriteString("}, ")
			}
			b.WriteString("},\n")
		}
		fields(&b, r.Fields)
		if l := r.List; l != nil {
			b.WriteString("List: &Lister{\n")
			field(&b, "Operation", l.Operation)
			field(&b, "Target", l.Target)
			field(&b, "Method", l.Method)
			field(&b, "URI", l.URI)
			if len(l.Input) > 0 {
				b.WriteString("Input: []Binding{\n")
				for _, in := range l.Input {
					binding(&b, in)
				}
				b.WriteString("},\n")
			}
			b.WriteString("Token: ")
			binding(&b, l.Token)
			fmt.Fprintf(&b, "NextToken: %#v,\nItems: %#v,\n", l.NextToken, l.Items)
			field(&b, "Item", l.Item)
			field(&b, "Property", l.Property)
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func binding(b *bytes.Buffer, in Binding) {
	fmt.Fprintf(b, "Binding{Member: %q, Location: %q", in.Member, in.Location)
	for _, f := range []struct{ name, value string }{{"Property", in.Property}, {"Name", in.Name}, {"JSONName", in.JSONName}, {"Value", in.Value}} {
		if f.value != "" {
			fmt.Fprintf(b, ", %s: %q", f.name, f.value)
		}
	}
	b.WriteString("},\n")
}

func field(b *bytes.Buffer, name, value string) {
	if value != "" {
		fmt.Fprintf(b, "%s: %q,\n", name, value)
	}
}

func fields(b *bytes.Buffer, fs []Field) {
	if len(fs) == 0 {
		return
	}
	b.WriteString("Fields: []Field{\n")
	for _, f := range fs {
		fmt.Fprintf(b, "{Property: %q, Member: %q, Kind: %q", f.Property, f.Member, f.Kind)
		if f.JSONName != "" {
			fmt.Fprintf(b, ", JSONName: %q", f.JSONName)
		}
		for _, x := range []struct{ name, value string }{{"XMLName", f.XMLName}, {"Item", f.Item}, {"Scalar", f.Scalar}} {
			if x.value != "" {
				fmt.Fprintf(b, ", %s: %q", x.name, x.value)
			}
		}
		if len(f.Fields) > 0 {
			b.WriteString(",\n")
			fields(b, f.Fields)
		}
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
}

// Readers returns every compiled reader, sorted by type.
func Readers() []Reader {
	out := make([]Reader, 0, len(readers))
	for _, typeName := range sortedKeys(readers) {
		out = append(out, readers[typeName])
	}
	return out
}
