package direct

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"slices"
	"strconv"
	"strings"
)

// Generate returns the Go source of the generated reader files, by name:
// every override compiled against its locked model and schema, one file
// per service. The same inputs always give the same bytes, which a test
// holds the checked-in files to.
func Generate() (map[string][]byte, error) {
	readers, err := Compile()
	if err != nil {
		return nil, err
	}
	proven, err := provenTypes(files)
	if err != nil {
		return nil, err
	}
	lived, err := lifecycleTypes(files)
	if err != nil {
		return nil, err
	}
	byService := map[string][]Reader{}
	for _, r := range readers {
		byService[GeneratedFile(r.Type)] = append(byService[GeneratedFile(r.Type)], r)
	}
	out := make(map[string][]byte, len(byService))
	for name, rs := range byService {
		var b bytes.Buffer
		b.WriteString("// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.\n\n")
		b.WriteString("package direct\n\n")
		b.WriteString("func init() {\nregister(map[string]Reader{\n")
		for _, r := range rs {
			fmt.Fprintf(&b, "%s: {\n", strconv.Quote(r.Type))
			production := r.Complete && r.addressable() && evidenced(proven, r.Type, r.UndeclaredReadErrors)
			readerBody(&b, r, production)
			if production && r.LifecycleComplete && evidenced(lived, r.Type, r.UndeclaredDeleteErrors) {
				b.WriteString("Mutable: true,\n")
			}
			b.WriteString("},\n")
		}
		b.WriteString("})\n}\n")
		src, err := format.Source(b.Bytes())
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out[name] = src
	}
	return out, nil
}

// GeneratedFile is the generated file typeName's reader is written to:
// readers_<service>.go, the service lowercased, as readers_ec2.go.
func GeneratedFile(typeName string) string {
	parts := strings.Split(typeName, "::")
	return "readers_" + strings.ToLower(parts[1]) + ".go"
}

// readerBody writes r's fields as the body of a Reader literal.
func readerBody(b *bytes.Buffer, r Reader, production bool) {
	field(b, "Type", r.Type)
	field(b, "Protocol", r.Protocol)
	field(b, "SigningName", r.SigningName)
	if r.Complete {
		b.WriteString("Complete: true,\n")
	}
	if production {
		b.WriteString("Production: true,\n")
	}
	field(b, "Host", r.Host)
	field(b, "SigningRegion", r.SigningRegion)
	if r.DisableDoubleEncoding {
		b.WriteString("DisableDoubleEncoding: true,\n")
	}
	field(b, "Target", r.Target)
	field(b, "Method", r.Method)
	field(b, "URI", r.URI)
	field(b, "Action", r.Action)
	field(b, "Version", r.Version)
	field(b, "Wrapper", r.Wrapper)
	if len(r.Identifier) > 0 {
		b.WriteString("Identifier: []Binding{\n")
		for _, id := range r.Identifier {
			fmt.Fprintf(b, "{Property: %q, Member: %q, Location: %q", id.Property, id.Member, id.Location)
			if id.Name != "" {
				fmt.Fprintf(b, ", Name: %q", id.Name)
			}
			if id.JSONName != "" {
				fmt.Fprintf(b, ", JSONName: %q", id.JSONName)
			}
			if id.List {
				b.WriteString(", List: true")
			}
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	if len(r.IdentifierOrder) > 0 {
		fmt.Fprintf(b, "IdentifierOrder: %#v,\n", r.IdentifierOrder)
	}
	if len(r.Serves) > 0 {
		fmt.Fprintf(b, "Serves: %#v,\n", r.Serves)
	}
	if len(r.Input) > 0 {
		b.WriteString("Input: []Binding{\n")
		for _, in := range r.Input {
			binding(b, in)
		}
		b.WriteString("},\n")
	}
	if len(r.Absent) > 0 {
		b.WriteString("Absent: []Condition{\n")
		for _, c := range r.Absent {
			b.WriteString("{Field: ")
			fieldLiteral(b, c.Field, "Field")
			fmt.Fprintf(b, ", Values: %#v},\n", c.Values)
		}
		b.WriteString("},\n")
	}
	if len(r.Busy) > 0 {
		b.WriteString("Busy: []Condition{\n")
		for _, c := range r.Busy {
			b.WriteString("{Field: ")
			fieldLiteral(b, c.Field, "Field")
			fmt.Fprintf(b, ", Values: %#v},\n", c.Values)
		}
		b.WriteString("},\n")
	}
	if r.Wait > 0 {
		fmt.Fprintf(b, "Wait: %d,\n", r.Wait)
	}
	if len(r.AbsentErrors) > 0 {
		fmt.Fprintf(b, "AbsentErrors: %#v,\n", r.AbsentErrors)
	}
	if r.Each != "" {
		fmt.Fprintf(b, "Each: %q,\n", r.Each)
	}
	if len(r.When) > 0 {
		b.WriteString("When: []Condition{\n")
		for _, c := range r.When {
			fmt.Fprintf(b, "{Field: Field{Property: %q}, Values: %#v},\n", c.Field.Property, c.Values)
		}
		b.WriteString("},\n")
	}
	if r.PageInput != nil {
		b.WriteString("PageInput: &")
		binding(b, *r.PageInput)
	}
	if len(r.PageToken) > 0 {
		fmt.Fprintf(b, "PageToken: %#v,\n", r.PageToken)
	}
	if len(r.Response) > 0 {
		b.WriteString("Response: []Step{")
		for _, st := range r.Response {
			fmt.Fprintf(b, "{Name: %q", st.Name)
			if st.List {
				b.WriteString(", List: true")
			}
			if st.Item != "" {
				fmt.Fprintf(b, ", Item: %q", st.Item)
			}
			if st.Where != "" {
				fmt.Fprintf(b, ", Where: %q, Equals: %q", st.Where, st.Equals)
			}
			b.WriteString("}, ")
		}
		b.WriteString("},\n")
	}
	fields(b, r.Fields)
	lister(b, "List", r.List)
	lister(b, "Probe", r.Probe)
	if len(r.AbsentIDs) > 0 {
		fmt.Fprintf(b, "AbsentIDs: %#v,\n", r.AbsentIDs)
	}
	if len(r.Capture) > 0 {
		b.WriteString("Capture: []Field{\n")
		for _, f := range r.Capture {
			fieldLiteral(b, f, "")
			b.WriteString(",\n")
		}
		b.WriteString("},\n")
	}
	if len(r.UndeclaredReadErrors) > 0 {
		fmt.Fprintf(b, "UndeclaredReadErrors: %#v,\n", r.UndeclaredReadErrors)
	}
	if len(r.UndeclaredDeleteErrors) > 0 {
		fmt.Fprintf(b, "UndeclaredDeleteErrors: %#v,\n", r.UndeclaredDeleteErrors)
	}
	if len(r.CreateOnly) > 0 {
		fmt.Fprintf(b, "CreateOnly: %#v,\n", r.CreateOnly)
	}
	if len(r.Unsupported) > 0 {
		fmt.Fprintf(b, "Unsupported: %#v,\n", r.Unsupported)
	}
	if len(r.WriteOnly) > 0 {
		fmt.Fprintf(b, "WriteOnly: %#v,\n", r.WriteOnly)
	}
	if r.LifecycleComplete {
		b.WriteString("LifecycleComplete: true,\n")
	}
	if r.MutationCaptures {
		b.WriteString("MutationCaptures: true,\n")
	}
	for _, m := range []struct {
		name string
		call *MutationCall
	}{{"Create", r.Create}, {"Delete", r.Delete}} {
		if m.call != nil {
			fmt.Fprintf(b, "%s: &", m.name)
			mutationLiteral(b, *m.call)
			b.WriteString(",\n")
		}
	}
	if len(r.Update) > 0 {
		b.WriteString("Update: []MutationCall{\n")
		for _, u := range r.Update {
			mutationLiteral(b, u)
			b.WriteString(",\n")
		}
		b.WriteString("},\n")
	}
	if len(r.Also) > 0 {
		b.WriteString("Also: []Reader{\n")
		for _, also := range r.Also {
			b.WriteString("{\n")
			readerBody(b, also, false)
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
}

func lister(b *bytes.Buffer, name string, l *Lister) {
	if l == nil {
		return
	}
	fmt.Fprintf(b, "%s: &Lister{\n", name)
	field(b, "Operation", l.Operation)
	field(b, "Target", l.Target)
	field(b, "Method", l.Method)
	field(b, "URI", l.URI)
	if len(l.Input) > 0 {
		b.WriteString("Input: []Binding{\n")
		for _, in := range l.Input {
			binding(b, in)
		}
		b.WriteString("},\n")
	}
	b.WriteString("Token: ")
	binding(b, l.Token)
	fmt.Fprintf(b, "NextToken: %#v,\nItems: %#v,\n", l.NextToken, l.Items)
	field(b, "Item", l.Item)
	field(b, "Property", l.Property)
	b.WriteString("},\n")
}

func binding(b *bytes.Buffer, in Binding) {
	fmt.Fprintf(b, "Binding{Location: %q", in.Location)
	for _, f := range []struct{ name, value string }{{"Member", in.Member}, {"Property", in.Property}, {"Name", in.Name}, {"JSONName", in.JSONName}, {"Value", in.Value}} {
		if f.value != "" {
			fmt.Fprintf(b, ", %s: %q", f.name, f.value)
		}
	}
	if in.List {
		b.WriteString(", List: true")
	}
	if in.Structured != nil {
		b.WriteString(", Structured: ")
		literal(b, in.Structured)
	}
	if in.JSONShape != nil {
		b.WriteString(", JSONShape: ")
		jsonShapeLiteral(b, in.JSONShape)
	}
	b.WriteString("},\n")
}

// literal writes a structured input value, as decoded from YAML, as a Go
// expression of the same dynamic type.
func literal(b *bytes.Buffer, v any) {
	switch t := v.(type) {
	case []any:
		b.WriteString("[]any{")
		for _, item := range t {
			literal(b, item)
			b.WriteString(", ")
		}
		b.WriteString("}")
	case map[string]any:
		b.WriteString("map[string]any{")
		for _, k := range sortedKeys(t) {
			fmt.Fprintf(b, "%q: ", k)
			literal(b, t[k])
			b.WriteString(", ")
		}
		b.WriteString("}")
	default:
		fmt.Fprintf(b, "%#v", t)
	}
}

func field(b *bytes.Buffer, name, value string) {
	if value != "" {
		fmt.Fprintf(b, "%s: %q,\n", name, value)
	}
}

func fields(b *bytes.Buffer, fs []Field) {
	if len(fs) == 0 {
		return
	}
	b.WriteString("Fields: []Field{\n")
	for _, f := range fs {
		fieldLiteral(b, f, "")
		b.WriteString(",\n")
	}
	b.WriteString("},\n")
}

// fieldLiteral writes f as a composite literal, prefixed by typeName
// where the context does not already give the type.
func fieldLiteral(b *bytes.Buffer, f Field, typeName string) {
	fmt.Fprintf(b, "%s{Property: %q, Member: %q, Kind: %q", typeName, f.Property, f.Member, f.Kind)
	if len(f.Regions) > 0 {
		// fmt writes a map's keys sorted, so the output is the same each run.
		fmt.Fprintf(b, ", Regions: %#v", f.Regions)
	}
	if f.AsList {
		b.WriteString(", AsList: true")
	}
	if len(f.Alternatives) > 0 {
		b.WriteString(", Alternatives: []Field{")
		for _, alt := range f.Alternatives {
			fieldLiteral(b, alt, "")
			b.WriteString(", ")
		}
		b.WriteString("}")
	}
	if len(f.Via) > 0 {
		b.WriteString(", Via: []Step{")
		for _, st := range f.Via {
			fmt.Fprintf(b, "{Name: %q", st.Name)
			if st.List {
				b.WriteString(", List: true")
			}
			if st.Item != "" {
				fmt.Fprintf(b, ", Item: %q", st.Item)
			}
			if st.Where != "" {
				fmt.Fprintf(b, ", Where: %q, Equals: %q", st.Where, st.Equals)
			}
			if st.Many {
				b.WriteString(", Many: true")
			}
			b.WriteString("}, ")
		}
		b.WriteString("}")
	}
	if f.Transform != "" {
		fmt.Fprintf(b, ", Transform: %q", f.Transform)
	}
	if f.Key != "" {
		fmt.Fprintf(b, ", Key: %q", f.Key)
	}
	if f.Entries != nil {
		fmt.Fprintf(b, ", Entries: %#v", f.Entries)
	}
	if f.Keyed != nil {
		fmt.Fprintf(b, ", Keyed: %#v", f.Keyed)
	}
	if f.TrueWhen != nil {
		fmt.Fprintf(b, ", TrueWhen: %#v", f.TrueWhen)
	}
	if f.Wrap != "" {
		fmt.Fprintf(b, ", Wrap: %q", f.Wrap)
	}
	if f.Extract != nil {
		fmt.Fprintf(b, ", Extract: %#v", f.Extract)
	}
	if f.Default != nil {
		b.WriteString(", Default: ")
		literal(b, f.Default)
	}
	if len(f.Unless) > 0 {
		b.WriteString(", Unless: []Condition{")
		for _, c := range f.Unless {
			fmt.Fprintf(b, "{Field: Field{Property: %q}, Values: %#v}, ", c.Field.Property, c.Values)
		}
		b.WriteString("}")
	}
	if len(f.Where) > 0 {
		b.WriteString(", Where: []Match{")
		for _, m := range f.Where {
			fmt.Fprintf(b, "{Member: %q, Equals: %q}, ", m.Member, m.Equals)
		}
		b.WriteString("}")
	}
	if f.Root {
		b.WriteString(", Root: true")
	}
	if f.JSONName != "" {
		fmt.Fprintf(b, ", JSONName: %q", f.JSONName)
	}
	for _, x := range []struct{ name, value string }{{"XMLName", f.XMLName}, {"Item", f.Item}, {"Scalar", f.Scalar}} {
		if x.value != "" {
			fmt.Fprintf(b, ", %s: %q", x.name, x.value)
		}
	}
	if len(f.Fields) > 0 {
		b.WriteString(",\n")
		fields(b, f.Fields)
	}
	b.WriteString("}")
}

// Readers returns every compiled reader, sorted by type.
func Readers() []Reader {
	out := make([]Reader, 0, len(readers))
	for _, typeName := range sortedKeys(readers) {
		out = append(out, readers[typeName])
	}
	return out
}

// evidenced reports whether evidence for typeName is recorded and observed
// every code in undeclared: an override's own claim that the service
// answers a code its model does not declare holds only once a run saw it.
func evidenced(evidence map[string][]string, typeName string, undeclared []string) bool {
	observed, ok := evidence[typeName]
	if !ok {
		return false
	}
	for _, code := range undeclared {
		if !slices.Contains(observed, code) {
			return false
		}
	}
	return true
}

// provenTypes is every type whose recorded evidence shows parity on the
// instances read and on the identifiers probed as absent, each with the
// codes the run observed.
func provenTypes(files fs.FS) (map[string][]string, error) {
	raw, err := fs.ReadFile(files, "evidence/parity.json")
	if err != nil {
		return nil, err
	}
	var evidence Evidence
	if err := json.Unmarshal(raw, &evidence); err != nil {
		return nil, err
	}
	out := map[string][]string{}
	for _, e := range evidence.Types {
		if e.Outcome != "parity" || e.Absence != "parity" {
			continue
		}
		// A missing override is no reader to prove.
		if current, err := overrideHash(files, e.Type); err == nil && current == e.Override {
			out[e.Type] = e.Observed
		}
	}
	return out, nil
}
