// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CodeDeploy::Application": {
			Type:        "AWS::CodeDeploy::Application",
			Protocol:    "awsJson1_1",
			SigningName: "codedeploy",
			Host:        "codedeploy.{region}.amazonaws.com",
			Target:      "CodeDeploy_20141006.GetApplication",
			Identifier: []Binding{
				{Property: "ApplicationName", Member: "applicationName", Location: "body"},
			},
			Response: []Step{{Name: "application"}},
			Fields: []Field{
				{Property: "ApplicationName", Member: "applicationName", Kind: "scalar"},
				{Property: "ComputePlatform", Member: "computePlatform", Kind: "scalar"},
			},
		},
		"AWS::CodeDeploy::DeploymentConfig": {
			Type:        "AWS::CodeDeploy::DeploymentConfig",
			Protocol:    "awsJson1_1",
			SigningName: "codedeploy",
			Complete:    true,
			Host:        "codedeploy.{region}.amazonaws.com",
			Target:      "CodeDeploy_20141006.GetDeploymentConfig",
			Identifier: []Binding{
				{Property: "DeploymentConfigName", Member: "deploymentConfigName", Location: "body"},
			},
			Response: []Step{{Name: "deploymentConfigInfo"}},
			Fields: []Field{
				{Property: "ComputePlatform", Member: "computePlatform", Kind: "scalar"},
				{Property: "DeploymentConfigName", Member: "deploymentConfigName", Kind: "scalar"},
				{Property: "MinimumHealthyHosts", Member: "minimumHealthyHosts", Kind: "structure",
					Fields: []Field{
						{Property: "Type", Member: "type", Kind: "scalar"},
						{Property: "Value", Member: "value", Kind: "scalar"},
					},
				},
				{Property: "TrafficRoutingConfig", Member: "trafficRoutingConfig", Kind: "structure",
					Fields: []Field{
						{Property: "TimeBasedCanary", Member: "timeBasedCanary", Kind: "structure",
							Fields: []Field{
								{Property: "CanaryInterval", Member: "canaryInterval", Kind: "scalar"},
								{Property: "CanaryPercentage", Member: "canaryPercentage", Kind: "scalar"},
							},
						},
						{Property: "TimeBasedLinear", Member: "timeBasedLinear", Kind: "structure",
							Fields: []Field{
								{Property: "LinearInterval", Member: "linearInterval", Kind: "scalar"},
								{Property: "LinearPercentage", Member: "linearPercentage", Kind: "scalar"},
							},
						},
						{Property: "Type", Member: "type", Kind: "scalar"},
					},
				},
				{Property: "ZonalConfig", Member: "zonalConfig", Kind: "structure",
					Fields: []Field{
						{Property: "FirstZoneMonitorDurationInSeconds", Member: "firstZoneMonitorDurationInSeconds", Kind: "scalar"},
						{Property: "MinimumHealthyHostsPerZone", Member: "minimumHealthyHostsPerZone", Kind: "structure",
							Fields: []Field{
								{Property: "Type", Member: "type", Kind: "scalar"},
								{Property: "Value", Member: "value", Kind: "scalar"},
							},
						},
						{Property: "MonitorDurationInSeconds", Member: "monitorDurationInSeconds", Kind: "scalar"},
					},
				},
			},
		},
	})
}
