// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Kinesis::Channel": {
			Type:        "AWS::Kinesis::Channel",
			Protocol:    "awsJson1_1",
			SigningName: "kinesis",
			Host:        "kinesis.{region}.amazonaws.com",
			Target:      "Kinesis_20131202.DescribeChannel",
			Identifier: []Binding{
				{Property: "ChannelARN", Member: "ChannelARN", Location: "body"},
			},
			Response: []Step{{Name: "ChannelDescription"}},
			Fields: []Field{
				{Property: "ChannelARN", Member: "ChannelARN", Kind: "scalar"},
				{Property: "ChannelCreationTimestamp", Member: "ChannelCreationTimestamp", Kind: "timestamp"},
				{Property: "ChannelId", Member: "ChannelId", Kind: "scalar"},
				{Property: "ChannelName", Member: "ChannelName", Kind: "scalar"},
				{Property: "ChannelStatus", Member: "ChannelStatus", Kind: "scalar"},
				{Property: "EncryptionConfiguration", Member: "EncryptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "EncryptionType", Member: "EncryptionType", Kind: "scalar"},
						{Property: "KeyId", Member: "KeyId", Kind: "scalar"},
					},
				},
				{Property: "LoggingConfiguration", Member: "LoggingConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "CloudWatchLogs", Member: "CloudWatchLogs", Kind: "structure",
							Fields: []Field{
								{Property: "Enabled", Member: "Enabled", Kind: "scalar"},
								{Property: "LogGroupName", Member: "LogGroupName", Kind: "scalar"},
								{Property: "LogStreamName", Member: "LogStreamName", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "S3DestinationConfiguration", Member: "S3DestinationConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "DataFreshnessInSeconds", Member: "DataFreshnessInSeconds", Kind: "scalar"},
						{Property: "DeadLetterQueueS3Configuration", Member: "DeadLetterQueueS3Configuration", Kind: "structure",
							Fields: []Field{
								{Property: "BucketARN", Member: "BucketARN", Kind: "scalar"},
								{Property: "ErrorOutputPrefix", Member: "ErrorOutputPrefix", Kind: "scalar"},
								{Property: "ExpectedBucketOwner", Member: "ExpectedBucketOwner", Kind: "scalar"},
							},
						},
						{Property: "StorageConfiguration", Member: "StorageConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "BucketARN", Member: "BucketARN", Kind: "scalar"},
								{Property: "CompressionType", Member: "CompressionType", Kind: "scalar"},
								{Property: "ExpectedBucketOwner", Member: "ExpectedBucketOwner", Kind: "scalar"},
								{Property: "OutputKeyTemplate", Member: "OutputKeyTemplate", Kind: "scalar"},
								{Property: "StorageClass", Member: "StorageClass", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "S3TablesDestinationConfiguration", Member: "S3TablesDestinationConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "DataFreshnessInSeconds", Member: "DataFreshnessInSeconds", Kind: "scalar"},
						{Property: "DeadLetterQueueS3Configuration", Member: "DeadLetterQueueS3Configuration", Kind: "structure",
							Fields: []Field{
								{Property: "BucketARN", Member: "BucketARN", Kind: "scalar"},
								{Property: "ErrorOutputPrefix", Member: "ErrorOutputPrefix", Kind: "scalar"},
								{Property: "ExpectedBucketOwner", Member: "ExpectedBucketOwner", Kind: "scalar"},
							},
						},
						{Property: "S3TablesConfigurationList", Member: "S3TablesConfigurationList", Kind: "list",
							Fields: []Field{
								{Property: "CompressionType", Member: "CompressionType", Kind: "scalar"},
								{Property: "Namespace", Member: "Namespace", Kind: "scalar"},
								{Property: "PartitionSpec", Member: "PartitionSpec", Kind: "structure",
									Fields: []Field{
										{Property: "PartitionFields", Member: "PartitionFields", Kind: "list",
											Fields: []Field{
												{Property: "SourceName", Member: "SourceName", Kind: "scalar"},
												{Property: "Transform", Member: "Transform", Kind: "scalar"},
											},
										},
									},
								},
								{Property: "TableBucketARN", Member: "TableBucketARN", Kind: "scalar"},
								{Property: "TableName", Member: "TableName", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ServiceExecutionRoleARN", Member: "ServiceExecutionRoleARN", Kind: "scalar"},
				{Property: "StreamConfigurationList", Member: "StreamConfigurationList", Kind: "list",
					Fields: []Field{
						{Property: "RecordConfiguration", Member: "RecordConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "GSRSchemaARN", Member: "GSRSchemaARN", Kind: "scalar"},
								{Property: "RecordFormatType", Member: "RecordFormatType", Kind: "scalar"},
							},
						},
						{Property: "StreamARN", Member: "StreamARN", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::Kinesis::StreamConsumer": {
			Type:        "AWS::Kinesis::StreamConsumer",
			Protocol:    "awsJson1_1",
			SigningName: "kinesis",
			Host:        "kinesis.{region}.amazonaws.com",
			Target:      "Kinesis_20131202.DescribeStreamConsumer",
			Identifier: []Binding{
				{Property: "ConsumerARN", Member: "ConsumerARN", Location: "body"},
			},
			Response: []Step{{Name: "ConsumerDescription"}},
			Fields: []Field{
				{Property: "ConsumerARN", Member: "ConsumerARN", Kind: "scalar"},
				{Property: "ConsumerCreationTimestamp", Member: "ConsumerCreationTimestamp", Kind: "timestamp"},
				{Property: "ConsumerName", Member: "ConsumerName", Kind: "scalar"},
				{Property: "ConsumerStatus", Member: "ConsumerStatus", Kind: "scalar"},
				{Property: "StreamARN", Member: "StreamARN", Kind: "scalar"},
			},
		},
	})
}
