// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SSMQuickSetup::ConfigurationManager": {
			Type:        "AWS::SSMQuickSetup::ConfigurationManager",
			Protocol:    "restJson1",
			SigningName: "ssm-quicksetup",
			Complete:    true,
			Host:        "ssm-quicksetup.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/configurationManager/{ManagerArn}",
			Identifier: []Binding{
				{Property: "ManagerArn", Member: "ManagerArn", Location: "label"},
			},
			Fields: []Field{
				{Property: "ConfigurationDefinitions", Member: "ConfigurationDefinitions", Kind: "list",
					Fields: []Field{
						{Property: "LocalDeploymentAdministrationRoleArn", Member: "LocalDeploymentAdministrationRoleArn", Kind: "scalar"},
						{Property: "LocalDeploymentExecutionRoleName", Member: "LocalDeploymentExecutionRoleName", Kind: "scalar"},
						{Property: "Parameters", Member: "Parameters", Kind: "map"},
						{Property: "Type", Member: "Type", Kind: "scalar"},
						{Property: "TypeVersion", Member: "TypeVersion", Kind: "scalar"},
						{Property: "id", Member: "Id", Kind: "scalar"},
					},
				},
				{Property: "CreatedAt", Member: "CreatedAt", Kind: "timestamp"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "LastModifiedAt", Member: "LastModifiedAt", Kind: "timestamp"},
				{Property: "ManagerArn", Member: "ManagerArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "StatusSummaries", Member: "StatusSummaries", Kind: "list",
					Fields: []Field{
						{Property: "LastUpdatedAt", Member: "LastUpdatedAt", Kind: "timestamp"},
						{Property: "Status", Member: "Status", Kind: "scalar"},
						{Property: "StatusDetails", Member: "StatusDetails", Kind: "map"},
						{Property: "StatusMessage", Member: "StatusMessage", Kind: "scalar"},
						{Property: "StatusType", Member: "StatusType", Kind: "scalar"},
					},
				},
				{Property: "Tags", Member: "Tags", Kind: "map"},
			},
		},
	})
}
