// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::OpenSearchServerless::SecurityConfig": {
			Type:        "AWS::OpenSearchServerless::SecurityConfig",
			Protocol:    "awsJson1_0",
			SigningName: "aoss",
			Complete:    true,
			Host:        "aoss.{region}.amazonaws.com",
			Target:      "OpenSearchServerless.GetSecurityConfig",
			Identifier: []Binding{
				{Property: "Id", Member: "id", Location: "body"},
			},
			Response: []Step{{Name: "securityConfigDetail"}},
			Fields: []Field{
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "IamFederationOptions", Member: "iamFederationOptions", Kind: "structure",
					Fields: []Field{
						{Property: "GroupAttribute", Member: "groupAttribute", Kind: "scalar"},
						{Property: "UserAttribute", Member: "userAttribute", Kind: "scalar"},
					},
				},
				{Property: "IamIdentityCenterOptions", Member: "iamIdentityCenterOptions", Kind: "structure",
					Fields: []Field{
						{Property: "ApplicationArn", Member: "applicationArn", Kind: "scalar"},
						{Property: "ApplicationDescription", Member: "applicationDescription", Kind: "scalar"},
						{Property: "ApplicationName", Member: "applicationName", Kind: "scalar"},
						{Property: "GroupAttribute", Member: "groupAttribute", Kind: "scalar"},
						{Property: "InstanceArn", Member: "instanceArn", Kind: "scalar"},
						{Property: "UserAttribute", Member: "userAttribute", Kind: "scalar"},
					},
				},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "SamlOptions", Member: "samlOptions", Kind: "structure",
					Fields: []Field{
						{Property: "GroupAttribute", Member: "groupAttribute", Kind: "scalar"},
						{Property: "Metadata", Member: "metadata", Kind: "scalar"},
						{Property: "OpenSearchServerlessEntityId", Member: "openSearchServerlessEntityId", Kind: "scalar"},
						{Property: "SessionTimeout", Member: "sessionTimeout", Kind: "scalar"},
						{Property: "UserAttribute", Member: "userAttribute", Kind: "scalar"},
					},
				},
				{Property: "Type", Member: "type", Kind: "scalar"},
			},
		},
	})
}
