// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::QBusiness::Application": {
			Type:        "AWS::QBusiness::Application",
			Protocol:    "restJson1",
			SigningName: "qbusiness",
			Host:        "qbusiness.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/applications/{applicationId}",
			Identifier: []Binding{
				{Property: "ApplicationId", Member: "applicationId", Location: "label"},
			},
			Fields: []Field{
				{Property: "ApplicationArn", Member: "applicationArn", Kind: "scalar"},
				{Property: "ApplicationId", Member: "applicationId", Kind: "scalar"},
				{Property: "AttachmentsConfiguration", Member: "attachmentsConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "AttachmentsControlMode", Member: "attachmentsControlMode", Kind: "scalar"},
					},
				},
				{Property: "AutoSubscriptionConfiguration", Member: "autoSubscriptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "AutoSubscribe", Member: "autoSubscribe", Kind: "scalar"},
						{Property: "DefaultSubscriptionType", Member: "defaultSubscriptionType", Kind: "scalar"},
					},
				},
				{Property: "ClientIdsForOIDC", Member: "clientIdsForOIDC", Kind: "list"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "EncryptionConfiguration", Member: "encryptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyId", Member: "kmsKeyId", Kind: "scalar"},
					},
				},
				{Property: "IamIdentityProviderArn", Member: "iamIdentityProviderArn", Kind: "scalar"},
				{Property: "IdentityCenterApplicationArn", Member: "identityCenterApplicationArn", Kind: "scalar"},
				{Property: "IdentityType", Member: "identityType", Kind: "scalar"},
				{Property: "PersonalizationConfiguration", Member: "personalizationConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "PersonalizationControlMode", Member: "personalizationControlMode", Kind: "scalar"},
					},
				},
				{Property: "QAppsConfiguration", Member: "qAppsConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "QAppsControlMode", Member: "qAppsControlMode", Kind: "scalar"},
					},
				},
				{Property: "QuickSightConfiguration", Member: "quickSightConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "ClientNamespace", Member: "clientNamespace", Kind: "scalar"},
					},
				},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
