// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::KafkaConnect::Connector": {
			Type:        "AWS::KafkaConnect::Connector",
			Protocol:    "restJson1",
			SigningName: "kafkaconnect",
			Host:        "kafkaconnect.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/connectors/{connectorArn}",
			Identifier: []Binding{
				{Property: "ConnectorArn", Member: "connectorArn", Location: "label"},
			},
			Fields: []Field{
				{Property: "Capacity", Member: "capacity", Kind: "structure",
					Fields: []Field{
						{Property: "AutoScaling", Member: "autoScaling", Kind: "structure",
							Fields: []Field{
								{Property: "MaxAutoscalingTaskCount", Member: "maxAutoscalingTaskCount", Kind: "scalar"},
								{Property: "MaxWorkerCount", Member: "maxWorkerCount", Kind: "scalar"},
								{Property: "McuCount", Member: "mcuCount", Kind: "scalar"},
								{Property: "MinWorkerCount", Member: "minWorkerCount", Kind: "scalar"},
								{Property: "ScaleInPolicy", Member: "scaleInPolicy", Kind: "structure",
									Fields: []Field{
										{Property: "CpuUtilizationPercentage", Member: "cpuUtilizationPercentage", Kind: "scalar"},
									},
								},
								{Property: "ScaleOutPolicy", Member: "scaleOutPolicy", Kind: "structure",
									Fields: []Field{
										{Property: "CpuUtilizationPercentage", Member: "cpuUtilizationPercentage", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "ProvisionedCapacity", Member: "provisionedCapacity", Kind: "structure",
							Fields: []Field{
								{Property: "McuCount", Member: "mcuCount", Kind: "scalar"},
								{Property: "WorkerCount", Member: "workerCount", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ConnectorArn", Member: "connectorArn", Kind: "scalar"},
				{Property: "ConnectorConfiguration", Member: "connectorConfiguration", Kind: "map"},
				{Property: "ConnectorDescription", Member: "connectorDescription", Kind: "scalar"},
				{Property: "ConnectorName", Member: "connectorName", Kind: "scalar"},
				{Property: "KafkaCluster", Member: "kafkaCluster", Kind: "structure",
					Fields: []Field{
						{Property: "ApacheKafkaCluster", Member: "apacheKafkaCluster", Kind: "structure",
							Fields: []Field{
								{Property: "BootstrapServers", Member: "bootstrapServers", Kind: "scalar"},
								{Property: "Vpc", Member: "vpc", Kind: "structure",
									Fields: []Field{
										{Property: "SecurityGroups", Member: "securityGroups", Kind: "list"},
										{Property: "Subnets", Member: "subnets", Kind: "list"},
									},
								},
							},
						},
					},
				},
				{Property: "KafkaClusterClientAuthentication", Member: "kafkaClusterClientAuthentication", Kind: "structure",
					Fields: []Field{
						{Property: "AuthenticationType", Member: "authenticationType", Kind: "scalar"},
					},
				},
				{Property: "KafkaClusterEncryptionInTransit", Member: "kafkaClusterEncryptionInTransit", Kind: "structure",
					Fields: []Field{
						{Property: "EncryptionType", Member: "encryptionType", Kind: "scalar"},
					},
				},
				{Property: "KafkaConnectVersion", Member: "kafkaConnectVersion", Kind: "scalar"},
				{Property: "LogDelivery", Member: "logDelivery", Kind: "structure",
					Fields: []Field{
						{Property: "WorkerLogDelivery", Member: "workerLogDelivery", Kind: "structure",
							Fields: []Field{
								{Property: "CloudWatchLogs", Member: "cloudWatchLogs", Kind: "structure",
									Fields: []Field{
										{Property: "Enabled", Member: "enabled", Kind: "scalar"},
										{Property: "LogGroup", Member: "logGroup", Kind: "scalar"},
									},
								},
								{Property: "Firehose", Member: "firehose", Kind: "structure",
									Fields: []Field{
										{Property: "DeliveryStream", Member: "deliveryStream", Kind: "scalar"},
										{Property: "Enabled", Member: "enabled", Kind: "scalar"},
									},
								},
								{Property: "S3", Member: "s3", Kind: "structure",
									Fields: []Field{
										{Property: "Bucket", Member: "bucket", Kind: "scalar"},
										{Property: "Enabled", Member: "enabled", Kind: "scalar"},
										{Property: "Prefix", Member: "prefix", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{Property: "NetworkType", Member: "networkType", Kind: "scalar"},
				{Property: "Plugins", Member: "plugins", Kind: "list",
					Fields: []Field{
						{Property: "CustomPlugin", Member: "customPlugin", Kind: "structure",
							Fields: []Field{
								{Property: "CustomPluginArn", Member: "customPluginArn", Kind: "scalar"},
								{Property: "Revision", Member: "revision", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ServiceExecutionRoleArn", Member: "serviceExecutionRoleArn", Kind: "scalar"},
				{Property: "WorkerConfiguration", Member: "workerConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Revision", Member: "revision", Kind: "scalar"},
						{Property: "WorkerConfigurationArn", Member: "workerConfigurationArn", Kind: "scalar"},
					},
				},
			},
		},
	})
}
