// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Notifications::EventRule": {
			Type:        "AWS::Notifications::EventRule",
			Protocol:    "restJson1",
			SigningName: "notifications",
			Complete:    true,
			Host:        "notifications.{region}.api.aws",
			Method:      "GET",
			URI:         "/event-rules/{arn}",
			Identifier: []Binding{
				{Property: "Arn", Member: "arn", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreationTime", Member: "creationTime", Kind: "timestamp"},
				{Property: "EventPattern", Member: "eventPattern", Kind: "scalar"},
				{Property: "EventType", Member: "eventType", Kind: "scalar"},
				{Property: "ManagedRules", Member: "managedRules", Kind: "list"},
				{Property: "NotificationConfigurationArn", Member: "notificationConfigurationArn", Kind: "scalar"},
				{Property: "Regions", Member: "regions", Kind: "list"},
				{Property: "Source", Member: "source", Kind: "scalar"},
				{Property: "StatusSummaryByRegion", Member: "statusSummaryByRegion", Kind: "map"},
			},
		},
		"AWS::Notifications::NotificationConfiguration": {
			Type:        "AWS::Notifications::NotificationConfiguration",
			Protocol:    "restJson1",
			SigningName: "notifications",
			Host:        "notifications.{region}.api.aws",
			Method:      "GET",
			URI:         "/notification-configurations/{arn}",
			Identifier: []Binding{
				{Property: "Arn", Member: "arn", Location: "label"},
			},
			Fields: []Field{
				{Property: "AggregationDuration", Member: "aggregationDuration", Kind: "scalar"},
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreationTime", Member: "creationTime", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
	})
}
