// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::S3::Bucket": {
			Type:                  "AWS::S3::Bucket",
			Protocol:              "restXml",
			SigningName:           "s3",
			Host:                  "s3.{region}.amazonaws.com",
			DisableDoubleEncoding: true,
			Method:                "GET",
			URI:                   "/{Bucket}?versioning",
			Identifier: []Binding{
				{Property: "BucketName", Member: "Bucket", Location: "label"},
			},
			AbsentErrors: []string{"NoSuchBucket"},
			Fields: []Field{
				{Property: "Arn", Member: "arn:aws:s3:::{BucketName}", Kind: "template"},
				{Property: "BucketName", Member: "BucketName", Kind: "identifier"},
				{Property: "DomainName", Member: "{BucketName}.s3.amazonaws.com", Kind: "template"},
				{Property: "DualStackDomainName", Member: "{BucketName}.s3.dualstack.{region}.amazonaws.com", Kind: "template"},
				{Property: "RegionalDomainName", Member: "{BucketName}.s3.{region}.amazonaws.com", Kind: "template"},
				{Property: "VersioningConfiguration", Member: ".", Kind: "structure",
					Fields: []Field{
						{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
					},
				},
				{Property: "WebsiteURL", Member: "http://{BucketName}.s3-website.{region}.amazonaws.com", Kind: "template", Regions: map[string]string{"ap-northeast-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "ap-southeast-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "ap-southeast-2": "http://{BucketName}.s3-website-{region}.amazonaws.com", "eu-west-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "sa-east-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "us-east-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "us-west-1": "http://{BucketName}.s3-website-{region}.amazonaws.com", "us-west-2": "http://{BucketName}.s3-website-{region}.amazonaws.com"}},
			},
			AbsentIDs:            []string{"kraai-absent-probe-{account}-{region}"},
			UndeclaredReadErrors: []string{"NoSuchCORSConfiguration", "NoSuchPublicAccessBlockConfiguration", "NoSuchTagSet", "NoSuchWebsiteConfiguration", "ObjectLockConfigurationNotFoundError", "OwnershipControlsNotFoundError", "ReplicationConfigurationNotFoundError"},
			Also: []Reader{
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?abac",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket"},
					Fields: []Field{
						{Property: "AbacStatus", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?accelerate",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket"},
					Fields: []Field{
						{Property: "AccelerateConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "AccelerationStatus", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?encryption",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket"},
					Fields: []Field{
						{Property: "BucketEncryption", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "ServerSideEncryptionConfiguration", Member: "Rules", Kind: "list", XMLName: "Rule",
									Fields: []Field{
										{Property: "BlockedEncryptionTypes", Member: "BlockedEncryptionTypes", Kind: "structure", XMLName: "BlockedEncryptionTypes",
											Fields: []Field{
												{Property: "EncryptionType", Member: "EncryptionType", Kind: "list", XMLName: "EncryptionType", Scalar: "string"},
											},
										},
										{Property: "BucketKeyEnabled", Member: "BucketKeyEnabled", Kind: "scalar", XMLName: "BucketKeyEnabled", Scalar: "boolean"},
										{Property: "ServerSideEncryptionByDefault", Member: "ApplyServerSideEncryptionByDefault", Kind: "structure", XMLName: "ApplyServerSideEncryptionByDefault",
											Fields: []Field{
												{Property: "KMSMasterKeyID", Member: "KMSMasterKeyID", Kind: "scalar", XMLName: "KMSMasterKeyID", Scalar: "string"},
												{Property: "SSEAlgorithm", Member: "SSEAlgorithm", Kind: "scalar", XMLName: "SSEAlgorithm", Scalar: "string"},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?ownershipControls",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "OwnershipControlsNotFoundError"},
					Fields: []Field{
						{Property: "OwnershipControls", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "Rules", Member: "Rules", Kind: "list", XMLName: "Rule",
									Fields: []Field{
										{Property: "ObjectOwnership", Member: "ObjectOwnership", Kind: "scalar", XMLName: "ObjectOwnership", Scalar: "string"},
									},
								},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?publicAccessBlock",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "NoSuchPublicAccessBlockConfiguration"},
					Fields: []Field{
						{Property: "PublicAccessBlockConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "BlockPublicAcls", Member: "BlockPublicAcls", Kind: "scalar", XMLName: "BlockPublicAcls", Scalar: "boolean"},
								{Property: "BlockPublicPolicy", Member: "BlockPublicPolicy", Kind: "scalar", XMLName: "BlockPublicPolicy", Scalar: "boolean"},
								{Property: "IgnorePublicAcls", Member: "IgnorePublicAcls", Kind: "scalar", XMLName: "IgnorePublicAcls", Scalar: "boolean"},
								{Property: "RestrictPublicBuckets", Member: "RestrictPublicBuckets", Kind: "scalar", XMLName: "RestrictPublicBuckets", Scalar: "boolean"},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?tagging",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "NoSuchTagSet"},
					Fields: []Field{
						{Property: "Tags", Member: "TagSet", Kind: "list", XMLName: "TagSet", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?cors",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "NoSuchCORSConfiguration"},
					Fields: []Field{
						{Property: "CorsConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "CorsRules", Member: "CORSRules", Kind: "list", XMLName: "CORSRule",
									Fields: []Field{
										{Property: "AllowedHeaders", Member: "AllowedHeaders", Kind: "list", XMLName: "AllowedHeader", Scalar: "string"},
										{Property: "AllowedMethods", Member: "AllowedMethods", Kind: "list", XMLName: "AllowedMethod", Scalar: "string"},
										{Property: "AllowedOrigins", Member: "AllowedOrigins", Kind: "list", XMLName: "AllowedOrigin", Scalar: "string"},
										{Property: "ExposedHeaders", Member: "ExposeHeaders", Kind: "list", XMLName: "ExposeHeader", Scalar: "string"},
										{Property: "Id", Member: "ID", Kind: "scalar", XMLName: "ID", Scalar: "string"},
										{Property: "MaxAge", Member: "MaxAgeSeconds", Kind: "scalar", XMLName: "MaxAgeSeconds", Scalar: "number"},
									},
								},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?object-lock",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "ObjectLockConfigurationNotFoundError"},
					Fields: []Field{
						{Property: "ObjectLockConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "ObjectLockEnabled", Member: "ObjectLockEnabled", Kind: "scalar", XMLName: "ObjectLockEnabled", Scalar: "string"},
								{Property: "Rule", Member: "Rule", Kind: "structure", XMLName: "Rule",
									Fields: []Field{
										{Property: "DefaultRetention", Member: "DefaultRetention", Kind: "structure", XMLName: "DefaultRetention",
											Fields: []Field{
												{Property: "Days", Member: "Days", Kind: "scalar", XMLName: "Days", Scalar: "number"},
												{Property: "DefaultEventHold", Member: "DefaultEventHold", Kind: "structure", XMLName: "DefaultEventHold",
													Fields: []Field{
														{Property: "Days", Member: "Days", Kind: "scalar", XMLName: "Days", Scalar: "number"},
														{Property: "Years", Member: "Years", Kind: "scalar", XMLName: "Years", Scalar: "number"},
													},
												},
												{Property: "Mode", Member: "Mode", Kind: "scalar", XMLName: "Mode", Scalar: "string"},
												{Property: "Years", Member: "Years", Kind: "scalar", XMLName: "Years", Scalar: "number"},
											},
										},
									},
								},
							},
						},
						{Property: "ObjectLockEnabled", Member: "ObjectLockEnabled", Kind: "scalar", TrueWhen: []string{"Enabled"}, XMLName: "ObjectLockEnabled", Scalar: "string"},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?website",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "NoSuchWebsiteConfiguration"},
					Fields: []Field{
						{Property: "WebsiteConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "ErrorDocument", Member: "Key", Kind: "scalar", Via: []Step{{Name: "ErrorDocument"}}, XMLName: "Key", Scalar: "string"},
								{Property: "IndexDocument", Member: "Suffix", Kind: "scalar", Via: []Step{{Name: "IndexDocument"}}, XMLName: "Suffix", Scalar: "string"},
								{Property: "RedirectAllRequestsTo", Member: "RedirectAllRequestsTo", Kind: "structure", XMLName: "RedirectAllRequestsTo",
									Fields: []Field{
										{Property: "HostName", Member: "HostName", Kind: "scalar", XMLName: "HostName", Scalar: "string"},
										{Property: "Protocol", Member: "Protocol", Kind: "scalar", XMLName: "Protocol", Scalar: "string"},
									},
								},
								{Property: "RoutingRules", Member: "RoutingRules", Kind: "list", XMLName: "RoutingRules", Item: "RoutingRule",
									Fields: []Field{
										{Property: "RedirectRule", Member: "Redirect", Kind: "structure", XMLName: "Redirect",
											Fields: []Field{
												{Property: "HostName", Member: "HostName", Kind: "scalar", XMLName: "HostName", Scalar: "string"},
												{Property: "HttpRedirectCode", Member: "HttpRedirectCode", Kind: "scalar", XMLName: "HttpRedirectCode", Scalar: "string"},
												{Property: "Protocol", Member: "Protocol", Kind: "scalar", XMLName: "Protocol", Scalar: "string"},
												{Property: "ReplaceKeyPrefixWith", Member: "ReplaceKeyPrefixWith", Kind: "scalar", XMLName: "ReplaceKeyPrefixWith", Scalar: "string"},
												{Property: "ReplaceKeyWith", Member: "ReplaceKeyWith", Kind: "scalar", XMLName: "ReplaceKeyWith", Scalar: "string"},
											},
										},
										{Property: "RoutingRuleCondition", Member: "Condition", Kind: "structure", XMLName: "Condition",
											Fields: []Field{
												{Property: "HttpErrorCodeReturnedEquals", Member: "HttpErrorCodeReturnedEquals", Kind: "scalar", XMLName: "HttpErrorCodeReturnedEquals", Scalar: "string"},
												{Property: "KeyPrefixEquals", Member: "KeyPrefixEquals", Kind: "scalar", XMLName: "KeyPrefixEquals", Scalar: "string"},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?logging",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket"},
					Fields: []Field{
						{Property: "LoggingConfiguration", Member: "LoggingEnabled", Kind: "structure", XMLName: "LoggingEnabled",
							Fields: []Field{
								{Property: "DestinationBucketName", Member: "TargetBucket", Kind: "scalar", XMLName: "TargetBucket", Scalar: "string"},
								{Property: "LogFilePrefix", Member: "TargetPrefix", Kind: "scalar", XMLName: "TargetPrefix", Scalar: "string"},
								{Property: "TargetObjectKeyFormat", Member: "TargetObjectKeyFormat", Kind: "structure", XMLName: "TargetObjectKeyFormat",
									Fields: []Field{
										{Property: "PartitionedPrefix", Member: "PartitionedPrefix", Kind: "structure", XMLName: "PartitionedPrefix",
											Fields: []Field{
												{Property: "PartitionDateSource", Member: "PartitionDateSource", Kind: "scalar", XMLName: "PartitionDateSource", Scalar: "string"},
											},
										},
										{Property: "SimplePrefix", Member: "SimplePrefix", Kind: "scalar", XMLName: "SimplePrefix", Scalar: "string"},
									},
								},
							},
						},
					},
				},
				{
					Type:                  "AWS::S3::Bucket",
					Protocol:              "restXml",
					SigningName:           "s3",
					Host:                  "s3.{region}.amazonaws.com",
					DisableDoubleEncoding: true,
					Method:                "GET",
					URI:                   "/{Bucket}?replication",
					Identifier: []Binding{
						{Property: "BucketName", Member: "Bucket", Location: "label"},
					},
					AbsentErrors: []string{"NoSuchBucket", "ReplicationConfigurationNotFoundError"},
					Fields: []Field{
						{Property: "ReplicationConfiguration", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "Role", Member: "Role", Kind: "scalar", XMLName: "Role", Scalar: "string"},
								{Property: "Rules", Member: "Rules", Kind: "list", XMLName: "Rule",
									Fields: []Field{
										{Property: "DeleteMarkerReplication", Member: "DeleteMarkerReplication", Kind: "structure", XMLName: "DeleteMarkerReplication",
											Fields: []Field{
												{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
											},
										},
										{Property: "Destination", Member: "Destination", Kind: "structure", XMLName: "Destination",
											Fields: []Field{
												{Property: "AccessControlTranslation", Member: "AccessControlTranslation", Kind: "structure", XMLName: "AccessControlTranslation",
													Fields: []Field{
														{Property: "Owner", Member: "Owner", Kind: "scalar", XMLName: "Owner", Scalar: "string"},
													},
												},
												{Property: "Account", Member: "Account", Kind: "scalar", XMLName: "Account", Scalar: "string"},
												{Property: "Bucket", Member: "Bucket", Kind: "scalar", XMLName: "Bucket", Scalar: "string"},
												{Property: "EncryptionConfiguration", Member: "EncryptionConfiguration", Kind: "structure", XMLName: "EncryptionConfiguration",
													Fields: []Field{
														{Property: "ReplicaKmsKeyID", Member: "ReplicaKmsKeyID", Kind: "scalar", XMLName: "ReplicaKmsKeyID", Scalar: "string"},
													},
												},
												{Property: "Metrics", Member: "Metrics", Kind: "structure", XMLName: "Metrics",
													Fields: []Field{
														{Property: "EventThreshold", Member: "EventThreshold", Kind: "structure", XMLName: "EventThreshold",
															Fields: []Field{
																{Property: "Minutes", Member: "Minutes", Kind: "scalar", XMLName: "Minutes", Scalar: "number"},
															},
														},
														{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
													},
												},
												{Property: "ReplicationTime", Member: "ReplicationTime", Kind: "structure", XMLName: "ReplicationTime",
													Fields: []Field{
														{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
														{Property: "Time", Member: "Time", Kind: "structure", XMLName: "Time",
															Fields: []Field{
																{Property: "Minutes", Member: "Minutes", Kind: "scalar", XMLName: "Minutes", Scalar: "number"},
															},
														},
													},
												},
												{Property: "StorageClass", Member: "StorageClass", Kind: "scalar", XMLName: "StorageClass", Scalar: "string"},
											},
										},
										{Property: "Filter", Member: "Filter", Kind: "structure", XMLName: "Filter",
											Fields: []Field{
												{Property: "And", Member: "And", Kind: "structure", XMLName: "And",
													Fields: []Field{
														{Property: "Prefix", Member: "Prefix", Kind: "scalar", XMLName: "Prefix", Scalar: "string"},
														{Property: "TagFilters", Member: "Tags", Kind: "list", XMLName: "Tag",
															Fields: []Field{
																{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
																{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
															},
														},
													},
												},
												{Property: "Prefix", Member: "Prefix", Kind: "scalar", XMLName: "Prefix", Scalar: "string"},
												{Property: "TagFilter", Member: "Tag", Kind: "structure", XMLName: "Tag",
													Fields: []Field{
														{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
														{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
													},
												},
											},
										},
										{Property: "Id", Member: "ID", Kind: "scalar", XMLName: "ID", Scalar: "string"},
										{Property: "Priority", Member: "Priority", Kind: "scalar", XMLName: "Priority", Scalar: "number"},
										{Property: "SourceSelectionCriteria", Member: "SourceSelectionCriteria", Kind: "structure", XMLName: "SourceSelectionCriteria",
											Fields: []Field{
												{Property: "ReplicaModifications", Member: "ReplicaModifications", Kind: "structure", XMLName: "ReplicaModifications",
													Fields: []Field{
														{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
													},
												},
												{Property: "SseKmsEncryptedObjects", Member: "SseKmsEncryptedObjects", Kind: "structure", XMLName: "SseKmsEncryptedObjects",
													Fields: []Field{
														{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
													},
												},
											},
										},
										{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
									},
								},
							},
						},
					},
				},
			},
		},
	})
}
