// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Signer::SigningProfile": {
			Type:        "AWS::Signer::SigningProfile",
			Protocol:    "restJson1",
			SigningName: "signer",
			Host:        "signer.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/signing-profiles/{profileName}",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "profileName", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "PlatformId", Member: "platformId", Kind: "scalar"},
				{Property: "ProfileName", Member: "profileName", Kind: "scalar"},
				{Property: "ProfileVersion", Member: "profileVersion", Kind: "scalar"},
				{Property: "ProfileVersionArn", Member: "profileVersionArn", Kind: "scalar"},
				{Property: "SignatureValidityPeriod", Member: "signatureValidityPeriod", Kind: "structure",
					Fields: []Field{
						{Property: "Type", Member: "type", Kind: "scalar"},
						{Property: "Value", Member: "value", Kind: "scalar"},
					},
				},
			},
		},
	})
}
