// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::KendraRanking::ExecutionPlan": {
			Type:        "AWS::KendraRanking::ExecutionPlan",
			Protocol:    "awsJson1_0",
			SigningName: "kendra-ranking",
			Host:        "kendra-ranking.{region}.amazonaws.com",
			Target:      "AWSKendraRerankingFrontendService.DescribeRescoreExecutionPlan",
			Identifier: []Binding{
				{Property: "Id", Member: "Id", Location: "body"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "CapacityUnits", Member: "CapacityUnits", Kind: "structure",
					Fields: []Field{
						{Property: "RescoreCapacityUnits", Member: "RescoreCapacityUnits", Kind: "scalar"},
					},
				},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
			},
		},
	})
}
