// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CodeStarConnections::Connection": {
			Type:        "AWS::CodeStarConnections::Connection",
			Protocol:    "awsJson1_0",
			SigningName: "codestar-connections",
			Host:        "codestar-connections.{region}.amazonaws.com",
			Target:      "CodeStar_connections_20191201.GetConnection",
			Identifier: []Binding{
				{Property: "ConnectionArn", Member: "ConnectionArn", Location: "body"},
			},
			Response: []Step{{Name: "Connection"}},
			Fields: []Field{
				{Property: "ConnectionArn", Member: "ConnectionArn", Kind: "scalar"},
				{Property: "ConnectionName", Member: "ConnectionName", Kind: "scalar"},
				{Property: "ConnectionStatus", Member: "ConnectionStatus", Kind: "scalar"},
				{Property: "HostArn", Member: "HostArn", Kind: "scalar"},
				{Property: "OwnerAccountId", Member: "OwnerAccountId", Kind: "scalar"},
				{Property: "ProviderType", Member: "ProviderType", Kind: "scalar"},
			},
		},
	})
}
