// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::InternetMonitor::Monitor": {
			Type:        "AWS::InternetMonitor::Monitor",
			Protocol:    "restJson1",
			SigningName: "internetmonitor",
			Host:        "internetmonitor.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v20210603/Monitors/{MonitorName}",
			Identifier: []Binding{
				{Property: "MonitorName", Member: "MonitorName", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "CreatedAt", Kind: "timestamp"},
				{Property: "HealthEventsConfig", Member: "HealthEventsConfig", Kind: "structure",
					Fields: []Field{
						{Property: "AvailabilityLocalHealthEventsConfig", Member: "AvailabilityLocalHealthEventsConfig", Kind: "structure",
							Fields: []Field{
								{Property: "HealthScoreThreshold", Member: "HealthScoreThreshold", Kind: "scalar"},
								{Property: "MinTrafficImpact", Member: "MinTrafficImpact", Kind: "scalar"},
								{Property: "Status", Member: "Status", Kind: "scalar"},
							},
						},
						{Property: "AvailabilityScoreThreshold", Member: "AvailabilityScoreThreshold", Kind: "scalar"},
						{Property: "PerformanceLocalHealthEventsConfig", Member: "PerformanceLocalHealthEventsConfig", Kind: "structure",
							Fields: []Field{
								{Property: "HealthScoreThreshold", Member: "HealthScoreThreshold", Kind: "scalar"},
								{Property: "MinTrafficImpact", Member: "MinTrafficImpact", Kind: "scalar"},
								{Property: "Status", Member: "Status", Kind: "scalar"},
							},
						},
						{Property: "PerformanceScoreThreshold", Member: "PerformanceScoreThreshold", Kind: "scalar"},
					},
				},
				{Property: "InternetMeasurementsLogDelivery", Member: "InternetMeasurementsLogDelivery", Kind: "structure",
					Fields: []Field{
						{Property: "S3Config", Member: "S3Config", Kind: "structure",
							Fields: []Field{
								{Property: "BucketName", Member: "BucketName", Kind: "scalar"},
								{Property: "BucketPrefix", Member: "BucketPrefix", Kind: "scalar"},
								{Property: "LogDeliveryStatus", Member: "LogDeliveryStatus", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "MaxCityNetworksToMonitor", Member: "MaxCityNetworksToMonitor", Kind: "scalar"},
				{Property: "ModifiedAt", Member: "ModifiedAt", Kind: "timestamp"},
				{Property: "MonitorArn", Member: "MonitorArn", Kind: "scalar"},
				{Property: "MonitorName", Member: "MonitorName", Kind: "scalar"},
				{Property: "ProcessingStatus", Member: "ProcessingStatus", Kind: "scalar"},
				{Property: "ProcessingStatusInfo", Member: "ProcessingStatusInfo", Kind: "scalar"},
				{Property: "Resources", Member: "Resources", Kind: "list"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
				{Property: "TrafficPercentageToMonitor", Member: "TrafficPercentageToMonitor", Kind: "scalar"},
			},
		},
	})
}
