// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::AppIntegrations::EventIntegration": {
			Type:        "AWS::AppIntegrations::EventIntegration",
			Protocol:    "restJson1",
			SigningName: "app-integrations",
			Host:        "app-integrations.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/eventIntegrations/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "EventBridgeBus", Member: "EventBridgeBus", Kind: "scalar"},
				{Property: "EventFilter", Member: "EventFilter", Kind: "structure",
					Fields: []Field{
						{Property: "Source", Member: "Source", Kind: "scalar"},
					},
				},
				{Property: "EventIntegrationArn", Member: "EventIntegrationArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
			},
		},
	})
}
