// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CloudWatch::Alarm": {
			Type:        "AWS::CloudWatch::Alarm",
			Protocol:    "awsJson1_0",
			SigningName: "monitoring",
			Complete:    true,
			Production:  true,
			Host:        "monitoring.{region}.amazonaws.com",
			Target:      "GraniteServiceVersion20100801.DescribeAlarms",
			Identifier: []Binding{
				{Property: "AlarmName", Member: "AlarmNames", Location: "body", List: true},
			},
			PageToken: []string{"NextToken"},
			Response:  []Step{{Name: "MetricAlarms", List: true}},
			Fields: []Field{
				{Property: "ActionsEnabled", Member: "ActionsEnabled", Kind: "scalar"},
				{Property: "AlarmActions", Member: "AlarmActions", Kind: "list"},
				{Property: "AlarmDescription", Member: "AlarmDescription", Kind: "scalar"},
				{Property: "AlarmName", Member: "AlarmName", Kind: "scalar"},
				{Property: "Arn", Member: "AlarmArn", Kind: "scalar"},
				{Property: "ComparisonOperator", Member: "ComparisonOperator", Kind: "scalar"},
				{Property: "DatapointsToAlarm", Member: "DatapointsToAlarm", Kind: "scalar"},
				{Property: "Dimensions", Member: "Dimensions", Kind: "list",
					Fields: []Field{
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "EvaluateLowSampleCountPercentile", Member: "EvaluateLowSampleCountPercentile", Kind: "scalar"},
				{Property: "EvaluationCriteria", Member: "EvaluationCriteria", Kind: "structure",
					Fields: []Field{
						{Property: "PromQLCriteria", Member: "PromQLCriteria", Kind: "structure",
							Fields: []Field{
								{Property: "PendingPeriod", Member: "PendingPeriod", Kind: "scalar"},
								{Property: "Query", Member: "Query", Kind: "scalar"},
								{Property: "RecoveryPeriod", Member: "RecoveryPeriod", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "EvaluationInterval", Member: "EvaluationInterval", Kind: "scalar"},
				{Property: "EvaluationPeriods", Member: "EvaluationPeriods", Kind: "scalar"},
				{Property: "EvaluationWindow", Member: "EvaluationWindow", Kind: "structure",
					Fields: []Field{
						{Property: "SlidingWindow", Member: "SlidingWindow", Kind: "scalar"},
						{Property: "WallClockWindow", Member: "WallClockWindow", Kind: "structure",
							Fields: []Field{
								{Property: "Timezone", Member: "Timezone", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ExtendedStatistic", Member: "ExtendedStatistic", Kind: "scalar"},
				{Property: "InsufficientDataActions", Member: "InsufficientDataActions", Kind: "list"},
				{Property: "MetricName", Member: "MetricName", Kind: "scalar"},
				{Property: "Metrics", Member: "Metrics", Kind: "list",
					Fields: []Field{
						{Property: "AccountId", Member: "AccountId", Kind: "scalar"},
						{Property: "Expression", Member: "Expression", Kind: "scalar"},
						{Property: "Id", Member: "Id", Kind: "scalar"},
						{Property: "Label", Member: "Label", Kind: "scalar"},
						{Property: "MetricStat", Member: "MetricStat", Kind: "structure",
							Fields: []Field{
								{Property: "Metric", Member: "Metric", Kind: "structure",
									Fields: []Field{
										{Property: "Dimensions", Member: "Dimensions", Kind: "list",
											Fields: []Field{
												{Property: "Name", Member: "Name", Kind: "scalar"},
												{Property: "Value", Member: "Value", Kind: "scalar"},
											},
										},
										{Property: "MetricName", Member: "MetricName", Kind: "scalar"},
										{Property: "Namespace", Member: "Namespace", Kind: "scalar"},
									},
								},
								{Property: "Period", Member: "Period", Kind: "scalar"},
								{Property: "Stat", Member: "Stat", Kind: "scalar"},
								{Property: "Unit", Member: "Unit", Kind: "scalar"},
							},
						},
						{Property: "Period", Member: "Period", Kind: "scalar"},
						{Property: "ReturnData", Member: "ReturnData", Kind: "scalar"},
					},
				},
				{Property: "Namespace", Member: "Namespace", Kind: "scalar"},
				{Property: "OKActions", Member: "OKActions", Kind: "list"},
				{Property: "Period", Member: "Period", Kind: "scalar"},
				{Property: "Statistic", Member: "Statistic", Kind: "scalar"},
				{Property: "Threshold", Member: "Threshold", Kind: "scalar"},
				{Property: "ThresholdMetricId", Member: "ThresholdMetricId", Kind: "scalar"},
				{Property: "TreatMissingData", Member: "TreatMissingData", Kind: "scalar"},
				{Property: "Unit", Member: "Unit", Kind: "scalar"},
				{Property: "WarmUpConfiguration", Member: "WarmUpConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "OnlyStartEvaluatingAfterWarmUpPeriodEnds", Member: "OnlyStartEvaluatingAfterWarmUpPeriodEnds", Kind: "scalar"},
						{Property: "WarmUpPeriodDurationInMinutes", Member: "WarmUpPeriodDurationInMinutes", Kind: "scalar"},
					},
				},
			},
			AbsentIDs: []string{"kraai-absent-probe-alarm"},
			Capture: []Field{
				{Property: "Arn", Member: "AlarmArn", Kind: "scalar"},
			},
			Also: []Reader{
				{
					Type:        "AWS::CloudWatch::Alarm",
					Protocol:    "awsJson1_0",
					SigningName: "monitoring",
					Host:        "monitoring.{region}.amazonaws.com",
					Target:      "GraniteServiceVersion20100801.ListTagsForResource",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceARN", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
	})
}
