// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Proton::EnvironmentAccountConnection": {
			Type:        "AWS::Proton::EnvironmentAccountConnection",
			Protocol:    "awsJson1_0",
			SigningName: "proton",
			Host:        "proton.{region}.amazonaws.com",
			Target:      "AwsProton20200720.GetEnvironmentAccountConnection",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "id", Value: "{Arn:arnName}"},
			},
			Response: []Step{{Name: "environmentAccountConnection"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CodebuildRoleArn", Member: "codebuildRoleArn", Kind: "scalar"},
				{Property: "ComponentRoleArn", Member: "componentRoleArn", Kind: "scalar"},
				{Property: "EnvironmentAccountId", Member: "environmentAccountId", Kind: "scalar"},
				{Property: "EnvironmentName", Member: "environmentName", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "ManagementAccountId", Member: "managementAccountId", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
		"AWS::Proton::EnvironmentTemplate": {
			Type:        "AWS::Proton::EnvironmentTemplate",
			Protocol:    "awsJson1_0",
			SigningName: "proton",
			Host:        "proton.{region}.amazonaws.com",
			Target:      "AwsProton20200720.GetEnvironmentTemplate",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "name", Value: "{Arn:arnName}"},
			},
			Response: []Step{{Name: "environmentTemplate"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "EncryptionKey", Member: "encryptionKey", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Provisioning", Member: "provisioning", Kind: "scalar"},
			},
		},
		"AWS::Proton::ServiceTemplate": {
			Type:        "AWS::Proton::ServiceTemplate",
			Protocol:    "awsJson1_0",
			SigningName: "proton",
			Host:        "proton.{region}.amazonaws.com",
			Target:      "AwsProton20200720.GetServiceTemplate",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "name", Value: "{Arn:arnName}"},
			},
			Response: []Step{{Name: "serviceTemplate"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "EncryptionKey", Member: "encryptionKey", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "PipelineProvisioning", Member: "pipelineProvisioning", Kind: "scalar"},
			},
		},
	})
}
