// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IAM::Role": {
			Type:          "AWS::IAM::Role",
			Protocol:      "awsQuery",
			SigningName:   "iam",
			Complete:      true,
			Production:    true,
			Host:          "iam.amazonaws.com",
			SigningRegion: "us-east-1",
			Action:        "GetRole",
			Version:       "2010-05-08",
			Wrapper:       "GetRoleResult",
			Identifier: []Binding{
				{Property: "RoleName", Member: "RoleName", Location: "form", Name: "RoleName"},
			},
			AbsentErrors: []string{"NoSuchEntity"},
			Response:     []Step{{Name: "Role"}},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", XMLName: "Arn", Scalar: "string"},
				{Property: "AssumeRolePolicyDocument", Member: "AssumeRolePolicyDocument", Kind: "scalar", Transform: "urlJson", XMLName: "AssumeRolePolicyDocument", Scalar: "string"},
				{Property: "Description", Member: "Description", Kind: "scalar", XMLName: "Description", Scalar: "string"},
				{Property: "MaxSessionDuration", Member: "MaxSessionDuration", Kind: "scalar", XMLName: "MaxSessionDuration", Scalar: "number"},
				{Property: "Path", Member: "Path", Kind: "scalar", XMLName: "Path", Scalar: "string"},
				{Property: "PermissionsBoundary", Member: "PermissionsBoundaryArn", Kind: "scalar", Via: []Step{{Name: "PermissionsBoundary"}}, XMLName: "PermissionsBoundaryArn", Scalar: "string"},
				{Property: "RoleId", Member: "RoleId", Kind: "scalar", XMLName: "RoleId", Scalar: "string"},
				{Property: "RoleName", Member: "RoleName", Kind: "scalar", XMLName: "RoleName", Scalar: "string"},
				{Property: "Tags", Member: "Tags", Kind: "list", XMLName: "Tags", Item: "member",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
						{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
					},
				},
			},
			AbsentIDs:         []string{"kraai-absent-probe"},
			LifecycleComplete: true,
			Create:            &MutationCall{Operation: "CreateRole", Target: "AWSIdentityManagementV20100508.CreateRole", NameProperty: "RoleName", NameTag: "kraai:resource-name", NameMaxLength: 64, Input: map[string]any{"AssumeRolePolicyDocument": "{AssumeRolePolicyDocument:json}", "Description": "{Description}", "MaxSessionDuration": "{MaxSessionDuration}", "Path": "{Path}", "PermissionsBoundary": "{PermissionsBoundary}", "RoleName": "{RoleName}", "Tags": "{Tags}"}, Properties: []string{"AssumeRolePolicyDocument", "Description", "MaxSessionDuration", "Path", "PermissionsBoundary", "RoleName", "Tags"}, Identifier: map[string]string{"RoleName": "CreateRoleResult.Role.RoleName"}, Form: map[string]FormStep{"AssumeRolePolicyDocument": {Key: "AssumeRolePolicyDocument", Kind: "scalar"}, "Description": {Key: "Description", Kind: "scalar"}, "MaxSessionDuration": {Key: "MaxSessionDuration", Kind: "scalar"}, "Path": {Key: "Path", Kind: "scalar"}, "PermissionsBoundary": {Key: "PermissionsBoundary", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "member"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}},
			Delete:            &MutationCall{Operation: "DeleteRole", Target: "AWSIdentityManagementV20100508.DeleteRole", Input: map[string]any{"RoleName": "{RoleName}"}, AbsentErrors: []string{"NoSuchEntity"}, RetryErrors: []string{"DeleteConflict"}, Clear: []string{"ManagedPolicyArns", "Policies"}, Form: map[string]FormStep{"RoleName": {Key: "RoleName", Kind: "scalar"}}},
			Update: []MutationCall{
				MutationCall{Operation: "UpdateAssumeRolePolicy", Target: "AWSIdentityManagementV20100508.UpdateAssumeRolePolicy", Input: map[string]any{"PolicyDocument": "{AssumeRolePolicyDocument:json}", "RoleName": "{RoleName}"}, RetryErrors: []string{"NoSuchEntity"}, Properties: []string{"AssumeRolePolicyDocument"}, Form: map[string]FormStep{"PolicyDocument": {Key: "PolicyDocument", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}},
				MutationCall{Operation: "UpdateRole", Target: "AWSIdentityManagementV20100508.UpdateRole", Input: map[string]any{"Description": "{Description}", "MaxSessionDuration": "{MaxSessionDuration}", "RoleName": "{RoleName}"}, RetryErrors: []string{"NoSuchEntity"}, Properties: []string{"Description", "MaxSessionDuration"}, Form: map[string]FormStep{"Description": {Key: "Description", Kind: "scalar"}, "MaxSessionDuration": {Key: "MaxSessionDuration", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}},
				MutationCall{Operation: "PutRolePermissionsBoundary", Target: "AWSIdentityManagementV20100508.PutRolePermissionsBoundary", Input: map[string]any{"PermissionsBoundary": "{PermissionsBoundary}", "RoleName": "{RoleName}"}, RetryErrors: []string{"NoSuchEntity"}, Properties: []string{"PermissionsBoundary"}, Form: map[string]FormStep{"PermissionsBoundary": {Key: "PermissionsBoundary", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}},
				MutationCall{ListProperty: "ManagedPolicyArns", Key: []string{"."}, OneAtATime: true, Add: &MutationCall{Operation: "AttachRolePolicy", Target: "AWSIdentityManagementV20100508.AttachRolePolicy", TagProperty: "ManagedPolicyArns", Input: map[string]any{"PolicyArn": "{element}", "RoleName": "{RoleName}"}, RetryErrors: []string{"NoSuchEntity"}, Form: map[string]FormStep{"PolicyArn": {Key: "PolicyArn", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}}, Remove: &MutationCall{Operation: "DetachRolePolicy", Target: "AWSIdentityManagementV20100508.DetachRolePolicy", TagProperty: "ManagedPolicyArns", Input: map[string]any{"PolicyArn": "{element}", "RoleName": "{RoleName}"}, Form: map[string]FormStep{"PolicyArn": {Key: "PolicyArn", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}}},
				MutationCall{ListProperty: "Policies", Key: []string{"PolicyName"}, OneAtATime: true, Add: &MutationCall{Operation: "PutRolePolicy", Target: "AWSIdentityManagementV20100508.PutRolePolicy", TagProperty: "Policies", Input: map[string]any{"PolicyDocument": "{element.PolicyDocument:json}", "PolicyName": "{element.PolicyName}", "RoleName": "{RoleName}"}, RetryErrors: []string{"NoSuchEntity"}, Form: map[string]FormStep{"PolicyDocument": {Key: "PolicyDocument", Kind: "scalar"}, "PolicyName": {Key: "PolicyName", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}}, Remove: &MutationCall{Operation: "DeleteRolePolicy", Target: "AWSIdentityManagementV20100508.DeleteRolePolicy", TagProperty: "Policies", Input: map[string]any{"PolicyName": "{element.PolicyName}", "RoleName": "{RoleName}"}, Form: map[string]FormStep{"PolicyName": {Key: "PolicyName", Kind: "scalar"}, "RoleName": {Key: "RoleName", Kind: "scalar"}}}},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "TagRole", Target: "AWSIdentityManagementV20100508.TagRole", TagProperty: "Tags", Input: map[string]any{"RoleName": "{RoleName}", "Tags": "{added}"}, RetryErrors: []string{"NoSuchEntity"}, Form: map[string]FormStep{"RoleName": {Key: "RoleName", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "member"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}}, Remove: &MutationCall{Operation: "UntagRole", Target: "AWSIdentityManagementV20100508.UntagRole", Input: map[string]any{"RoleName": "{RoleName}", "TagKeys": "{removed}"}, RetryErrors: []string{"NoSuchEntity"}, Form: map[string]FormStep{"RoleName": {Key: "RoleName", Kind: "scalar"}, "TagKeys": {Key: "TagKeys", Kind: "list", Item: "member"}, "TagKeys[]": {Key: "", Kind: "scalar"}}}},
			},
			Also: []Reader{
				{
					Type:          "AWS::IAM::Role",
					Protocol:      "awsQuery",
					SigningName:   "iam",
					Host:          "iam.amazonaws.com",
					SigningRegion: "us-east-1",
					Action:        "ListAttachedRolePolicies",
					Version:       "2010-05-08",
					Wrapper:       "ListAttachedRolePoliciesResult",
					Identifier: []Binding{
						{Property: "RoleName", Member: "RoleName", Location: "form", Name: "RoleName"},
					},
					PageToken: []string{"Marker"},
					Fields: []Field{
						{Property: "ManagedPolicyArns", Member: "PolicyArn", Kind: "scalar", Via: []Step{{Name: "AttachedPolicies", List: true, Item: "member"}}, XMLName: "PolicyArn", Scalar: "string"},
					},
				},
				{
					Type:          "AWS::IAM::Role",
					Protocol:      "awsQuery",
					SigningName:   "iam",
					Host:          "iam.amazonaws.com",
					SigningRegion: "us-east-1",
					Action:        "ListRolePolicies",
					Version:       "2010-05-08",
					Wrapper:       "ListRolePoliciesResult",
					Identifier: []Binding{
						{Property: "RoleName", Member: "RoleName", Location: "form", Name: "RoleName"},
					},
					PageToken: []string{"Marker"},
					Fields: []Field{
						{Property: "Policies", Member: "PolicyNames", Kind: "list", Wrap: "PolicyName", XMLName: "PolicyNames", Item: "member", Scalar: "string"},
					},
				},
				{
					Type:          "AWS::IAM::Role",
					Protocol:      "awsQuery",
					SigningName:   "iam",
					Host:          "iam.amazonaws.com",
					SigningRegion: "us-east-1",
					Action:        "GetRolePolicy",
					Version:       "2010-05-08",
					Wrapper:       "GetRolePolicyResult",
					Identifier: []Binding{
						{Property: "RoleName", Member: "", Location: "placeholder"},
					},
					Input: []Binding{
						Binding{Location: "form", Member: "PolicyName", Name: "PolicyName", Value: "{PolicyName}"},
						Binding{Location: "form", Member: "RoleName", Name: "RoleName", Value: "{RoleName}"},
					},
					AbsentErrors: []string{"NoSuchEntity"},
					Each:         "Policies",
					Fields: []Field{
						{Property: "PolicyDocument", Member: "PolicyDocument", Kind: "scalar", Transform: "urlJson", XMLName: "PolicyDocument", Scalar: "string"},
					},
				},
			},
			Mutable: true,
		},
	})
}
