// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::AppConfig::DeploymentStrategy": {
			Type:        "AWS::AppConfig::DeploymentStrategy",
			Protocol:    "restJson1",
			SigningName: "appconfig",
			Host:        "appconfig.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/deploymentstrategies/{DeploymentStrategyId}",
			Identifier: []Binding{
				{Property: "Id", Member: "DeploymentStrategyId", Location: "label"},
			},
			Fields: []Field{
				{Property: "DeploymentDurationInMinutes", Member: "DeploymentDurationInMinutes", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "FinalBakeTimeInMinutes", Member: "FinalBakeTimeInMinutes", Kind: "scalar"},
				{Property: "GrowthFactor", Member: "GrowthFactor", Kind: "scalar"},
				{Property: "GrowthType", Member: "GrowthType", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ReplicateTo", Member: "ReplicateTo", Kind: "scalar"},
			},
		},
		"AWS::AppConfig::Extension": {
			Type:        "AWS::AppConfig::Extension",
			Protocol:    "restJson1",
			SigningName: "appconfig",
			Host:        "appconfig.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/extensions/{ExtensionIdentifier}",
			Identifier: []Binding{
				{Property: "Id", Member: "ExtensionIdentifier", Location: "label"},
			},
			Fields: []Field{
				{Property: "Actions", Member: "Actions", Kind: "map"},
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Parameters", Member: "Parameters", Kind: "map"},
				{Property: "VersionNumber", Member: "VersionNumber", Kind: "scalar"},
			},
		},
		"AWS::AppConfig::ExtensionAssociation": {
			Type:        "AWS::AppConfig::ExtensionAssociation",
			Protocol:    "restJson1",
			SigningName: "appconfig",
			Host:        "appconfig.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/extensionassociations/{ExtensionAssociationId}",
			Identifier: []Binding{
				{Property: "Id", Member: "ExtensionAssociationId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "ExtensionArn", Member: "ExtensionArn", Kind: "scalar"},
				{Property: "ExtensionVersionNumber", Member: "ExtensionVersionNumber", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Parameters", Member: "Parameters", Kind: "map"},
				{Property: "ResourceArn", Member: "ResourceArn", Kind: "scalar"},
			},
		},
	})
}
