// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MediaPackageV2::ChannelGroup": {
			Type:        "AWS::MediaPackageV2::ChannelGroup",
			Protocol:    "restJson1",
			SigningName: "mediapackagev2",
			Host:        "mediapackagev2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/channelGroup/{ChannelGroupName}",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "ChannelGroupName", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "ChannelGroupName", Member: "ChannelGroupName", Kind: "scalar"},
				{Property: "CreatedAt", Member: "CreatedAt", Kind: "timestamp"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "EgressDomain", Member: "EgressDomain", Kind: "scalar"},
				{Property: "ModifiedAt", Member: "ModifiedAt", Kind: "timestamp"},
			},
		},
	})
}
