// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IoTCoreDeviceAdvisor::SuiteDefinition": {
			Type:        "AWS::IoTCoreDeviceAdvisor::SuiteDefinition",
			Protocol:    "restJson1",
			SigningName: "iotdeviceadvisor",
			Host:        "api.iotdeviceadvisor.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/suiteDefinitions/{suiteDefinitionId}",
			Identifier: []Binding{
				{Property: "SuiteDefinitionId", Member: "suiteDefinitionId", Location: "label"},
			},
			Fields: []Field{
				{Property: "SuiteDefinitionArn", Member: "suiteDefinitionArn", Kind: "scalar"},
				{Property: "SuiteDefinitionConfiguration", Member: "suiteDefinitionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "DevicePermissionRoleArn", Member: "devicePermissionRoleArn", Kind: "scalar"},
						{Property: "Devices", Member: "devices", Kind: "list",
							Fields: []Field{
								{Property: "CertificateArn", Member: "certificateArn", Kind: "scalar"},
								{Property: "ThingArn", Member: "thingArn", Kind: "scalar"},
							},
						},
						{Property: "IntendedForQualification", Member: "intendedForQualification", Kind: "scalar"},
						{Property: "RootGroup", Member: "rootGroup", Kind: "scalar"},
						{Property: "SuiteDefinitionName", Member: "suiteDefinitionName", Kind: "scalar"},
					},
				},
				{Property: "SuiteDefinitionId", Member: "suiteDefinitionId", Kind: "scalar"},
				{Property: "SuiteDefinitionVersion", Member: "suiteDefinitionVersion", Kind: "scalar"},
			},
		},
	})
}
