// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Events::Endpoint": {
			Type:        "AWS::Events::Endpoint",
			Protocol:    "awsJson1_1",
			SigningName: "events",
			Complete:    true,
			Host:        "events.{region}.amazonaws.com",
			Target:      "AWSEvents.DescribeEndpoint",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "body"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "EndpointId", Member: "EndpointId", Kind: "scalar"},
				{Property: "EndpointUrl", Member: "EndpointUrl", Kind: "scalar"},
				{Property: "EventBuses", Member: "EventBuses", Kind: "list",
					Fields: []Field{
						{Property: "EventBusArn", Member: "EventBusArn", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ReplicationConfig", Member: "ReplicationConfig", Kind: "structure",
					Fields: []Field{
						{Property: "State", Member: "State", Kind: "scalar"},
					},
				},
				{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
				{Property: "RoutingConfig", Member: "RoutingConfig", Kind: "structure",
					Fields: []Field{
						{Property: "FailoverConfig", Member: "FailoverConfig", Kind: "structure",
							Fields: []Field{
								{Property: "Primary", Member: "Primary", Kind: "structure",
									Fields: []Field{
										{Property: "HealthCheck", Member: "HealthCheck", Kind: "scalar"},
									},
								},
								{Property: "Secondary", Member: "Secondary", Kind: "structure",
									Fields: []Field{
										{Property: "Route", Member: "Route", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{Property: "State", Member: "State", Kind: "scalar"},
				{Property: "StateReason", Member: "StateReason", Kind: "scalar"},
			},
		},
		"AWS::Events::Rule": {
			Type:        "AWS::Events::Rule",
			Protocol:    "awsJson1_1",
			SigningName: "events",
			Complete:    true,
			Production:  true,
			Host:        "events.{region}.amazonaws.com",
			Target:      "AWSEvents.DescribeRule",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "EventBusName", Value: "{Arn:arnParent}"},
				Binding{Location: "body", Member: "Name", Value: "{Arn:arnName}"},
			},
			AbsentErrors: []string{"ResourceNotFoundException"},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "EventBusName", Member: "EventBusName", Kind: "scalar"},
				{Property: "EventPattern", Member: "EventPattern", Kind: "scalar", Transform: "json"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
				{Property: "RuleName", Member: "Name", Kind: "scalar"},
				{Property: "ScheduleExpression", Member: "ScheduleExpression", Kind: "scalar"},
				{Property: "State", Member: "State", Kind: "scalar"},
			},
			AbsentIDs: []string{"arn:aws:events:{region}:{account}:rule/kraai-absent-probe"},
			Also: []Reader{
				{
					Type:        "AWS::Events::Rule",
					Protocol:    "awsJson1_1",
					SigningName: "events",
					Host:        "events.{region}.amazonaws.com",
					Target:      "AWSEvents.ListTargetsByRule",
					Identifier: []Binding{
						{Property: "Arn", Member: "", Location: "placeholder"},
					},
					Input: []Binding{
						Binding{Location: "body", Member: "EventBusName", Value: "{Arn:arnParent}"},
						Binding{Location: "body", Member: "Rule", Value: "{Arn:arnName}"},
					},
					Fields: []Field{
						{Property: "Targets", Member: "Targets", Kind: "list",
							Fields: []Field{
								{Property: "AppSyncParameters", Member: "AppSyncParameters", Kind: "structure",
									Fields: []Field{
										{Property: "GraphQLOperation", Member: "GraphQLOperation", Kind: "scalar"},
									},
								},
								{Property: "Arn", Member: "Arn", Kind: "scalar"},
								{Property: "BatchParameters", Member: "BatchParameters", Kind: "structure",
									Fields: []Field{
										{Property: "ArrayProperties", Member: "ArrayProperties", Kind: "structure",
											Fields: []Field{
												{Property: "Size", Member: "Size", Kind: "scalar"},
											},
										},
										{Property: "JobDefinition", Member: "JobDefinition", Kind: "scalar"},
										{Property: "JobName", Member: "JobName", Kind: "scalar"},
										{Property: "RetryStrategy", Member: "RetryStrategy", Kind: "structure",
											Fields: []Field{
												{Property: "Attempts", Member: "Attempts", Kind: "scalar"},
											},
										},
									},
								},
								{Property: "DeadLetterConfig", Member: "DeadLetterConfig", Kind: "structure",
									Fields: []Field{
										{Property: "Arn", Member: "Arn", Kind: "scalar"},
									},
								},
								{Property: "EcsParameters", Member: "EcsParameters", Kind: "structure",
									Fields: []Field{
										{Property: "CapacityProviderStrategy", Member: "CapacityProviderStrategy", Kind: "list",
											Fields: []Field{
												{Property: "Base", Member: "base", Kind: "scalar"},
												{Property: "CapacityProvider", Member: "capacityProvider", Kind: "scalar"},
												{Property: "Weight", Member: "weight", Kind: "scalar"},
											},
										},
										{Property: "EnableECSManagedTags", Member: "EnableECSManagedTags", Kind: "scalar"},
										{Property: "EnableExecuteCommand", Member: "EnableExecuteCommand", Kind: "scalar"},
										{Property: "Group", Member: "Group", Kind: "scalar"},
										{Property: "LaunchType", Member: "LaunchType", Kind: "scalar"},
										{Property: "NetworkConfiguration", Member: "NetworkConfiguration", Kind: "structure",
											Fields: []Field{
												{Property: "AwsVpcConfiguration", Member: "awsvpcConfiguration", Kind: "structure",
													Fields: []Field{
														{Property: "AssignPublicIp", Member: "AssignPublicIp", Kind: "scalar"},
														{Property: "SecurityGroups", Member: "SecurityGroups", Kind: "list"},
														{Property: "Subnets", Member: "Subnets", Kind: "list"},
													},
												},
											},
										},
										{Property: "PlacementConstraints", Member: "PlacementConstraints", Kind: "list",
											Fields: []Field{
												{Property: "Expression", Member: "expression", Kind: "scalar"},
												{Property: "Type", Member: "type", Kind: "scalar"},
											},
										},
										{Property: "PlacementStrategies", Member: "PlacementStrategy", Kind: "list",
											Fields: []Field{
												{Property: "Field", Member: "field", Kind: "scalar"},
												{Property: "Type", Member: "type", Kind: "scalar"},
											},
										},
										{Property: "PlatformVersion", Member: "PlatformVersion", Kind: "scalar"},
										{Property: "PropagateTags", Member: "PropagateTags", Kind: "scalar"},
										{Property: "ReferenceId", Member: "ReferenceId", Kind: "scalar"},
										{Property: "TagList", Member: "Tags", Kind: "list",
											Fields: []Field{
												{Property: "Key", Member: "Key", Kind: "scalar"},
												{Property: "Value", Member: "Value", Kind: "scalar"},
											},
										},
										{Property: "TaskCount", Member: "TaskCount", Kind: "scalar"},
										{Property: "TaskDefinitionArn", Member: "TaskDefinitionArn", Kind: "scalar"},
									},
								},
								{Property: "HttpParameters", Member: "HttpParameters", Kind: "structure",
									Fields: []Field{
										{Property: "HeaderParameters", Member: "HeaderParameters", Kind: "map"},
										{Property: "PathParameterValues", Member: "PathParameterValues", Kind: "list"},
										{Property: "QueryStringParameters", Member: "QueryStringParameters", Kind: "map"},
									},
								},
								{Property: "Id", Member: "Id", Kind: "scalar"},
								{Property: "Input", Member: "Input", Kind: "scalar"},
								{Property: "InputPath", Member: "InputPath", Kind: "scalar"},
								{Property: "InputTransformer", Member: "InputTransformer", Kind: "structure",
									Fields: []Field{
										{Property: "InputPathsMap", Member: "InputPathsMap", Kind: "map"},
										{Property: "InputTemplate", Member: "InputTemplate", Kind: "scalar"},
									},
								},
								{Property: "KinesisParameters", Member: "KinesisParameters", Kind: "structure",
									Fields: []Field{
										{Property: "PartitionKeyPath", Member: "PartitionKeyPath", Kind: "scalar"},
									},
								},
								{Property: "RedshiftDataParameters", Member: "RedshiftDataParameters", Kind: "structure",
									Fields: []Field{
										{Property: "Database", Member: "Database", Kind: "scalar"},
										{Property: "DbUser", Member: "DbUser", Kind: "scalar"},
										{Property: "SecretManagerArn", Member: "SecretManagerArn", Kind: "scalar"},
										{Property: "Sql", Member: "Sql", Kind: "scalar"},
										{Property: "Sqls", Member: "Sqls", Kind: "list"},
										{Property: "StatementName", Member: "StatementName", Kind: "scalar"},
										{Property: "WithEvent", Member: "WithEvent", Kind: "scalar"},
									},
								},
								{Property: "RetryPolicy", Member: "RetryPolicy", Kind: "structure",
									Fields: []Field{
										{Property: "MaximumEventAgeInSeconds", Member: "MaximumEventAgeInSeconds", Kind: "scalar"},
										{Property: "MaximumRetryAttempts", Member: "MaximumRetryAttempts", Kind: "scalar"},
									},
								},
								{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
								{Property: "RunCommandParameters", Member: "RunCommandParameters", Kind: "structure",
									Fields: []Field{
										{Property: "RunCommandTargets", Member: "RunCommandTargets", Kind: "list",
											Fields: []Field{
												{Property: "Key", Member: "Key", Kind: "scalar"},
												{Property: "Values", Member: "Values", Kind: "list"},
											},
										},
									},
								},
								{Property: "SageMakerPipelineParameters", Member: "SageMakerPipelineParameters", Kind: "structure",
									Fields: []Field{
										{Property: "PipelineParameterList", Member: "PipelineParameterList", Kind: "list",
											Fields: []Field{
												{Property: "Name", Member: "Name", Kind: "scalar"},
												{Property: "Value", Member: "Value", Kind: "scalar"},
											},
										},
									},
								},
								{Property: "SqsParameters", Member: "SqsParameters", Kind: "structure",
									Fields: []Field{
										{Property: "MessageGroupId", Member: "MessageGroupId", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{
					Type:        "AWS::Events::Rule",
					Protocol:    "awsJson1_1",
					SigningName: "events",
					Host:        "events.{region}.amazonaws.com",
					Target:      "AWSEvents.ListTagsForResource",
					Identifier: []Binding{
						{Property: "Arn", Member: "ResourceARN", Location: "body"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
	})
}
