// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MediaTailor::Channel": {
			Type:        "AWS::MediaTailor::Channel",
			Protocol:    "restJson1",
			SigningName: "mediatailor",
			Host:        "api.mediatailor.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/channel/{ChannelName}",
			Identifier: []Binding{
				{Property: "ChannelName", Member: "ChannelName", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Audiences", Member: "Audiences", Kind: "list"},
				{Property: "ChannelName", Member: "ChannelName", Kind: "scalar"},
				{Property: "FillerSlate", Member: "FillerSlate", Kind: "structure",
					Fields: []Field{
						{Property: "SourceLocationName", Member: "SourceLocationName", Kind: "scalar"},
						{Property: "VodSourceName", Member: "VodSourceName", Kind: "scalar"},
					},
				},
				{Property: "LogConfiguration", Member: "LogConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "LogTypes", Member: "LogTypes", Kind: "list"},
					},
				},
				{Property: "Outputs", Member: "Outputs", Kind: "list",
					Fields: []Field{
						{Property: "DashPlaylistSettings", Member: "DashPlaylistSettings", Kind: "structure",
							Fields: []Field{
								{Property: "ManifestWindowSeconds", Member: "ManifestWindowSeconds", Kind: "scalar"},
								{Property: "MinBufferTimeSeconds", Member: "MinBufferTimeSeconds", Kind: "scalar"},
								{Property: "MinUpdatePeriodSeconds", Member: "MinUpdatePeriodSeconds", Kind: "scalar"},
								{Property: "SuggestedPresentationDelaySeconds", Member: "SuggestedPresentationDelaySeconds", Kind: "scalar"},
							},
						},
						{Property: "HlsPlaylistSettings", Member: "HlsPlaylistSettings", Kind: "structure",
							Fields: []Field{
								{Property: "AdMarkupType", Member: "AdMarkupType", Kind: "list"},
								{Property: "ManifestWindowSeconds", Member: "ManifestWindowSeconds", Kind: "scalar"},
							},
						},
						{Property: "ManifestName", Member: "ManifestName", Kind: "scalar"},
						{Property: "SourceGroup", Member: "SourceGroup", Kind: "scalar"},
					},
				},
				{Property: "PlaybackMode", Member: "PlaybackMode", Kind: "scalar"},
				{Property: "Tier", Member: "Tier", Kind: "scalar"},
				{Property: "TimeShiftConfiguration", Member: "TimeShiftConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "MaxTimeDelaySeconds", Member: "MaxTimeDelaySeconds", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::MediaTailor::Function": {
			Type:        "AWS::MediaTailor::Function",
			Protocol:    "restJson1",
			SigningName: "mediatailor",
			Host:        "api.mediatailor.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/function/{FunctionId}",
			Identifier: []Binding{
				{Property: "FunctionId", Member: "FunctionId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "CustomOutputConfiguration", Member: "CustomOutputConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Output", Member: "Output", Kind: "map"},
						{Property: "Runtime", Member: "Runtime", Kind: "scalar"},
					},
				},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "FunctionId", Member: "FunctionId", Kind: "scalar"},
				{Property: "FunctionType", Member: "FunctionType", Kind: "scalar"},
				{Property: "HttpRequestConfiguration", Member: "HttpRequestConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Body", Member: "Body", Kind: "scalar"},
						{Property: "Headers", Member: "Headers", Kind: "map"},
						{Property: "MethodType", Member: "MethodType", Kind: "scalar"},
						{Property: "Output", Member: "Output", Kind: "map"},
						{Property: "RequestTimeoutMilliseconds", Member: "RequestTimeoutMilliseconds", Kind: "scalar"},
						{Property: "Runtime", Member: "Runtime", Kind: "scalar"},
						{Property: "Url", Member: "Url", Kind: "scalar"},
					},
				},
				{Property: "SequentialExecutorConfiguration", Member: "SequentialExecutorConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "FunctionList", Member: "FunctionList", Kind: "list",
							Fields: []Field{
								{Property: "FunctionId", Member: "FunctionId", Kind: "scalar"},
								{Property: "RunCondition", Member: "RunCondition", Kind: "scalar"},
							},
						},
						{Property: "Output", Member: "Output", Kind: "map"},
						{Property: "Runtime", Member: "Runtime", Kind: "scalar"},
						{Property: "TimeoutMilliseconds", Member: "TimeoutMilliseconds", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::MediaTailor::SourceLocation": {
			Type:        "AWS::MediaTailor::SourceLocation",
			Protocol:    "restJson1",
			SigningName: "mediatailor",
			Host:        "api.mediatailor.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/sourceLocation/{SourceLocationName}",
			Identifier: []Binding{
				{Property: "SourceLocationName", Member: "SourceLocationName", Location: "label"},
			},
			Fields: []Field{
				{Property: "AccessConfiguration", Member: "AccessConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "AccessType", Member: "AccessType", Kind: "scalar"},
						{Property: "SecretsManagerAccessTokenConfiguration", Member: "SecretsManagerAccessTokenConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "HeaderName", Member: "HeaderName", Kind: "scalar"},
								{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
								{Property: "SecretStringKey", Member: "SecretStringKey", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "DefaultSegmentDeliveryConfiguration", Member: "DefaultSegmentDeliveryConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "BaseUrl", Member: "BaseUrl", Kind: "scalar"},
					},
				},
				{Property: "HttpConfiguration", Member: "HttpConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "BaseUrl", Member: "BaseUrl", Kind: "scalar"},
					},
				},
				{Property: "SegmentDeliveryConfigurations", Member: "SegmentDeliveryConfigurations", Kind: "list",
					Fields: []Field{
						{Property: "BaseUrl", Member: "BaseUrl", Kind: "scalar"},
						{Property: "Name", Member: "Name", Kind: "scalar"},
					},
				},
				{Property: "SourceLocationName", Member: "SourceLocationName", Kind: "scalar"},
			},
		},
	})
}
