// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Timestream::InfluxDBCluster": {
			Type:        "AWS::Timestream::InfluxDBCluster",
			Protocol:    "awsJson1_0",
			SigningName: "timestream-influxdb",
			Host:        "timestream-influxdb.{region}.amazonaws.com",
			Target:      "AmazonTimestreamInfluxDB.GetDbCluster",
			Identifier: []Binding{
				{Property: "Id", Member: "dbClusterId", Location: "body"},
			},
			Fields: []Field{
				{Property: "AllocatedStorage", Member: "allocatedStorage", Kind: "scalar"},
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "DbInstanceType", Member: "dbInstanceType", Kind: "scalar"},
				{Property: "DbParameterGroupIdentifier", Member: "dbParameterGroupIdentifier", Kind: "scalar"},
				{Property: "DbStorageType", Member: "dbStorageType", Kind: "scalar"},
				{Property: "DeploymentType", Member: "deploymentType", Kind: "scalar"},
				{Property: "Endpoint", Member: "endpoint", Kind: "scalar"},
				{Property: "EngineType", Member: "engineType", Kind: "scalar"},
				{Property: "FailoverMode", Member: "failoverMode", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "InfluxAuthParametersSecretArn", Member: "influxAuthParametersSecretArn", Kind: "scalar"},
				{Property: "LogDeliveryConfiguration", Member: "logDeliveryConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "S3Configuration", Member: "s3Configuration", Kind: "structure",
							Fields: []Field{
								{Property: "BucketName", Member: "bucketName", Kind: "scalar"},
								{Property: "Enabled", Member: "enabled", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "MaintenanceSchedule", Member: "maintenanceSchedule", Kind: "structure",
					Fields: []Field{
						{Property: "PreferredMaintenanceWindow", Member: "preferredMaintenanceWindow", Kind: "scalar"},
						{Property: "Timezone", Member: "timezone", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "NetworkType", Member: "networkType", Kind: "scalar"},
				{Property: "NextMaintenanceTime", Member: "nextMaintenanceTime", Kind: "timestamp"},
				{Property: "Port", Member: "port", Kind: "scalar"},
				{Property: "PubliclyAccessible", Member: "publiclyAccessible", Kind: "scalar"},
				{Property: "ReaderEndpoint", Member: "readerEndpoint", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "VpcSecurityGroupIds", Member: "vpcSecurityGroupIds", Kind: "list"},
				{Property: "VpcSubnetIds", Member: "vpcSubnetIds", Kind: "list"},
			},
		},
		"AWS::Timestream::InfluxDBInstance": {
			Type:        "AWS::Timestream::InfluxDBInstance",
			Protocol:    "awsJson1_0",
			SigningName: "timestream-influxdb",
			Host:        "timestream-influxdb.{region}.amazonaws.com",
			Target:      "AmazonTimestreamInfluxDB.GetDbInstance",
			Identifier: []Binding{
				{Property: "Id", Member: "identifier", Location: "body"},
			},
			Fields: []Field{
				{Property: "AllocatedStorage", Member: "allocatedStorage", Kind: "scalar"},
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "AvailabilityZone", Member: "availabilityZone", Kind: "scalar"},
				{Property: "DbInstanceType", Member: "dbInstanceType", Kind: "scalar"},
				{Property: "DbParameterGroupIdentifier", Member: "dbParameterGroupIdentifier", Kind: "scalar"},
				{Property: "DbStorageType", Member: "dbStorageType", Kind: "scalar"},
				{Property: "DeploymentType", Member: "deploymentType", Kind: "scalar"},
				{Property: "Endpoint", Member: "endpoint", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "InfluxAuthParametersSecretArn", Member: "influxAuthParametersSecretArn", Kind: "scalar"},
				{Property: "LogDeliveryConfiguration", Member: "logDeliveryConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "S3Configuration", Member: "s3Configuration", Kind: "structure",
							Fields: []Field{
								{Property: "BucketName", Member: "bucketName", Kind: "scalar"},
								{Property: "Enabled", Member: "enabled", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "MaintenanceSchedule", Member: "maintenanceSchedule", Kind: "structure",
					Fields: []Field{
						{Property: "PreferredMaintenanceWindow", Member: "preferredMaintenanceWindow", Kind: "scalar"},
						{Property: "Timezone", Member: "timezone", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "NetworkType", Member: "networkType", Kind: "scalar"},
				{Property: "NextMaintenanceTime", Member: "nextMaintenanceTime", Kind: "timestamp"},
				{Property: "Port", Member: "port", Kind: "scalar"},
				{Property: "PubliclyAccessible", Member: "publiclyAccessible", Kind: "scalar"},
				{Property: "SecondaryAvailabilityZone", Member: "secondaryAvailabilityZone", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "VpcSecurityGroupIds", Member: "vpcSecurityGroupIds", Kind: "list"},
				{Property: "VpcSubnetIds", Member: "vpcSubnetIds", Kind: "list"},
			},
		},
	})
}
