// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::VoiceID::Domain": {
			Type:        "AWS::VoiceID::Domain",
			Protocol:    "awsJson1_0",
			SigningName: "voiceid",
			Host:        "voiceid.{region}.amazonaws.com",
			Target:      "VoiceID.DescribeDomain",
			Identifier: []Binding{
				{Property: "DomainId", Member: "DomainId", Location: "body"},
			},
			Response: []Step{{Name: "Domain"}},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "DomainId", Member: "DomainId", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ServerSideEncryptionConfiguration", Member: "ServerSideEncryptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyId", Member: "KmsKeyId", Kind: "scalar"},
					},
				},
			},
		},
	})
}
