// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::WorkspacesInstances::WorkspaceInstance": {
			Type:        "AWS::WorkspacesInstances::WorkspaceInstance",
			Protocol:    "awsJson1_0",
			SigningName: "workspaces-instances",
			Host:        "workspaces-instances.{region}.api.aws",
			Target:      "EUCMIFrontendAPIService.GetWorkspaceInstance",
			Identifier: []Binding{
				{Property: "WorkspaceInstanceId", Member: "WorkspaceInstanceId", Location: "body"},
			},
			Fields: []Field{
				{Property: "EC2ManagedInstance", Member: "EC2ManagedInstance", Kind: "structure",
					Fields: []Field{
						{Property: "InstanceId", Member: "InstanceId", Kind: "scalar"},
					},
				},
				{Property: "ProvisionState", Member: "ProvisionState", Kind: "scalar"},
				{Property: "WorkspaceInstanceId", Member: "WorkspaceInstanceId", Kind: "scalar"},
			},
		},
	})
}
