// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MGN::NetworkMigrationDefinition": {
			Type:        "AWS::MGN::NetworkMigrationDefinition",
			Protocol:    "restJson1",
			SigningName: "mgn",
			Host:        "mgn.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/network-migration/GetNetworkMigrationDefinition",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "networkMigrationDefinitionID", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "NetworkMigrationDefinitionID", Member: "networkMigrationDefinitionID", Kind: "scalar"},
				{Property: "ScopeTags", Member: "scopeTags", Kind: "map"},
				{Property: "SourceConfigurations", Member: "sourceConfigurations", Kind: "list",
					Fields: []Field{
						{Property: "SourceEnvironment", Member: "sourceEnvironment", Kind: "scalar"},
						{Property: "SourceS3Configuration", Member: "sourceS3Configuration", Kind: "structure",
							Fields: []Field{
								{Property: "S3Bucket", Member: "s3Bucket", Kind: "scalar"},
								{Property: "S3BucketOwner", Member: "s3BucketOwner", Kind: "scalar"},
								{Property: "S3Key", Member: "s3Key", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "TargetDeployment", Member: "targetDeployment", Kind: "scalar"},
				{Property: "TargetNetwork", Member: "targetNetwork", Kind: "structure",
					Fields: []Field{
						{Property: "InboundCidr", Member: "inboundCidr", Kind: "scalar"},
						{Property: "InspectionCidr", Member: "inspectionCidr", Kind: "scalar"},
						{Property: "OutboundCidr", Member: "outboundCidr", Kind: "scalar"},
						{Property: "Topology", Member: "topology", Kind: "scalar"},
					},
				},
				{Property: "TargetS3Configuration", Member: "targetS3Configuration", Kind: "structure",
					Fields: []Field{
						{Property: "S3Bucket", Member: "s3Bucket", Kind: "scalar"},
						{Property: "S3BucketOwner", Member: "s3BucketOwner", Kind: "scalar"},
					},
				},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
