// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MediaLive::Cluster": {
			Type:        "AWS::MediaLive::Cluster",
			Protocol:    "restJson1",
			SigningName: "medialive",
			Host:        "medialive.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/prod/clusters/{ClusterId}",
			Identifier: []Binding{
				{Property: "Id", Member: "ClusterId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", JSONName: "arn"},
				{Property: "ChannelIds", Member: "ChannelIds", Kind: "list", JSONName: "channelIds"},
				{Property: "ClusterType", Member: "ClusterType", Kind: "scalar", JSONName: "clusterType"},
				{Property: "Id", Member: "Id", Kind: "scalar", JSONName: "id"},
				{Property: "InstanceRoleArn", Member: "InstanceRoleArn", Kind: "scalar", JSONName: "instanceRoleArn"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "NetworkSettings", Member: "NetworkSettings", Kind: "structure", JSONName: "networkSettings",
					Fields: []Field{
						{Property: "DefaultRoute", Member: "DefaultRoute", Kind: "scalar", JSONName: "defaultRoute"},
						{Property: "InterfaceMappings", Member: "InterfaceMappings", Kind: "list", JSONName: "interfaceMappings",
							Fields: []Field{
								{Property: "LogicalInterfaceName", Member: "LogicalInterfaceName", Kind: "scalar", JSONName: "logicalInterfaceName"},
								{Property: "NetworkId", Member: "NetworkId", Kind: "scalar", JSONName: "networkId"},
							},
						},
					},
				},
				{Property: "State", Member: "State", Kind: "scalar", JSONName: "state"},
			},
		},
		"AWS::MediaLive::Network": {
			Type:        "AWS::MediaLive::Network",
			Protocol:    "restJson1",
			SigningName: "medialive",
			Host:        "medialive.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/prod/networks/{NetworkId}",
			Identifier: []Binding{
				{Property: "Id", Member: "NetworkId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", JSONName: "arn"},
				{Property: "AssociatedClusterIds", Member: "AssociatedClusterIds", Kind: "list", JSONName: "associatedClusterIds"},
				{Property: "Id", Member: "Id", Kind: "scalar", JSONName: "id"},
				{Property: "IpPools", Member: "IpPools", Kind: "list", JSONName: "ipPools",
					Fields: []Field{
						{Property: "Cidr", Member: "Cidr", Kind: "scalar", JSONName: "cidr"},
					},
				},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "Routes", Member: "Routes", Kind: "list", JSONName: "routes",
					Fields: []Field{
						{Property: "Cidr", Member: "Cidr", Kind: "scalar", JSONName: "cidr"},
						{Property: "Gateway", Member: "Gateway", Kind: "scalar", JSONName: "gateway"},
					},
				},
				{Property: "State", Member: "State", Kind: "scalar", JSONName: "state"},
			},
		},
		"AWS::MediaLive::SdiSource": {
			Type:        "AWS::MediaLive::SdiSource",
			Protocol:    "restJson1",
			SigningName: "medialive",
			Host:        "medialive.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/prod/sdiSources/{SdiSourceId}",
			Identifier: []Binding{
				{Property: "Id", Member: "SdiSourceId", Location: "label"},
			},
			Response: []Step{{Name: "sdiSource"}},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", JSONName: "arn"},
				{Property: "Id", Member: "Id", Kind: "scalar", JSONName: "id"},
				{Property: "Inputs", Member: "Inputs", Kind: "list", JSONName: "inputs"},
				{Property: "Mode", Member: "Mode", Kind: "scalar", JSONName: "mode"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "State", Member: "State", Kind: "scalar", JSONName: "state"},
				{Property: "Type", Member: "Type", Kind: "scalar", JSONName: "type"},
			},
		},
	})
}
