// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::VerifiedPermissions::PolicyStoreAlias": {
			Type:        "AWS::VerifiedPermissions::PolicyStoreAlias",
			Protocol:    "awsJson1_0",
			SigningName: "verifiedpermissions",
			Complete:    true,
			Host:        "verifiedpermissions.{region}.amazonaws.com",
			Target:      "VerifiedPermissions.GetPolicyStoreAlias",
			Identifier: []Binding{
				{Property: "AliasName", Member: "aliasName", Location: "body"},
			},
			Fields: []Field{
				{Property: "AliasName", Member: "aliasName", Kind: "scalar"},
				{Property: "PolicyStoreId", Member: "policyStoreId", Kind: "scalar"},
			},
		},
	})
}
