// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SES::ContactList": {
			Type:        "AWS::SES::ContactList",
			Protocol:    "restJson1",
			SigningName: "ses",
			Complete:    true,
			Host:        "email.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v2/email/contact-lists/{ContactListName}",
			Identifier: []Binding{
				{Property: "ContactListName", Member: "ContactListName", Location: "label"},
			},
			Fields: []Field{
				{Property: "ContactListName", Member: "ContactListName", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Tags", Member: "Tags", Kind: "list",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "Topics", Member: "Topics", Kind: "list",
					Fields: []Field{
						{Property: "DefaultSubscriptionStatus", Member: "DefaultSubscriptionStatus", Kind: "scalar"},
						{Property: "Description", Member: "Description", Kind: "scalar"},
						{Property: "DisplayName", Member: "DisplayName", Kind: "scalar"},
						{Property: "TopicName", Member: "TopicName", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::SES::CustomVerificationEmailTemplate": {
			Type:        "AWS::SES::CustomVerificationEmailTemplate",
			Protocol:    "awsQuery",
			SigningName: "ses",
			Host:        "email.{region}.amazonaws.com",
			Action:      "GetCustomVerificationEmailTemplate",
			Version:     "2010-12-01",
			Wrapper:     "GetCustomVerificationEmailTemplateResult",
			Identifier: []Binding{
				{Property: "TemplateName", Member: "TemplateName", Location: "form", Name: "TemplateName"},
			},
			Fields: []Field{
				{Property: "FailureRedirectionURL", Member: "FailureRedirectionURL", Kind: "scalar", XMLName: "FailureRedirectionURL", Scalar: "string"},
				{Property: "FromEmailAddress", Member: "FromEmailAddress", Kind: "scalar", XMLName: "FromEmailAddress", Scalar: "string"},
				{Property: "SuccessRedirectionURL", Member: "SuccessRedirectionURL", Kind: "scalar", XMLName: "SuccessRedirectionURL", Scalar: "string"},
				{Property: "TemplateContent", Member: "TemplateContent", Kind: "scalar", XMLName: "TemplateContent", Scalar: "string"},
				{Property: "TemplateName", Member: "TemplateName", Kind: "scalar", XMLName: "TemplateName", Scalar: "string"},
				{Property: "TemplateSubject", Member: "TemplateSubject", Kind: "scalar", XMLName: "TemplateSubject", Scalar: "string"},
			},
		},
		"AWS::SES::MailManagerAddressList": {
			Type:        "AWS::SES::MailManagerAddressList",
			Protocol:    "awsJson1_0",
			SigningName: "ses",
			Host:        "mail-manager.{region}.amazonaws.com",
			Target:      "MailManagerSvc.GetAddressList",
			Identifier: []Binding{
				{Property: "AddressListId", Member: "AddressListId", Location: "body"},
			},
			Fields: []Field{
				{Property: "AddressListArn", Member: "AddressListArn", Kind: "scalar"},
				{Property: "AddressListId", Member: "AddressListId", Kind: "scalar"},
				{Property: "AddressListName", Member: "AddressListName", Kind: "scalar"},
			},
		},
		"AWS::SES::MailManagerRuleSet": {
			Type:        "AWS::SES::MailManagerRuleSet",
			Protocol:    "awsJson1_0",
			SigningName: "ses",
			Host:        "mail-manager.{region}.amazonaws.com",
			Target:      "MailManagerSvc.GetRuleSet",
			Identifier: []Binding{
				{Property: "RuleSetId", Member: "RuleSetId", Location: "body"},
			},
			Fields: []Field{
				{Property: "RuleSetArn", Member: "RuleSetArn", Kind: "scalar"},
				{Property: "RuleSetId", Member: "RuleSetId", Kind: "scalar"},
				{Property: "RuleSetName", Member: "RuleSetName", Kind: "scalar"},
				{Property: "Rules", Member: "Rules", Kind: "list",
					Fields: []Field{
						{Property: "Actions", Member: "Actions", Kind: "list"},
						{Property: "Conditions", Member: "Conditions", Kind: "list"},
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "Unless", Member: "Unless", Kind: "list"},
					},
				},
			},
		},
		"AWS::SES::MailManagerTrafficPolicy": {
			Type:        "AWS::SES::MailManagerTrafficPolicy",
			Protocol:    "awsJson1_0",
			SigningName: "ses",
			Host:        "mail-manager.{region}.amazonaws.com",
			Target:      "MailManagerSvc.GetTrafficPolicy",
			Identifier: []Binding{
				{Property: "TrafficPolicyId", Member: "TrafficPolicyId", Location: "body"},
			},
			Fields: []Field{
				{Property: "DefaultAction", Member: "DefaultAction", Kind: "scalar"},
				{Property: "MaxMessageSizeBytes", Member: "MaxMessageSizeBytes", Kind: "scalar"},
				{Property: "PolicyStatements", Member: "PolicyStatements", Kind: "list",
					Fields: []Field{
						{Property: "Action", Member: "Action", Kind: "scalar"},
						{Property: "Conditions", Member: "Conditions", Kind: "list"},
					},
				},
				{Property: "TrafficPolicyArn", Member: "TrafficPolicyArn", Kind: "scalar"},
				{Property: "TrafficPolicyId", Member: "TrafficPolicyId", Kind: "scalar"},
				{Property: "TrafficPolicyName", Member: "TrafficPolicyName", Kind: "scalar"},
			},
		},
	})
}
