// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ElementalInference::Dictionary": {
			Type:        "AWS::ElementalInference::Dictionary",
			Protocol:    "restJson1",
			SigningName: "elemental-inference",
			Complete:    true,
			Host:        "elemental-inference.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/dictionary/{id}",
			Identifier: []Binding{
				{Property: "Id", Member: "id", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "Language", Member: "language", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Tags", Member: "tags", Kind: "map"},
			},
		},
	})
}
