// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MediaConvert::Queue": {
			Type:        "AWS::MediaConvert::Queue",
			Protocol:    "restJson1",
			SigningName: "mediaconvert",
			Host:        "mediaconvert.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/2017-08-29/queues/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Response: []Step{{Name: "queue"}},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", JSONName: "arn"},
				{Property: "ConcurrentJobs", Member: "ConcurrentJobs", Kind: "scalar", JSONName: "concurrentJobs"},
				{Property: "Description", Member: "Description", Kind: "scalar", JSONName: "description"},
				{Property: "MaximumConcurrentFeeds", Member: "MaximumConcurrentFeeds", Kind: "scalar", JSONName: "maximumConcurrentFeeds"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "PricingPlan", Member: "PricingPlan", Kind: "scalar", JSONName: "pricingPlan"},
				{Property: "Status", Member: "Status", Kind: "scalar", JSONName: "status"},
			},
		},
	})
}
