// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CloudFront::CachePolicy": {
			Type:          "AWS::CloudFront::CachePolicy",
			Protocol:      "restXml",
			SigningName:   "cloudfront",
			Complete:      true,
			Host:          "cloudfront.amazonaws.com",
			SigningRegion: "us-east-1",
			Method:        "GET",
			URI:           "/2020-05-31/cache-policy/{Id}",
			Identifier: []Binding{
				{Property: "Id", Member: "Id", Location: "label"},
			},
			Fields: []Field{
				{Property: "CachePolicyConfig", Member: "CachePolicyConfig", Kind: "structure", XMLName: "CachePolicyConfig",
					Fields: []Field{
						{Property: "Comment", Member: "Comment", Kind: "scalar", XMLName: "Comment", Scalar: "string"},
						{Property: "DefaultTTL", Member: "DefaultTTL", Kind: "scalar", XMLName: "DefaultTTL", Scalar: "number"},
						{Property: "MaxTTL", Member: "MaxTTL", Kind: "scalar", XMLName: "MaxTTL", Scalar: "number"},
						{Property: "MinTTL", Member: "MinTTL", Kind: "scalar", XMLName: "MinTTL", Scalar: "number"},
						{Property: "Name", Member: "Name", Kind: "scalar", XMLName: "Name", Scalar: "string"},
						{Property: "ParametersInCacheKeyAndForwardedToOrigin", Member: "ParametersInCacheKeyAndForwardedToOrigin", Kind: "structure", XMLName: "ParametersInCacheKeyAndForwardedToOrigin",
							Fields: []Field{
								{Property: "CookiesConfig", Member: "CookiesConfig", Kind: "structure", XMLName: "CookiesConfig",
									Fields: []Field{
										{Property: "CookieBehavior", Member: "CookieBehavior", Kind: "scalar", XMLName: "CookieBehavior", Scalar: "string"},
										{Property: "Cookies", Member: "Items", Kind: "list", Via: []Step{{Name: "Cookies"}}, XMLName: "Items", Item: "Name", Scalar: "string"},
									},
								},
								{Property: "EnableAcceptEncodingBrotli", Member: "EnableAcceptEncodingBrotli", Kind: "scalar", XMLName: "EnableAcceptEncodingBrotli", Scalar: "boolean"},
								{Property: "EnableAcceptEncodingGzip", Member: "EnableAcceptEncodingGzip", Kind: "scalar", XMLName: "EnableAcceptEncodingGzip", Scalar: "boolean"},
								{Property: "HeadersConfig", Member: "HeadersConfig", Kind: "structure", XMLName: "HeadersConfig",
									Fields: []Field{
										{Property: "HeaderBehavior", Member: "HeaderBehavior", Kind: "scalar", XMLName: "HeaderBehavior", Scalar: "string"},
										{Property: "Headers", Member: "Items", Kind: "list", Via: []Step{{Name: "Headers"}}, XMLName: "Items", Item: "Name", Scalar: "string"},
									},
								},
								{Property: "QueryStringsConfig", Member: "QueryStringsConfig", Kind: "structure", XMLName: "QueryStringsConfig",
									Fields: []Field{
										{Property: "QueryStringBehavior", Member: "QueryStringBehavior", Kind: "scalar", XMLName: "QueryStringBehavior", Scalar: "string"},
										{Property: "QueryStrings", Member: "Items", Kind: "list", Via: []Step{{Name: "QueryStrings"}}, XMLName: "Items", Item: "Name", Scalar: "string"},
									},
								},
							},
						},
					},
				},
				{Property: "Id", Member: "Id", Kind: "scalar", XMLName: "Id", Scalar: "string"},
				{Property: "LastModifiedTime", Member: "LastModifiedTime", Kind: "timestamp", XMLName: "LastModifiedTime", Scalar: "timestamp"},
			},
		},
	})
}
