// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CloudWatch::Alarm": {
			Type:        "AWS::CloudWatch::Alarm",
			Protocol:    "awsJson1_0",
			SigningName: "monitoring",
			Complete:    true,
			Production:  true,
			Host:        "monitoring.{region}.amazonaws.com",
			Target:      "GraniteServiceVersion20100801.DescribeAlarms",
			Identifier: []Binding{
				{Property: "AlarmName", Member: "AlarmNames", Location: "body", List: true},
			},
			PageToken: []string{"NextToken"},
			Response:  []Step{{Name: "MetricAlarms", List: true}},
			Fields: []Field{
				{Property: "ActionsEnabled", Member: "ActionsEnabled", Kind: "scalar"},
				{Property: "AlarmActions", Member: "AlarmActions", Kind: "list"},
				{Property: "AlarmDescription", Member: "AlarmDescription", Kind: "scalar"},
				{Property: "AlarmName", Member: "AlarmName", Kind: "scalar"},
				{Property: "Arn", Member: "AlarmArn", Kind: "scalar"},
				{Property: "ComparisonOperator", Member: "ComparisonOperator", Kind: "scalar"},
				{Property: "DatapointsToAlarm", Member: "DatapointsToAlarm", Kind: "scalar"},
				{Property: "Dimensions", Member: "Dimensions", Kind: "list",
					Fields: []Field{
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "EvaluateLowSampleCountPercentile", Member: "EvaluateLowSampleCountPercentile", Kind: "scalar"},
				{Property: "EvaluationCriteria", Member: "EvaluationCriteria", Kind: "structure",
					Fields: []Field{
						{Property: "PromQLCriteria", Member: "PromQLCriteria", Kind: "structure",
							Fields: []Field{
								{Property: "PendingPeriod", Member: "PendingPeriod", Kind: "scalar"},
								{Property: "Query", Member: "Query", Kind: "scalar"},
								{Property: "RecoveryPeriod", Member: "RecoveryPeriod", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "EvaluationInterval", Member: "EvaluationInterval", Kind: "scalar"},
				{Property: "EvaluationPeriods", Member: "EvaluationPeriods", Kind: "scalar"},
				{Property: "EvaluationWindow", Member: "EvaluationWindow", Kind: "structure",
					Fields: []Field{
						{Property: "SlidingWindow", Member: "SlidingWindow", Kind: "scalar"},
						{Property: "WallClockWindow", Member: "WallClockWindow", Kind: "structure",
							Fields: []Field{
								{Property: "Timezone", Member: "Timezone", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ExtendedStatistic", Member: "ExtendedStatistic", Kind: "scalar"},
				{Property: "InsufficientDataActions", Member: "InsufficientDataActions", Kind: "list"},
				{Property: "MetricName", Member: "MetricName", Kind: "scalar"},
				{Property: "Metrics", Member: "Metrics", Kind: "list",
					Fields: []Field{
						{Property: "AccountId", Member: "AccountId", Kind: "scalar"},
						{Property: "Expression", Member: "Expression", Kind: "scalar"},
						{Property: "Id", Member: "Id", Kind: "scalar"},
						{Property: "Label", Member: "Label", Kind: "scalar"},
						{Property: "MetricStat", Member: "MetricStat", Kind: "structure",
							Fields: []Field{
								{Property: "Metric", Member: "Metric", Kind: "structure",
									Fields: []Field{
										{Property: "Dimensions", Member: "Dimensions", Kind: "list",
											Fields: []Field{
												{Property: "Name", Member: "Name", Kind: "scalar"},
												{Property: "Value", Member: "Value", Kind: "scalar"},
											},
										},
										{Property: "MetricName", Member: "MetricName", Kind: "scalar"},
										{Property: "Namespace", Member: "Namespace", Kind: "scalar"},
									},
								},
								{Property: "Period", Member: "Period", Kind: "scalar"},
								{Property: "Stat", Member: "Stat", Kind: "scalar"},
								{Property: "Unit", Member: "Unit", Kind: "scalar"},
							},
						},
						{Property: "Period", Member: "Period", Kind: "scalar"},
						{Property: "ReturnData", Member: "ReturnData", Kind: "scalar"},
					},
				},
				{Property: "Namespace", Member: "Namespace", Kind: "scalar"},
				{Property: "OKActions", Member: "OKActions", Kind: "list"},
				{Property: "Period", Member: "Period", Kind: "scalar"},
				{Property: "Statistic", Member: "Statistic", Kind: "scalar"},
				{Property: "Threshold", Member: "Threshold", Kind: "scalar"},
				{Property: "ThresholdMetricId", Member: "ThresholdMetricId", Kind: "scalar"},
				{Property: "TreatMissingData", Member: "TreatMissingData", Kind: "scalar"},
				{Property: "Unit", Member: "Unit", Kind: "scalar"},
				{Property: "WarmUpConfiguration", Member: "WarmUpConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "OnlyStartEvaluatingAfterWarmUpPeriodEnds", Member: "OnlyStartEvaluatingAfterWarmUpPeriodEnds", Kind: "scalar"},
						{Property: "WarmUpPeriodDurationInMinutes", Member: "WarmUpPeriodDurationInMinutes", Kind: "scalar"},
					},
				},
			},
			AbsentIDs: []string{"kraai-absent-probe-alarm"},
			Capture: []Field{
				{Property: "Arn", Member: "AlarmArn", Kind: "scalar"},
			},
			LifecycleComplete: true,
			MutationCaptures:  true,
			Create:            &MutationCall{Operation: "PutMetricAlarm", Target: "GraniteServiceVersion20100801.PutMetricAlarm", NameProperty: "AlarmName", NameTag: "kraai:resource-name", Input: map[string]any{"ActionsEnabled": "{ActionsEnabled}", "AlarmActions": "{AlarmActions}", "AlarmDescription": "{AlarmDescription}", "AlarmName": "{AlarmName}", "ComparisonOperator": "{ComparisonOperator}", "DatapointsToAlarm": "{DatapointsToAlarm}", "Dimensions": "{Dimensions:wire}", "EvaluateLowSampleCountPercentile": "{EvaluateLowSampleCountPercentile}", "EvaluationCriteria": "{EvaluationCriteria:wire}", "EvaluationInterval": "{EvaluationInterval}", "EvaluationPeriods": "{EvaluationPeriods}", "EvaluationWindow": "{EvaluationWindow:wire}", "ExtendedStatistic": "{ExtendedStatistic}", "InsufficientDataActions": "{InsufficientDataActions}", "MetricName": "{MetricName}", "Metrics": "{Metrics:wire}", "Namespace": "{Namespace}", "OKActions": "{OKActions}", "Period": "{Period}", "Statistic": "{Statistic}", "Tags": "{Tags}", "Threshold": "{Threshold}", "ThresholdMetricId": "{ThresholdMetricId}", "TreatMissingData": "{TreatMissingData}", "Unit": "{Unit}", "WarmUpConfiguration": "{WarmUpConfiguration:wire}"}, Properties: []string{"ActionsEnabled", "AlarmActions", "AlarmDescription", "AlarmName", "ComparisonOperator", "DatapointsToAlarm", "Dimensions", "EvaluateLowSampleCountPercentile", "EvaluationCriteria", "EvaluationInterval", "EvaluationPeriods", "EvaluationWindow", "ExtendedStatistic", "InsufficientDataActions", "MetricName", "Metrics", "Namespace", "OKActions", "Period", "Statistic", "Tags", "Threshold", "ThresholdMetricId", "TreatMissingData", "Unit", "WarmUpConfiguration"}, Identifier: map[string]string{"AlarmName": "{AlarmName}"}, Idempotent: true},
			Delete:            &MutationCall{Operation: "DeleteAlarms", Target: "GraniteServiceVersion20100801.DeleteAlarms", Input: map[string]any{"AlarmNames": []any{"{AlarmName}"}}, AbsentErrors: []string{"ResourceNotFound"}},
			Update: []MutationCall{
				MutationCall{Operation: "PutMetricAlarm", Target: "GraniteServiceVersion20100801.PutMetricAlarm", Input: map[string]any{"ActionsEnabled": "{ActionsEnabled}", "AlarmActions": "{AlarmActions}", "AlarmDescription": "{AlarmDescription}", "AlarmName": "{AlarmName}", "ComparisonOperator": "{ComparisonOperator}", "DatapointsToAlarm": "{DatapointsToAlarm}", "Dimensions": "{Dimensions:wire}", "EvaluateLowSampleCountPercentile": "{EvaluateLowSampleCountPercentile}", "EvaluationCriteria": "{EvaluationCriteria:wire}", "EvaluationInterval": "{EvaluationInterval}", "EvaluationPeriods": "{EvaluationPeriods}", "EvaluationWindow": "{EvaluationWindow:wire}", "ExtendedStatistic": "{ExtendedStatistic}", "InsufficientDataActions": "{InsufficientDataActions}", "MetricName": "{MetricName}", "Metrics": "{Metrics:wire}", "Namespace": "{Namespace}", "OKActions": "{OKActions}", "Period": "{Period}", "Statistic": "{Statistic}", "Threshold": "{Threshold}", "ThresholdMetricId": "{ThresholdMetricId}", "TreatMissingData": "{TreatMissingData}", "Unit": "{Unit}", "WarmUpConfiguration": "{WarmUpConfiguration:wire}"}, Properties: []string{"ActionsEnabled", "AlarmActions", "AlarmDescription", "ComparisonOperator", "DatapointsToAlarm", "Dimensions", "EvaluateLowSampleCountPercentile", "EvaluationCriteria", "EvaluationInterval", "EvaluationPeriods", "EvaluationWindow", "ExtendedStatistic", "InsufficientDataActions", "MetricName", "Metrics", "Namespace", "OKActions", "Period", "Statistic", "Threshold", "ThresholdMetricId", "TreatMissingData", "Unit", "WarmUpConfiguration"}, Together: true},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "TagResource", Target: "GraniteServiceVersion20100801.TagResource", TagProperty: "Tags", Input: map[string]any{"ResourceARN": "{Arn}", "Tags": "{added}"}}, Remove: &MutationCall{Operation: "UntagResource", Target: "GraniteServiceVersion20100801.UntagResource", Input: map[string]any{"ResourceARN": "{Arn}", "TagKeys": "{removed}"}}},
			},
			Also: []Reader{
				{
					Type:        "AWS::CloudWatch::Alarm",
					Protocol:    "awsJson1_0",
					SigningName: "monitoring",
					Host:        "monitoring.{region}.amazonaws.com",
					Target:      "GraniteServiceVersion20100801.ListTagsForResource",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceARN", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
			},
			Mutable: true,
		},
	})
}
