// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::BCM::ScheduledReport": {
			Type:          "AWS::BCM::ScheduledReport",
			Protocol:      "awsJson1_0",
			SigningName:   "bcm-dashboards",
			Host:          "bcm-dashboards.us-east-1.api.aws",
			SigningRegion: "us-east-1",
			Target:        "AWSBCMDashboardsService.GetScheduledReport",
			Identifier: []Binding{
				{Property: "Arn", Member: "arn", Location: "body"},
			},
			Response: []Step{{Name: "scheduledReport"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "DashboardArn", Member: "dashboardArn", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "HealthStatus", Member: "healthStatus", Kind: "structure",
					Fields: []Field{
						{Property: "LastRefreshedAt", Member: "lastRefreshedAt", Kind: "timestamp"},
						{Property: "StatusCode", Member: "statusCode", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "ScheduleConfig", Member: "scheduleConfig", Kind: "structure",
					Fields: []Field{
						{Property: "ScheduleExpression", Member: "scheduleExpression", Kind: "scalar"},
						{Property: "ScheduleExpressionTimeZone", Member: "scheduleExpressionTimeZone", Kind: "scalar"},
						{Property: "SchedulePeriod", Member: "schedulePeriod", Kind: "structure",
							Fields: []Field{
								{Property: "EndTime", Member: "endTime", Kind: "timestamp"},
								{Property: "StartTime", Member: "startTime", Kind: "timestamp"},
							},
						},
						{Property: "State", Member: "state", Kind: "scalar"},
					},
				},
				{Property: "ScheduledReportExecutionRoleArn", Member: "scheduledReportExecutionRoleArn", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
				{Property: "WidgetDateRangeOverride", Member: "widgetDateRangeOverride", Kind: "structure",
					Fields: []Field{
						{Property: "EndTime", Member: "endTime", Kind: "structure",
							Fields: []Field{
								{Property: "Type", Member: "type", Kind: "scalar"},
								{Property: "Value", Member: "value", Kind: "scalar"},
							},
						},
						{Property: "StartTime", Member: "startTime", Kind: "structure",
							Fields: []Field{
								{Property: "Type", Member: "type", Kind: "scalar"},
								{Property: "Value", Member: "value", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "WidgetIds", Member: "widgetIds", Kind: "list"},
			},
		},
	})
}
