// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SecretsManager::Secret": {
			Type:        "AWS::SecretsManager::Secret",
			Protocol:    "awsJson1_1",
			SigningName: "secretsmanager",
			Complete:    true,
			Production:  true,
			Host:        "secretsmanager.{region}.amazonaws.com",
			Target:      "secretsmanager.DescribeSecret",
			Identifier: []Binding{
				{Property: "Id", Member: "SecretId", Location: "body"},
			},
			AbsentErrors: []string{"ResourceNotFoundException"},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Id", Member: "ARN", Kind: "scalar"},
				{Property: "KmsKeyId", Member: "KmsKeyId", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ReplicaRegions", Member: "ReplicationStatus", Kind: "list",
					Fields: []Field{
						{Property: "KmsKeyId", Member: "KmsKeyId", Kind: "scalar"},
						{Property: "Region", Member: "Region", Kind: "scalar"},
					},
				},
				{Property: "Tags", Member: "Tags", Kind: "list",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "Type", Member: "Type", Kind: "scalar"},
			},
			AbsentIDs:         []string{"arn:aws:secretsmanager:{region}:{account}:secret:kraai-absent-probe-AbCdEf"},
			Unsupported:       map[string]string{"GenerateSecretString": "the password is made by GetRandomPassword and merged into the template client side, which no direct call does", "Type": "a managed external secret needs a partner account"},
			WriteOnly:         []string{"GenerateSecretString", "SecretString"},
			LifecycleComplete: true,
			Create:            &MutationCall{Operation: "CreateSecret", Target: "secretsmanager.CreateSecret", NameProperty: "Name", NameTag: "kraai:resource-name", TokenMember: "ClientRequestToken", Input: map[string]any{"AddReplicaRegions": "{ReplicaRegions:wire}", "Description": "{Description}", "KmsKeyId": "{KmsKeyId}", "Name": "{Name}", "SecretString": "{SecretString}", "Tags": "{Tags}"}, Properties: []string{"Description", "KmsKeyId", "Name", "ReplicaRegions", "SecretString", "Tags"}, Identifier: map[string]string{"Id": "ARN"}},
			Delete:            &MutationCall{Operation: "DeleteSecret", Target: "secretsmanager.DeleteSecret", Input: map[string]any{"ForceDeleteWithoutRecovery": true, "SecretId": "{Id}"}, AbsentErrors: []string{"ResourceNotFoundException"}, Clear: []string{"ReplicaRegions"}},
			Update: []MutationCall{
				MutationCall{Operation: "UpdateSecret", Target: "secretsmanager.UpdateSecret", TokenMember: "ClientRequestToken", Input: map[string]any{"Description": "{Description}", "KmsKeyId": "{KmsKeyId}", "SecretId": "{Id}", "SecretString": "{SecretString}"}, Properties: []string{"Description", "KmsKeyId", "SecretString"}},
				MutationCall{ListProperty: "ReplicaRegions", Key: []string{"Region"}, Add: &MutationCall{Operation: "ReplicateSecretToRegions", Target: "secretsmanager.ReplicateSecretToRegions", TagProperty: "ReplicaRegions", Input: map[string]any{"AddReplicaRegions": "{added:wire}", "SecretId": "{Id}"}}, Remove: &MutationCall{Operation: "RemoveRegionsFromReplication", Target: "secretsmanager.RemoveRegionsFromReplication", TagProperty: "ReplicaRegions", Input: map[string]any{"RemoveReplicaRegions": "{removedKeys}", "SecretId": "{Id}"}}},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "TagResource", Target: "secretsmanager.TagResource", TagProperty: "Tags", Input: map[string]any{"SecretId": "{Id}", "Tags": "{added}"}}, Remove: &MutationCall{Operation: "UntagResource", Target: "secretsmanager.UntagResource", Input: map[string]any{"SecretId": "{Id}", "TagKeys": "{removed}"}}},
			},
			Mutable: true,
		},
	})
}
