// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CloudFormation::ChangeSet": {
			Type:        "AWS::CloudFormation::ChangeSet",
			Protocol:    "awsQuery",
			SigningName: "cloudformation",
			Complete:    true,
			Host:        "cloudformation.{region}.amazonaws.com",
			Action:      "DescribeChangeSet",
			Version:     "2010-05-15",
			Wrapper:     "DescribeChangeSetResult",
			Identifier: []Binding{
				{Property: "ChangeSetId", Member: "ChangeSetName", Location: "form", Name: "ChangeSetName"},
			},
			PageToken: []string{"NextToken"},
			Fields: []Field{
				{Property: "Capabilities", Member: "Capabilities", Kind: "list", XMLName: "Capabilities", Item: "member", Scalar: "string"},
				{Property: "ChangeSetId", Member: "ChangeSetId", Kind: "scalar", XMLName: "ChangeSetId", Scalar: "string"},
				{Property: "ChangeSetName", Member: "ChangeSetName", Kind: "scalar", XMLName: "ChangeSetName", Scalar: "string"},
				{Property: "CreationTime", Member: "CreationTime", Kind: "timestamp", XMLName: "CreationTime", Scalar: "timestamp"},
				{Property: "DeploymentMode", Member: "DeploymentMode", Kind: "scalar", XMLName: "DeploymentMode", Scalar: "string"},
				{Property: "Description", Member: "Description", Kind: "scalar", XMLName: "Description", Scalar: "string"},
				{Property: "ImportExistingResources", Member: "ImportExistingResources", Kind: "scalar", XMLName: "ImportExistingResources", Scalar: "boolean"},
				{Property: "IncludeNestedStacks", Member: "IncludeNestedStacks", Kind: "scalar", XMLName: "IncludeNestedStacks", Scalar: "boolean"},
				{Property: "NotificationARNs", Member: "NotificationARNs", Kind: "list", XMLName: "NotificationARNs", Item: "member", Scalar: "string"},
				{Property: "OnStackFailure", Member: "OnStackFailure", Kind: "scalar", XMLName: "OnStackFailure", Scalar: "string"},
				{Property: "StackId", Member: "StackId", Kind: "scalar", XMLName: "StackId", Scalar: "string"},
				{Property: "StackName", Member: "StackName", Kind: "scalar", XMLName: "StackName", Scalar: "string"},
				{Property: "Tags", Member: "Tags", Kind: "list", XMLName: "Tags", Item: "member",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
						{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
					},
				},
			},
		},
		"AWS::CloudFormation::GeneratedTemplate": {
			Type:        "AWS::CloudFormation::GeneratedTemplate",
			Protocol:    "awsQuery",
			SigningName: "cloudformation",
			Complete:    true,
			Host:        "cloudformation.{region}.amazonaws.com",
			Action:      "DescribeGeneratedTemplate",
			Version:     "2010-05-15",
			Wrapper:     "DescribeGeneratedTemplateResult",
			Identifier: []Binding{
				{Property: "GeneratedTemplateId", Member: "GeneratedTemplateName", Location: "form", Name: "GeneratedTemplateName"},
			},
			Fields: []Field{
				{Property: "CreationTime", Member: "CreationTime", Kind: "timestamp", XMLName: "CreationTime", Scalar: "timestamp"},
				{Property: "GeneratedTemplateId", Member: "GeneratedTemplateId", Kind: "scalar", XMLName: "GeneratedTemplateId", Scalar: "string"},
				{Property: "GeneratedTemplateName", Member: "GeneratedTemplateName", Kind: "scalar", XMLName: "GeneratedTemplateName", Scalar: "string"},
				{Property: "LastUpdatedTime", Member: "LastUpdatedTime", Kind: "timestamp", XMLName: "LastUpdatedTime", Scalar: "timestamp"},
				{Property: "Progress", Member: "Progress", Kind: "structure", XMLName: "Progress",
					Fields: []Field{
						{Property: "ResourcesFailed", Member: "ResourcesFailed", Kind: "scalar", XMLName: "ResourcesFailed", Scalar: "number"},
						{Property: "ResourcesPending", Member: "ResourcesPending", Kind: "scalar", XMLName: "ResourcesPending", Scalar: "number"},
						{Property: "ResourcesProcessing", Member: "ResourcesProcessing", Kind: "scalar", XMLName: "ResourcesProcessing", Scalar: "number"},
						{Property: "ResourcesSucceeded", Member: "ResourcesSucceeded", Kind: "scalar", XMLName: "ResourcesSucceeded", Scalar: "number"},
					},
				},
				{Property: "Status", Member: "Status", Kind: "scalar", XMLName: "Status", Scalar: "string"},
				{Property: "TemplateConfiguration", Member: "TemplateConfiguration", Kind: "structure", XMLName: "TemplateConfiguration",
					Fields: []Field{
						{Property: "DeletionPolicy", Member: "DeletionPolicy", Kind: "scalar", XMLName: "DeletionPolicy", Scalar: "string"},
						{Property: "UpdateReplacePolicy", Member: "UpdateReplacePolicy", Kind: "scalar", XMLName: "UpdateReplacePolicy", Scalar: "string"},
					},
				},
				{Property: "TotalWarnings", Member: "TotalWarnings", Kind: "scalar", XMLName: "TotalWarnings", Scalar: "number"},
			},
		},
		"AWS::CloudFormation::ModuleDefaultVersion": {
			Type:        "AWS::CloudFormation::ModuleDefaultVersion",
			Protocol:    "awsQuery",
			SigningName: "cloudformation",
			Complete:    true,
			Host:        "cloudformation.{region}.amazonaws.com",
			Action:      "DescribeType",
			Version:     "2010-05-15",
			Wrapper:     "DescribeTypeResult",
			Identifier: []Binding{
				{Property: "Arn", Member: "Arn", Location: "form", Name: "Arn"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar", XMLName: "Arn", Scalar: "string"},
			},
		},
	})
}
