// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::BedrockAgentCore::ApiKeyCredentialProvider": {
			Type:        "AWS::BedrockAgentCore::ApiKeyCredentialProvider",
			Protocol:    "restJson1",
			SigningName: "bedrock-agentcore",
			Host:        "bedrock-agentcore-control.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/identities/GetApiKeyCredentialProvider",
			Identifier: []Binding{
				{Property: "CredentialProviderArn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "name", Value: "{CredentialProviderArn:arnName}"},
			},
			Fields: []Field{
				{Property: "ApiKeySecretArn", Member: "apiKeySecretArn", Kind: "structure",
					Fields: []Field{
						{Property: "SecretArn", Member: "secretArn", Kind: "scalar"},
					},
				},
				{Property: "ApiKeySecretJsonKey", Member: "apiKeySecretJsonKey", Kind: "scalar"},
				{Property: "CreatedTime", Member: "createdTime", Kind: "timestamp"},
				{Property: "CredentialProviderArn", Member: "credentialProviderArn", Kind: "scalar"},
				{Property: "LastUpdatedTime", Member: "lastUpdatedTime", Kind: "timestamp"},
				{Property: "Name", Member: "name", Kind: "scalar"},
			},
		},
		"AWS::BedrockAgentCore::BrowserProfile": {
			Type:        "AWS::BedrockAgentCore::BrowserProfile",
			Protocol:    "restJson1",
			SigningName: "bedrock-agentcore",
			Host:        "bedrock-agentcore-control.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/browser-profiles/{profileId}",
			Identifier: []Binding{
				{Property: "ProfileId", Member: "profileId", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "LastSavedAt", Member: "lastSavedAt", Kind: "timestamp"},
				{Property: "LastSavedBrowserId", Member: "lastSavedBrowserId", Kind: "scalar"},
				{Property: "LastSavedBrowserSessionId", Member: "lastSavedBrowserSessionId", Kind: "scalar"},
				{Property: "LastUpdatedAt", Member: "lastUpdatedAt", Kind: "timestamp"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "ProfileArn", Member: "profileArn", Kind: "scalar"},
				{Property: "ProfileId", Member: "profileId", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
		"AWS::BedrockAgentCore::PolicyEngine": {
			Type:        "AWS::BedrockAgentCore::PolicyEngine",
			Protocol:    "restJson1",
			SigningName: "bedrock-agentcore",
			Host:        "bedrock-agentcore-control.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/policy-engines/{policyEngineId}",
			Identifier: []Binding{
				{Property: "PolicyEngineArn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "policyEngineId", Value: "{PolicyEngineArn:arnName}"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "EncryptionKeyArn", Member: "encryptionKeyArn", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "PolicyEngineArn", Member: "policyEngineArn", Kind: "scalar"},
				{Property: "PolicyEngineId", Member: "policyEngineId", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "StatusReasons", Member: "statusReasons", Kind: "list"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
