// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IoTFleetWise::Fleet": {
			Type:        "AWS::IoTFleetWise::Fleet",
			Protocol:    "awsJson1_0",
			SigningName: "iotfleetwise",
			Host:        "iotfleetwise.{region}.amazonaws.com",
			Target:      "IoTAutobahnControlPlane.GetFleet",
			Identifier: []Binding{
				{Property: "Id", Member: "fleetId", Location: "body"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreationTime", Member: "creationTime", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "LastModificationTime", Member: "lastModificationTime", Kind: "timestamp"},
				{Property: "SignalCatalogArn", Member: "signalCatalogArn", Kind: "scalar"},
			},
		},
		"AWS::IoTFleetWise::StateTemplate": {
			Type:        "AWS::IoTFleetWise::StateTemplate",
			Protocol:    "awsJson1_0",
			SigningName: "iotfleetwise",
			Host:        "iotfleetwise.{region}.amazonaws.com",
			Target:      "IoTAutobahnControlPlane.GetStateTemplate",
			Identifier: []Binding{
				{Property: "Name", Member: "identifier", Location: "body"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreationTime", Member: "creationTime", Kind: "timestamp"},
				{Property: "DataExtraDimensions", Member: "dataExtraDimensions", Kind: "list"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "LastModificationTime", Member: "lastModificationTime", Kind: "timestamp"},
				{Property: "MetadataExtraDimensions", Member: "metadataExtraDimensions", Kind: "list"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "SignalCatalogArn", Member: "signalCatalogArn", Kind: "scalar"},
				{Property: "StateTemplateProperties", Member: "stateTemplateProperties", Kind: "list"},
			},
		},
	})
}
