// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Forecast::DatasetGroup": {
			Type:        "AWS::Forecast::DatasetGroup",
			Protocol:    "awsJson1_1",
			SigningName: "forecast",
			Host:        "forecast.{region}.amazonaws.com",
			Target:      "AmazonForecast.DescribeDatasetGroup",
			Identifier: []Binding{
				{Property: "DatasetGroupArn", Member: "DatasetGroupArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "DatasetArns", Member: "DatasetArns", Kind: "list"},
				{Property: "DatasetGroupArn", Member: "DatasetGroupArn", Kind: "scalar"},
				{Property: "DatasetGroupName", Member: "DatasetGroupName", Kind: "scalar"},
				{Property: "Domain", Member: "Domain", Kind: "scalar"},
			},
		},
	})
}
