// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::EntityResolution::IdNamespace": {
			Type:        "AWS::EntityResolution::IdNamespace",
			Protocol:    "restJson1",
			SigningName: "entityresolution",
			Host:        "entityresolution.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/idnamespaces/{idNamespaceName}",
			Identifier: []Binding{
				{Property: "IdNamespaceName", Member: "idNamespaceName", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "IdMappingWorkflowProperties", Member: "idMappingWorkflowProperties", Kind: "list",
					Fields: []Field{
						{Property: "IdMappingType", Member: "idMappingType", Kind: "scalar"},
						{Property: "ProviderProperties", Member: "providerProperties", Kind: "structure",
							Fields: []Field{
								{Property: "ProviderConfiguration", Member: "providerConfiguration", Kind: "scalar"},
								{Property: "ProviderServiceArn", Member: "providerServiceArn", Kind: "scalar"},
							},
						},
						{Property: "RuleBasedProperties", Member: "ruleBasedProperties", Kind: "structure",
							Fields: []Field{
								{Property: "AttributeMatchingModel", Member: "attributeMatchingModel", Kind: "scalar"},
								{Property: "RecordMatchingModels", Member: "recordMatchingModels", Kind: "list"},
								{Property: "RuleDefinitionTypes", Member: "ruleDefinitionTypes", Kind: "list"},
								{Property: "Rules", Member: "rules", Kind: "list",
									Fields: []Field{
										{Property: "MatchingKeys", Member: "matchingKeys", Kind: "list"},
										{Property: "RuleName", Member: "ruleName", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{Property: "IdNamespaceArn", Member: "idNamespaceArn", Kind: "scalar"},
				{Property: "IdNamespaceName", Member: "idNamespaceName", Kind: "scalar"},
				{Property: "InputSourceConfig", Member: "inputSourceConfig", Kind: "list",
					Fields: []Field{
						{Property: "InputSourceARN", Member: "inputSourceARN", Kind: "scalar"},
						{Property: "SchemaName", Member: "schemaName", Kind: "scalar"},
					},
				},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "Type", Member: "type", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
		"AWS::EntityResolution::SchemaMapping": {
			Type:        "AWS::EntityResolution::SchemaMapping",
			Protocol:    "restJson1",
			SigningName: "entityresolution",
			Host:        "entityresolution.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/schemas/{schemaName}",
			Identifier: []Binding{
				{Property: "SchemaName", Member: "schemaName", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "HasWorkflows", Member: "hasWorkflows", Kind: "scalar"},
				{Property: "MappedInputFields", Member: "mappedInputFields", Kind: "list",
					Fields: []Field{
						{Property: "FieldName", Member: "fieldName", Kind: "scalar"},
						{Property: "GroupName", Member: "groupName", Kind: "scalar"},
						{Property: "Hashed", Member: "hashed", Kind: "scalar"},
						{Property: "MatchKey", Member: "matchKey", Kind: "scalar"},
						{Property: "SubType", Member: "subType", Kind: "scalar"},
						{Property: "Type", Member: "type", Kind: "scalar"},
					},
				},
				{Property: "SchemaArn", Member: "schemaArn", Kind: "scalar"},
				{Property: "SchemaName", Member: "schemaName", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
