// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Personalize::DatasetGroup": {
			Type:        "AWS::Personalize::DatasetGroup",
			Protocol:    "awsJson1_1",
			SigningName: "personalize",
			Host:        "personalize.{region}.amazonaws.com",
			Target:      "AmazonPersonalize.DescribeDatasetGroup",
			Identifier: []Binding{
				{Property: "DatasetGroupArn", Member: "datasetGroupArn", Location: "body"},
			},
			Response: []Step{{Name: "datasetGroup"}},
			Fields: []Field{
				{Property: "DatasetGroupArn", Member: "datasetGroupArn", Kind: "scalar"},
				{Property: "Domain", Member: "domain", Kind: "scalar"},
				{Property: "KmsKeyArn", Member: "kmsKeyArn", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
			},
		},
		"AWS::Personalize::EventTracker": {
			Type:        "AWS::Personalize::EventTracker",
			Protocol:    "awsJson1_1",
			SigningName: "personalize",
			Host:        "personalize.{region}.amazonaws.com",
			Target:      "AmazonPersonalize.DescribeEventTracker",
			Identifier: []Binding{
				{Property: "EventTrackerArn", Member: "eventTrackerArn", Location: "body"},
			},
			Response: []Step{{Name: "eventTracker"}},
			Fields: []Field{
				{Property: "DatasetGroupArn", Member: "datasetGroupArn", Kind: "scalar"},
				{Property: "EventTrackerArn", Member: "eventTrackerArn", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "TrackingId", Member: "trackingId", Kind: "scalar"},
			},
		},
		"AWS::Personalize::Filter": {
			Type:        "AWS::Personalize::Filter",
			Protocol:    "awsJson1_1",
			SigningName: "personalize",
			Host:        "personalize.{region}.amazonaws.com",
			Target:      "AmazonPersonalize.DescribeFilter",
			Identifier: []Binding{
				{Property: "FilterArn", Member: "filterArn", Location: "body"},
			},
			Response: []Step{{Name: "filter"}},
			Fields: []Field{
				{Property: "CreationDateTime", Member: "creationDateTime", Kind: "timestamp"},
				{Property: "DatasetGroupArn", Member: "datasetGroupArn", Kind: "scalar"},
				{Property: "FilterArn", Member: "filterArn", Kind: "scalar"},
				{Property: "FilterExpression", Member: "filterExpression", Kind: "scalar"},
				{Property: "LastUpdatedDateTime", Member: "lastUpdatedDateTime", Kind: "timestamp"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
		"AWS::Personalize::Schema": {
			Type:        "AWS::Personalize::Schema",
			Protocol:    "awsJson1_1",
			SigningName: "personalize",
			Host:        "personalize.{region}.amazonaws.com",
			Target:      "AmazonPersonalize.DescribeSchema",
			Identifier: []Binding{
				{Property: "SchemaArn", Member: "schemaArn", Location: "body"},
			},
			Response: []Step{{Name: "schema"}},
			Fields: []Field{
				{Property: "Domain", Member: "domain", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Schema", Member: "schema", Kind: "scalar"},
				{Property: "SchemaArn", Member: "schemaArn", Kind: "scalar"},
			},
		},
		"AWS::Personalize::Solution": {
			Type:        "AWS::Personalize::Solution",
			Protocol:    "awsJson1_1",
			SigningName: "personalize",
			Host:        "personalize.{region}.amazonaws.com",
			Target:      "AmazonPersonalize.DescribeSolution",
			Identifier: []Binding{
				{Property: "SolutionArn", Member: "solutionArn", Location: "body"},
			},
			Response: []Step{{Name: "solution"}},
			Fields: []Field{
				{Property: "DatasetGroupArn", Member: "datasetGroupArn", Kind: "scalar"},
				{Property: "EventType", Member: "eventType", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "PerformAutoML", Member: "performAutoML", Kind: "scalar"},
				{Property: "PerformHPO", Member: "performHPO", Kind: "scalar"},
				{Property: "RecipeArn", Member: "recipeArn", Kind: "scalar"},
				{Property: "SolutionArn", Member: "solutionArn", Kind: "scalar"},
				{Property: "SolutionConfig", Member: "solutionConfig", Kind: "structure",
					Fields: []Field{
						{Property: "AlgorithmHyperParameters", Member: "algorithmHyperParameters", Kind: "map"},
						{Property: "AutoMLConfig", Member: "autoMLConfig", Kind: "structure",
							Fields: []Field{
								{Property: "MetricName", Member: "metricName", Kind: "scalar"},
								{Property: "RecipeList", Member: "recipeList", Kind: "list"},
							},
						},
						{Property: "EventValueThreshold", Member: "eventValueThreshold", Kind: "scalar"},
						{Property: "FeatureTransformationParameters", Member: "featureTransformationParameters", Kind: "map"},
						{Property: "HpoConfig", Member: "hpoConfig", Kind: "structure",
							Fields: []Field{
								{Property: "AlgorithmHyperParameterRanges", Member: "algorithmHyperParameterRanges", Kind: "structure",
									Fields: []Field{
										{Property: "CategoricalHyperParameterRanges", Member: "categoricalHyperParameterRanges", Kind: "list",
											Fields: []Field{
												{Property: "Name", Member: "name", Kind: "scalar"},
												{Property: "Values", Member: "values", Kind: "list"},
											},
										},
										{Property: "ContinuousHyperParameterRanges", Member: "continuousHyperParameterRanges", Kind: "list",
											Fields: []Field{
												{Property: "MaxValue", Member: "maxValue", Kind: "scalar"},
												{Property: "MinValue", Member: "minValue", Kind: "scalar"},
												{Property: "Name", Member: "name", Kind: "scalar"},
											},
										},
										{Property: "IntegerHyperParameterRanges", Member: "integerHyperParameterRanges", Kind: "list",
											Fields: []Field{
												{Property: "MaxValue", Member: "maxValue", Kind: "scalar"},
												{Property: "MinValue", Member: "minValue", Kind: "scalar"},
												{Property: "Name", Member: "name", Kind: "scalar"},
											},
										},
									},
								},
								{Property: "HpoObjective", Member: "hpoObjective", Kind: "structure",
									Fields: []Field{
										{Property: "MetricName", Member: "metricName", Kind: "scalar"},
										{Property: "MetricRegex", Member: "metricRegex", Kind: "scalar"},
										{Property: "Type", Member: "type", Kind: "scalar"},
									},
								},
								{Property: "HpoResourceConfig", Member: "hpoResourceConfig", Kind: "structure",
									Fields: []Field{
										{Property: "MaxNumberOfTrainingJobs", Member: "maxNumberOfTrainingJobs", Kind: "scalar"},
										{Property: "MaxParallelTrainingJobs", Member: "maxParallelTrainingJobs", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
			},
		},
	})
}
