// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Macie::CustomDataIdentifier": {
			Type:        "AWS::Macie::CustomDataIdentifier",
			Protocol:    "restJson1",
			SigningName: "macie2",
			Host:        "macie2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/custom-data-identifiers/{id}",
			Identifier: []Binding{
				{Property: "Id", Member: "id", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar", JSONName: "arn"},
				{Property: "Description", Member: "description", Kind: "scalar", JSONName: "description"},
				{Property: "Id", Member: "id", Kind: "scalar", JSONName: "id"},
				{Property: "IgnoreWords", Member: "ignoreWords", Kind: "list", JSONName: "ignoreWords"},
				{Property: "Keywords", Member: "keywords", Kind: "list", JSONName: "keywords"},
				{Property: "MaximumMatchDistance", Member: "maximumMatchDistance", Kind: "scalar", JSONName: "maximumMatchDistance"},
				{Property: "Name", Member: "name", Kind: "scalar", JSONName: "name"},
				{Property: "Regex", Member: "regex", Kind: "scalar", JSONName: "regex"},
			},
		},
		"AWS::Macie::FindingsFilter": {
			Type:        "AWS::Macie::FindingsFilter",
			Protocol:    "restJson1",
			SigningName: "macie2",
			Host:        "macie2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/findingsfilters/{id}",
			Identifier: []Binding{
				{Property: "Id", Member: "id", Location: "label"},
			},
			Fields: []Field{
				{Property: "Action", Member: "action", Kind: "scalar", JSONName: "action"},
				{Property: "Arn", Member: "arn", Kind: "scalar", JSONName: "arn"},
				{Property: "Description", Member: "description", Kind: "scalar", JSONName: "description"},
				{Property: "FindingCriteria", Member: "findingCriteria", Kind: "structure", JSONName: "findingCriteria",
					Fields: []Field{
						{Property: "Criterion", Member: "criterion", Kind: "map", JSONName: "criterion"},
					},
				},
				{Property: "Id", Member: "id", Kind: "scalar", JSONName: "id"},
				{Property: "Name", Member: "name", Kind: "scalar", JSONName: "name"},
				{Property: "Position", Member: "position", Kind: "scalar", JSONName: "position"},
			},
		},
		"AWS::Macie::Member": {
			Type:        "AWS::Macie::Member",
			Protocol:    "restJson1",
			SigningName: "macie2",
			Host:        "macie2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/members/{id}",
			Identifier: []Binding{
				{Property: "Arn", Member: "id", Location: "label"},
			},
			Fields: []Field{
				{Property: "AccountId", Member: "accountId", Kind: "scalar", JSONName: "accountId"},
				{Property: "AdministratorAccountId", Member: "administratorAccountId", Kind: "scalar", JSONName: "administratorAccountId"},
				{Property: "Arn", Member: "arn", Kind: "scalar", JSONName: "arn"},
				{Property: "RelationshipStatus", Member: "relationshipStatus", Kind: "scalar", JSONName: "relationshipStatus"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp", JSONName: "updatedAt"},
			},
		},
	})
}
