// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ElasticLoadBalancingV2::TargetGroup": {
			Type:        "AWS::ElasticLoadBalancingV2::TargetGroup",
			Protocol:    "awsQuery",
			SigningName: "elasticloadbalancing",
			Complete:    true,
			Production:  true,
			Host:        "elasticloadbalancing.{region}.amazonaws.com",
			Action:      "DescribeTargetGroups",
			Version:     "2015-12-01",
			Wrapper:     "DescribeTargetGroupsResult",
			Identifier: []Binding{
				{Property: "TargetGroupArn", Member: "TargetGroupArns", Location: "form", Name: "TargetGroupArns.member.1", List: true},
			},
			AbsentErrors: []string{"TargetGroupNotFound"},
			PageToken:    []string{"NextMarker"},
			Response:     []Step{{Name: "TargetGroups", List: true, Item: "member"}},
			Fields: []Field{
				{Property: "HealthCheckEnabled", Member: "HealthCheckEnabled", Kind: "scalar", XMLName: "HealthCheckEnabled", Scalar: "boolean"},
				{Property: "HealthCheckIntervalSeconds", Member: "HealthCheckIntervalSeconds", Kind: "scalar", XMLName: "HealthCheckIntervalSeconds", Scalar: "number"},
				{Property: "HealthCheckPath", Member: "HealthCheckPath", Kind: "scalar", XMLName: "HealthCheckPath", Scalar: "string"},
				{Property: "HealthCheckPort", Member: "HealthCheckPort", Kind: "scalar", XMLName: "HealthCheckPort", Scalar: "string"},
				{Property: "HealthCheckProtocol", Member: "HealthCheckProtocol", Kind: "scalar", XMLName: "HealthCheckProtocol", Scalar: "string"},
				{Property: "HealthCheckTimeoutSeconds", Member: "HealthCheckTimeoutSeconds", Kind: "scalar", XMLName: "HealthCheckTimeoutSeconds", Scalar: "number"},
				{Property: "HealthyThresholdCount", Member: "HealthyThresholdCount", Kind: "scalar", XMLName: "HealthyThresholdCount", Scalar: "number"},
				{Property: "IpAddressType", Member: "IpAddressType", Kind: "scalar", XMLName: "IpAddressType", Scalar: "string"},
				{Property: "LoadBalancerArns", Member: "LoadBalancerArns", Kind: "list", XMLName: "LoadBalancerArns", Item: "member", Scalar: "string"},
				{Property: "Matcher", Member: "Matcher", Kind: "structure", XMLName: "Matcher",
					Fields: []Field{
						{Property: "GrpcCode", Member: "GrpcCode", Kind: "scalar", XMLName: "GrpcCode", Scalar: "string"},
						{Property: "HttpCode", Member: "HttpCode", Kind: "scalar", XMLName: "HttpCode", Scalar: "string"},
					},
				},
				{Property: "Name", Member: "TargetGroupName", Kind: "scalar", XMLName: "TargetGroupName", Scalar: "string"},
				{Property: "Port", Member: "Port", Kind: "scalar", XMLName: "Port", Scalar: "number"},
				{Property: "Protocol", Member: "Protocol", Kind: "scalar", XMLName: "Protocol", Scalar: "string"},
				{Property: "ProtocolVersion", Member: "ProtocolVersion", Kind: "scalar", XMLName: "ProtocolVersion", Scalar: "string"},
				{Property: "TargetControlPort", Member: "TargetControlPort", Kind: "scalar", XMLName: "TargetControlPort", Scalar: "number"},
				{Property: "TargetGroupArn", Member: "TargetGroupArn", Kind: "scalar", XMLName: "TargetGroupArn", Scalar: "string"},
				{Property: "TargetGroupFullName", Member: "TargetGroupArn", Kind: "scalar", Transform: "arnResource", XMLName: "TargetGroupArn", Scalar: "string"},
				{Property: "TargetGroupName", Member: "TargetGroupName", Kind: "scalar", XMLName: "TargetGroupName", Scalar: "string"},
				{Property: "TargetType", Member: "TargetType", Kind: "scalar", XMLName: "TargetType", Scalar: "string"},
				{Property: "UnhealthyThresholdCount", Member: "UnhealthyThresholdCount", Kind: "scalar", XMLName: "UnhealthyThresholdCount", Scalar: "number"},
				{Property: "VpcId", Member: "VpcId", Kind: "scalar", XMLName: "VpcId", Scalar: "string"},
			},
			AbsentIDs: []string{"arn:aws:elasticloadbalancing:{region}:{account}:targetgroup/kraai-absent-probe/0123456789abcdef"},
			Also: []Reader{
				{
					Type:        "AWS::ElasticLoadBalancingV2::TargetGroup",
					Protocol:    "awsQuery",
					SigningName: "elasticloadbalancing",
					Host:        "elasticloadbalancing.{region}.amazonaws.com",
					Action:      "DescribeTags",
					Version:     "2015-12-01",
					Wrapper:     "DescribeTagsResult",
					Identifier: []Binding{
						{Property: "TargetGroupArn", Member: "ResourceArns", Location: "form", Name: "ResourceArns.member.1", List: true},
					},
					Response: []Step{{Name: "TagDescriptions", List: true, Item: "member"}},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list", XMLName: "Tags", Item: "member",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
				{
					Type:        "AWS::ElasticLoadBalancingV2::TargetGroup",
					Protocol:    "awsQuery",
					SigningName: "elasticloadbalancing",
					Host:        "elasticloadbalancing.{region}.amazonaws.com",
					Action:      "DescribeTargetGroupAttributes",
					Version:     "2015-12-01",
					Wrapper:     "DescribeTargetGroupAttributesResult",
					Identifier: []Binding{
						{Property: "TargetGroupArn", Member: "TargetGroupArn", Location: "form", Name: "TargetGroupArn"},
					},
					Fields: []Field{
						{Property: "TargetGroupAttributes", Member: "Attributes", Kind: "list", XMLName: "Attributes", Item: "member",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
				{
					Type:        "AWS::ElasticLoadBalancingV2::TargetGroup",
					Protocol:    "awsQuery",
					SigningName: "elasticloadbalancing",
					Host:        "elasticloadbalancing.{region}.amazonaws.com",
					Action:      "DescribeTargetHealth",
					Version:     "2015-12-01",
					Wrapper:     "DescribeTargetHealthResult",
					Identifier: []Binding{
						{Property: "TargetGroupArn", Member: "TargetGroupArn", Location: "form", Name: "TargetGroupArn"},
					},
					Fields: []Field{
						{Property: "Targets", Member: "Target", Kind: "structure", Via: []Step{{Name: "TargetHealthDescriptions", List: true, Item: "member"}}, XMLName: "Target",
							Fields: []Field{
								{Property: "AvailabilityZone", Member: "AvailabilityZone", Kind: "scalar", XMLName: "AvailabilityZone", Scalar: "string"},
								{Property: "Id", Member: "Id", Kind: "scalar", XMLName: "Id", Scalar: "string"},
								{Property: "Port", Member: "Port", Kind: "scalar", XMLName: "Port", Scalar: "number"},
								{Property: "QuicServerId", Member: "QuicServerId", Kind: "scalar", XMLName: "QuicServerId", Scalar: "string"},
							},
						},
					},
				},
			},
		},
	})
}
