// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SecurityAgent::Application": {
			Type:        "AWS::SecurityAgent::Application",
			Protocol:    "restJson1",
			SigningName: "securityagent",
			Host:        "securityagent.{region}.api.aws",
			Method:      "POST",
			URI:         "/GetApplication",
			Identifier: []Binding{
				{Property: "ApplicationId", Member: "applicationId", Location: "body"},
			},
			Fields: []Field{
				{Property: "ApplicationId", Member: "applicationId", Kind: "scalar"},
				{Property: "ApplicationName", Member: "applicationName", Kind: "scalar"},
				{Property: "DefaultKmsKeyId", Member: "defaultKmsKeyId", Kind: "scalar"},
				{Property: "Domain", Member: "domain", Kind: "scalar"},
				{Property: "IdCConfiguration", Member: "idcConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "IdCApplicationArn", Member: "idcApplicationArn", Kind: "scalar"},
						{Property: "IdCInstanceArn", Member: "idcInstanceArn", Kind: "scalar"},
					},
				},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
			},
		},
	})
}
