// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Config::Connector": {
			Type:        "AWS::Config::Connector",
			Protocol:    "awsJson1_1",
			SigningName: "config",
			Host:        "config.{region}.amazonaws.com",
			Target:      "StarlingDoveService.GetConnector",
			Identifier: []Binding{
				{Property: "Arn", Member: "Arn", Location: "body"},
			},
			Response: []Step{{Name: "Connector"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "ConnectorConfiguration", Member: "connectorConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Azure", Member: "azure", Kind: "structure",
							Fields: []Field{
								{Property: "ClientIdentifier", Member: "clientIdentifier", Kind: "scalar"},
								{Property: "TenantIdentifier", Member: "tenantIdentifier", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "CreatedTime", Member: "createdTime", Kind: "timestamp"},
				{Property: "Name", Member: "name", Kind: "scalar"},
			},
		},
	})
}
