// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::RolesAnywhere::Profile": {
			Type:        "AWS::RolesAnywhere::Profile",
			Protocol:    "restJson1",
			SigningName: "rolesanywhere",
			Host:        "rolesanywhere.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/profile/{profileId}",
			Identifier: []Binding{
				{Property: "ProfileId", Member: "profileId", Location: "label"},
			},
			Response: []Step{{Name: "profile"}},
			Fields: []Field{
				{Property: "AcceptRoleSessionName", Member: "acceptRoleSessionName", Kind: "scalar"},
				{Property: "AttributeMappings", Member: "attributeMappings", Kind: "list",
					Fields: []Field{
						{Property: "CertificateField", Member: "certificateField", Kind: "scalar"},
						{Property: "MappingRules", Member: "mappingRules", Kind: "list",
							Fields: []Field{
								{Property: "Specifier", Member: "specifier", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "DurationSeconds", Member: "durationSeconds", Kind: "scalar"},
				{Property: "Enabled", Member: "enabled", Kind: "scalar"},
				{Property: "ManagedPolicyArns", Member: "managedPolicyArns", Kind: "list"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "ProfileArn", Member: "profileArn", Kind: "scalar"},
				{Property: "ProfileId", Member: "profileId", Kind: "scalar"},
				{Property: "RoleArns", Member: "roleArns", Kind: "list"},
				{Property: "SessionPolicy", Member: "sessionPolicy", Kind: "scalar"},
			},
		},
	})
}
