// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ODB::OdbNetwork": {
			Type:        "AWS::ODB::OdbNetwork",
			Protocol:    "awsJson1_0",
			SigningName: "odb",
			Host:        "odb.{region}.amazonaws.com",
			Target:      "Odb.GetOdbNetwork",
			Identifier: []Binding{
				{Property: "OdbNetworkArn", Member: "odbNetworkId", Location: "body"},
			},
			Response: []Step{{Name: "odbNetwork"}},
			Fields: []Field{
				{Property: "AvailabilityZone", Member: "availabilityZone", Kind: "scalar"},
				{Property: "AvailabilityZoneId", Member: "availabilityZoneId", Kind: "scalar"},
				{Property: "BackupSubnetCidr", Member: "backupSubnetCidr", Kind: "scalar"},
				{Property: "ClientSubnetCidr", Member: "clientSubnetCidr", Kind: "scalar"},
				{Property: "CustomDomainName", Member: "customDomainName", Kind: "scalar"},
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "Ec2PlacementGroupIds", Member: "ec2PlacementGroupIds", Kind: "list"},
				{Property: "ManagedServices", Member: "managedServices", Kind: "structure",
					Fields: []Field{
						{Property: "CrossRegionS3RestoreSourcesAccess", Member: "crossRegionS3RestoreSourcesAccess", Kind: "list",
							Fields: []Field{
								{Property: "Ipv4Addresses", Member: "ipv4Addresses", Kind: "list"},
								{Property: "Region", Member: "region", Kind: "scalar"},
								{Property: "Status", Member: "status", Kind: "scalar"},
							},
						},
						{Property: "KmsAccess", Member: "kmsAccess", Kind: "structure",
							Fields: []Field{
								{Property: "DomainName", Member: "domainName", Kind: "scalar"},
								{Property: "Ipv4Addresses", Member: "ipv4Addresses", Kind: "list"},
								{Property: "KmsPolicyDocument", Member: "kmsPolicyDocument", Kind: "scalar"},
								{Property: "Status", Member: "status", Kind: "scalar"},
							},
						},
						{Property: "ManagedS3BackupAccess", Member: "managedS3BackupAccess", Kind: "structure",
							Fields: []Field{
								{Property: "Ipv4Addresses", Member: "ipv4Addresses", Kind: "list"},
								{Property: "Status", Member: "status", Kind: "scalar"},
							},
						},
						{Property: "ManagedServicesIpv4Cidrs", Member: "managedServicesIpv4Cidrs", Kind: "list"},
						{Property: "ResourceGatewayArn", Member: "resourceGatewayArn", Kind: "scalar"},
						{Property: "S3Access", Member: "s3Access", Kind: "structure",
							Fields: []Field{
								{Property: "DomainName", Member: "domainName", Kind: "scalar"},
								{Property: "Ipv4Addresses", Member: "ipv4Addresses", Kind: "list"},
								{Property: "S3PolicyDocument", Member: "s3PolicyDocument", Kind: "scalar"},
								{Property: "Status", Member: "status", Kind: "scalar"},
							},
						},
						{Property: "ServiceNetworkArn", Member: "serviceNetworkArn", Kind: "scalar"},
						{Property: "ServiceNetworkEndpoint", Member: "serviceNetworkEndpoint", Kind: "structure",
							Fields: []Field{
								{Property: "VpcEndpointId", Member: "vpcEndpointId", Kind: "scalar"},
								{Property: "VpcEndpointType", Member: "vpcEndpointType", Kind: "scalar"},
							},
						},
						{Property: "StsAccess", Member: "stsAccess", Kind: "structure",
							Fields: []Field{
								{Property: "DomainName", Member: "domainName", Kind: "scalar"},
								{Property: "Ipv4Addresses", Member: "ipv4Addresses", Kind: "list"},
								{Property: "Status", Member: "status", Kind: "scalar"},
								{Property: "StsPolicyDocument", Member: "stsPolicyDocument", Kind: "scalar"},
							},
						},
						{Property: "ZeroEtlAccess", Member: "zeroEtlAccess", Kind: "structure",
							Fields: []Field{
								{Property: "Cidr", Member: "cidr", Kind: "scalar"},
								{Property: "Status", Member: "status", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "OciNetworkAnchorId", Member: "ociNetworkAnchorId", Kind: "scalar"},
				{Property: "OciResourceAnchorName", Member: "ociResourceAnchorName", Kind: "scalar"},
				{Property: "OciVcnUrl", Member: "ociVcnUrl", Kind: "scalar"},
				{Property: "OdbNetworkArn", Member: "odbNetworkArn", Kind: "scalar"},
				{Property: "OdbNetworkId", Member: "odbNetworkId", Kind: "scalar"},
			},
		},
		"AWS::ODB::OdbPeeringConnection": {
			Type:        "AWS::ODB::OdbPeeringConnection",
			Protocol:    "awsJson1_0",
			SigningName: "odb",
			Host:        "odb.{region}.amazonaws.com",
			Target:      "Odb.GetOdbPeeringConnection",
			Identifier: []Binding{
				{Property: "OdbPeeringConnectionArn", Member: "odbPeeringConnectionId", Location: "body"},
			},
			Response: []Step{{Name: "odbPeeringConnection"}},
			Fields: []Field{
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "OdbNetworkArn", Member: "odbNetworkArn", Kind: "scalar"},
				{Property: "OdbPeeringConnectionArn", Member: "odbPeeringConnectionArn", Kind: "scalar"},
				{Property: "OdbPeeringConnectionId", Member: "odbPeeringConnectionId", Kind: "scalar"},
				{Property: "PeerNetworkArn", Member: "peerNetworkArn", Kind: "scalar"},
				{Property: "PeerNetworkCidrs", Member: "peerNetworkCidrs", Kind: "list"},
			},
		},
	})
}
