// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::AppRunner::AutoScalingConfiguration": {
			Type:        "AWS::AppRunner::AutoScalingConfiguration",
			Protocol:    "awsJson1_0",
			SigningName: "apprunner",
			Host:        "apprunner.{region}.amazonaws.com",
			Target:      "AppRunner.DescribeAutoScalingConfiguration",
			Identifier: []Binding{
				{Property: "AutoScalingConfigurationArn", Member: "AutoScalingConfigurationArn", Location: "body"},
			},
			Response: []Step{{Name: "AutoScalingConfiguration"}},
			Fields: []Field{
				{Property: "AutoScalingConfigurationArn", Member: "AutoScalingConfigurationArn", Kind: "scalar"},
				{Property: "AutoScalingConfigurationName", Member: "AutoScalingConfigurationName", Kind: "scalar"},
				{Property: "AutoScalingConfigurationRevision", Member: "AutoScalingConfigurationRevision", Kind: "scalar"},
				{Property: "Latest", Member: "Latest", Kind: "scalar"},
				{Property: "MaxConcurrency", Member: "MaxConcurrency", Kind: "scalar"},
				{Property: "MaxSize", Member: "MaxSize", Kind: "scalar"},
				{Property: "MinSize", Member: "MinSize", Kind: "scalar"},
			},
		},
		"AWS::AppRunner::ObservabilityConfiguration": {
			Type:        "AWS::AppRunner::ObservabilityConfiguration",
			Protocol:    "awsJson1_0",
			SigningName: "apprunner",
			Complete:    true,
			Host:        "apprunner.{region}.amazonaws.com",
			Target:      "AppRunner.DescribeObservabilityConfiguration",
			Identifier: []Binding{
				{Property: "ObservabilityConfigurationArn", Member: "ObservabilityConfigurationArn", Location: "body"},
			},
			Response: []Step{{Name: "ObservabilityConfiguration"}},
			Fields: []Field{
				{Property: "Latest", Member: "Latest", Kind: "scalar"},
				{Property: "ObservabilityConfigurationArn", Member: "ObservabilityConfigurationArn", Kind: "scalar"},
				{Property: "ObservabilityConfigurationName", Member: "ObservabilityConfigurationName", Kind: "scalar"},
				{Property: "ObservabilityConfigurationRevision", Member: "ObservabilityConfigurationRevision", Kind: "scalar"},
				{Property: "TraceConfiguration", Member: "TraceConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Vendor", Member: "Vendor", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::AppRunner::VpcConnector": {
			Type:        "AWS::AppRunner::VpcConnector",
			Protocol:    "awsJson1_0",
			SigningName: "apprunner",
			Complete:    true,
			Host:        "apprunner.{region}.amazonaws.com",
			Target:      "AppRunner.DescribeVpcConnector",
			Identifier: []Binding{
				{Property: "VpcConnectorArn", Member: "VpcConnectorArn", Location: "body"},
			},
			Response: []Step{{Name: "VpcConnector"}},
			Fields: []Field{
				{Property: "SecurityGroups", Member: "SecurityGroups", Kind: "list"},
				{Property: "Subnets", Member: "Subnets", Kind: "list"},
				{Property: "VpcConnectorArn", Member: "VpcConnectorArn", Kind: "scalar"},
				{Property: "VpcConnectorName", Member: "VpcConnectorName", Kind: "scalar"},
				{Property: "VpcConnectorRevision", Member: "VpcConnectorRevision", Kind: "scalar"},
			},
		},
		"AWS::AppRunner::VpcIngressConnection": {
			Type:        "AWS::AppRunner::VpcIngressConnection",
			Protocol:    "awsJson1_0",
			SigningName: "apprunner",
			Complete:    true,
			Host:        "apprunner.{region}.amazonaws.com",
			Target:      "AppRunner.DescribeVpcIngressConnection",
			Identifier: []Binding{
				{Property: "VpcIngressConnectionArn", Member: "VpcIngressConnectionArn", Location: "body"},
			},
			Response: []Step{{Name: "VpcIngressConnection"}},
			Fields: []Field{
				{Property: "DomainName", Member: "DomainName", Kind: "scalar"},
				{Property: "IngressVpcConfiguration", Member: "IngressVpcConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "VpcEndpointId", Member: "VpcEndpointId", Kind: "scalar"},
						{Property: "VpcId", Member: "VpcId", Kind: "scalar"},
					},
				},
				{Property: "ServiceArn", Member: "ServiceArn", Kind: "scalar"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
				{Property: "VpcIngressConnectionArn", Member: "VpcIngressConnectionArn", Kind: "scalar"},
				{Property: "VpcIngressConnectionName", Member: "VpcIngressConnectionName", Kind: "scalar"},
			},
		},
	})
}
