// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::NetworkFirewall::ContainerAssociation": {
			Type:        "AWS::NetworkFirewall::ContainerAssociation",
			Protocol:    "awsJson1_0",
			SigningName: "network-firewall",
			Complete:    true,
			Host:        "network-firewall.{region}.amazonaws.com",
			Target:      "NetworkFirewall_20201112.DescribeContainerAssociation",
			Identifier: []Binding{
				{Property: "ContainerAssociationArn", Member: "ContainerAssociationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "ContainerAssociationArn", Member: "ContainerAssociationArn", Kind: "scalar"},
				{Property: "ContainerAssociationName", Member: "ContainerAssociationName", Kind: "scalar"},
				{Property: "ContainerMonitoringConfigurations", Member: "ContainerMonitoringConfigurations", Kind: "list",
					Fields: []Field{
						{Property: "AttributeFilters", Member: "AttributeFilters", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
						{Property: "ClusterArn", Member: "ClusterArn", Kind: "scalar"},
					},
				},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "ResolvedCidrCount", Member: "ResolvedCidrCount", Kind: "scalar"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
				{Property: "Tags", Member: "Tags", Kind: "list",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "Type", Member: "Type", Kind: "scalar"},
			},
		},
	})
}
