// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Invoicing::ProcurementPortalPreference": {
			Type:          "AWS::Invoicing::ProcurementPortalPreference",
			Protocol:      "awsJson1_0",
			SigningName:   "invoicing",
			Host:          "invoicing.us-east-1.api.aws",
			SigningRegion: "us-east-1",
			Target:        "Invoicing.GetProcurementPortalPreference",
			Identifier: []Binding{
				{Property: "ProcurementPortalPreferenceArn", Member: "ProcurementPortalPreferenceArn", Location: "body"},
			},
			Response: []Step{{Name: "ProcurementPortalPreference"}},
			Fields: []Field{
				{Property: "AwsAccountId", Member: "AwsAccountId", Kind: "scalar"},
				{Property: "BuyerDomain", Member: "BuyerDomain", Kind: "scalar"},
				{Property: "BuyerIdentifier", Member: "BuyerIdentifier", Kind: "scalar"},
				{Property: "Contacts", Member: "Contacts", Kind: "list",
					Fields: []Field{
						{Property: "Email", Member: "Email", Kind: "scalar"},
						{Property: "Name", Member: "Name", Kind: "scalar"},
					},
				},
				{Property: "CreateDate", Member: "CreateDate", Kind: "timestamp"},
				{Property: "EinvoiceDeliveryEnabled", Member: "EinvoiceDeliveryEnabled", Kind: "scalar"},
				{Property: "EinvoiceDeliveryPreference", Member: "EinvoiceDeliveryPreference", Kind: "structure",
					Fields: []Field{
						{Property: "ConnectionTestingMethod", Member: "ConnectionTestingMethod", Kind: "scalar"},
						{Property: "EinvoiceDeliveryActivationDate", Member: "EinvoiceDeliveryActivationDate", Kind: "timestamp"},
						{Property: "EinvoiceDeliveryAttachmentTypes", Member: "EinvoiceDeliveryAttachmentTypes", Kind: "list"},
						{Property: "EinvoiceDeliveryDocumentTypes", Member: "EinvoiceDeliveryDocumentTypes", Kind: "list"},
						{Property: "Protocol", Member: "Protocol", Kind: "scalar"},
						{Property: "PurchaseOrderDataSources", Member: "PurchaseOrderDataSources", Kind: "list",
							Fields: []Field{
								{Property: "EinvoiceDeliveryDocumentType", Member: "EinvoiceDeliveryDocumentType", Kind: "scalar"},
								{Property: "PurchaseOrderDataSourceType", Member: "PurchaseOrderDataSourceType", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "EinvoiceDeliveryPreferenceStatus", Member: "EinvoiceDeliveryPreferenceStatus", Kind: "scalar"},
				{Property: "LastUpdateDate", Member: "LastUpdateDate", Kind: "timestamp"},
				{Property: "ProcurementPortalInstanceEndpoint", Member: "ProcurementPortalInstanceEndpoint", Kind: "scalar"},
				{Property: "ProcurementPortalName", Member: "ProcurementPortalName", Kind: "scalar"},
				{Property: "ProcurementPortalPreferenceArn", Member: "ProcurementPortalPreferenceArn", Kind: "scalar"},
				{Property: "PurchaseOrderRetrievalEnabled", Member: "PurchaseOrderRetrievalEnabled", Kind: "scalar"},
				{Property: "PurchaseOrderRetrievalEndpoint", Member: "PurchaseOrderRetrievalEndpoint", Kind: "scalar"},
				{Property: "PurchaseOrderRetrievalPreferenceStatus", Member: "PurchaseOrderRetrievalPreferenceStatus", Kind: "scalar"},
				{Property: "Selector", Member: "Selector", Kind: "structure",
					Fields: []Field{
						{Property: "InvoiceUnitArns", Member: "InvoiceUnitArns", Kind: "list"},
					},
				},
				{Property: "SupplierDomain", Member: "SupplierDomain", Kind: "scalar"},
				{Property: "SupplierIdentifier", Member: "SupplierIdentifier", Kind: "scalar"},
				{Property: "TestEnvPreference", Member: "TestEnvPreference", Kind: "structure",
					Fields: []Field{
						{Property: "BuyerDomain", Member: "BuyerDomain", Kind: "scalar"},
						{Property: "BuyerIdentifier", Member: "BuyerIdentifier", Kind: "scalar"},
						{Property: "ProcurementPortalInstanceEndpoint", Member: "ProcurementPortalInstanceEndpoint", Kind: "scalar"},
						{Property: "ProcurementPortalSharedSecret", Member: "ProcurementPortalSharedSecret", Kind: "scalar"},
						{Property: "SupplierDomain", Member: "SupplierDomain", Kind: "scalar"},
						{Property: "SupplierIdentifier", Member: "SupplierIdentifier", Kind: "scalar"},
					},
				},
				{Property: "Version", Member: "Version", Kind: "scalar"},
			},
		},
	})
}
