// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::DataExchange::DataSet": {
			Type:        "AWS::DataExchange::DataSet",
			Protocol:    "restJson1",
			SigningName: "dataexchange",
			Host:        "dataexchange.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/data-sets/{DataSetId}",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "DataSetId", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "AssetType", Member: "AssetType", Kind: "scalar"},
				{Property: "CreatedAt", Member: "CreatedAt", Kind: "timestamp"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Origin", Member: "Origin", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "UpdatedAt", Kind: "timestamp"},
			},
		},
	})
}
