// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::DataSync::LocationEFS": {
			Type:        "AWS::DataSync::LocationEFS",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationEfs",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "AccessPointArn", Member: "AccessPointArn", Kind: "scalar"},
				{Property: "Ec2Config", Member: "Ec2Config", Kind: "structure",
					Fields: []Field{
						{Property: "SecurityGroupArns", Member: "SecurityGroupArns", Kind: "list"},
						{Property: "SubnetArn", Member: "SubnetArn", Kind: "scalar"},
					},
				},
				{Property: "FileSystemAccessRoleArn", Member: "FileSystemAccessRoleArn", Kind: "scalar"},
				{Property: "InTransitEncryption", Member: "InTransitEncryption", Kind: "scalar"},
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
			},
		},
		"AWS::DataSync::LocationFSxLustre": {
			Type:        "AWS::DataSync::LocationFSxLustre",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationFsxLustre",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "SecurityGroupArns", Member: "SecurityGroupArns", Kind: "list"},
			},
		},
		"AWS::DataSync::LocationFSxONTAP": {
			Type:        "AWS::DataSync::LocationFSxONTAP",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationFsxOntap",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "FsxFilesystemArn", Member: "FsxFilesystemArn", Kind: "scalar"},
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "Protocol", Member: "Protocol", Kind: "structure",
					Fields: []Field{
						{Property: "NFS", Member: "NFS", Kind: "structure",
							Fields: []Field{
								{Property: "MountOptions", Member: "MountOptions", Kind: "structure",
									Fields: []Field{
										{Property: "Version", Member: "Version", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "SMB", Member: "SMB", Kind: "structure",
							Fields: []Field{
								{Property: "CmkSecretConfig", Member: "CmkSecretConfig", Kind: "structure",
									Fields: []Field{
										{Property: "KmsKeyArn", Member: "KmsKeyArn", Kind: "scalar"},
										{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
									},
								},
								{Property: "CustomSecretConfig", Member: "CustomSecretConfig", Kind: "structure",
									Fields: []Field{
										{Property: "SecretAccessRoleArn", Member: "SecretAccessRoleArn", Kind: "scalar"},
										{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
									},
								},
								{Property: "Domain", Member: "Domain", Kind: "scalar"},
								{Property: "ManagedSecretConfig", Member: "ManagedSecretConfig", Kind: "structure",
									Fields: []Field{
										{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
									},
								},
								{Property: "MountOptions", Member: "MountOptions", Kind: "structure",
									Fields: []Field{
										{Property: "Version", Member: "Version", Kind: "scalar"},
									},
								},
								{Property: "User", Member: "User", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "SecurityGroupArns", Member: "SecurityGroupArns", Kind: "list"},
				{Property: "StorageVirtualMachineArn", Member: "StorageVirtualMachineArn", Kind: "scalar"},
			},
		},
		"AWS::DataSync::LocationFSxOpenZFS": {
			Type:        "AWS::DataSync::LocationFSxOpenZFS",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationFsxOpenZfs",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "Protocol", Member: "Protocol", Kind: "structure",
					Fields: []Field{
						{Property: "NFS", Member: "NFS", Kind: "structure",
							Fields: []Field{
								{Property: "MountOptions", Member: "MountOptions", Kind: "structure",
									Fields: []Field{
										{Property: "Version", Member: "Version", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{Property: "SecurityGroupArns", Member: "SecurityGroupArns", Kind: "list"},
			},
		},
		"AWS::DataSync::LocationFSxWindows": {
			Type:        "AWS::DataSync::LocationFSxWindows",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationFsxWindows",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "CmkSecretConfig", Member: "CmkSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyArn", Member: "KmsKeyArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "CustomSecretConfig", Member: "CustomSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretAccessRoleArn", Member: "SecretAccessRoleArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "Domain", Member: "Domain", Kind: "scalar"},
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "ManagedSecretConfig", Member: "ManagedSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "SecurityGroupArns", Member: "SecurityGroupArns", Kind: "list"},
				{Property: "User", Member: "User", Kind: "scalar"},
			},
		},
		"AWS::DataSync::LocationHDFS": {
			Type:        "AWS::DataSync::LocationHDFS",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationHdfs",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "AgentArns", Member: "AgentArns", Kind: "list"},
				{Property: "AuthenticationType", Member: "AuthenticationType", Kind: "scalar"},
				{Property: "BlockSize", Member: "BlockSize", Kind: "scalar"},
				{Property: "CmkSecretConfig", Member: "CmkSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyArn", Member: "KmsKeyArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "CustomSecretConfig", Member: "CustomSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretAccessRoleArn", Member: "SecretAccessRoleArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "KerberosPrincipal", Member: "KerberosPrincipal", Kind: "scalar"},
				{Property: "KmsKeyProviderUri", Member: "KmsKeyProviderUri", Kind: "scalar"},
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "ManagedSecretConfig", Member: "ManagedSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "NameNodes", Member: "NameNodes", Kind: "list",
					Fields: []Field{
						{Property: "Hostname", Member: "Hostname", Kind: "scalar"},
						{Property: "Port", Member: "Port", Kind: "scalar"},
					},
				},
				{Property: "QopConfiguration", Member: "QopConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "DataTransferProtection", Member: "DataTransferProtection", Kind: "scalar"},
						{Property: "RpcProtection", Member: "RpcProtection", Kind: "scalar"},
					},
				},
				{Property: "ReplicationFactor", Member: "ReplicationFactor", Kind: "scalar"},
				{Property: "SimpleUser", Member: "SimpleUser", Kind: "scalar"},
			},
		},
		"AWS::DataSync::LocationNFS": {
			Type:        "AWS::DataSync::LocationNFS",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationNfs",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "MountOptions", Member: "MountOptions", Kind: "structure",
					Fields: []Field{
						{Property: "Version", Member: "Version", Kind: "scalar"},
					},
				},
				{Property: "OnPremConfig", Member: "OnPremConfig", Kind: "structure",
					Fields: []Field{
						{Property: "AgentArns", Member: "AgentArns", Kind: "list"},
					},
				},
			},
		},
		"AWS::DataSync::LocationS3": {
			Type:        "AWS::DataSync::LocationS3",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationS3",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "S3Config", Member: "S3Config", Kind: "structure",
					Fields: []Field{
						{Property: "BucketAccessRoleArn", Member: "BucketAccessRoleArn", Kind: "scalar"},
					},
				},
				{Property: "S3StorageClass", Member: "S3StorageClass", Kind: "scalar"},
			},
		},
		"AWS::DataSync::LocationSMB": {
			Type:        "AWS::DataSync::LocationSMB",
			Protocol:    "awsJson1_1",
			SigningName: "datasync",
			Host:        "datasync.{region}.amazonaws.com",
			Target:      "FmrsService.DescribeLocationSmb",
			Identifier: []Binding{
				{Property: "LocationArn", Member: "LocationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "AgentArns", Member: "AgentArns", Kind: "list"},
				{Property: "AuthenticationType", Member: "AuthenticationType", Kind: "scalar"},
				{Property: "CmkSecretConfig", Member: "CmkSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyArn", Member: "KmsKeyArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "CustomSecretConfig", Member: "CustomSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretAccessRoleArn", Member: "SecretAccessRoleArn", Kind: "scalar"},
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "DnsIpAddresses", Member: "DnsIpAddresses", Kind: "list"},
				{Property: "Domain", Member: "Domain", Kind: "scalar"},
				{Property: "KerberosPrincipal", Member: "KerberosPrincipal", Kind: "scalar"},
				{Property: "LocationArn", Member: "LocationArn", Kind: "scalar"},
				{Property: "LocationUri", Member: "LocationUri", Kind: "scalar"},
				{Property: "ManagedSecretConfig", Member: "ManagedSecretConfig", Kind: "structure",
					Fields: []Field{
						{Property: "SecretArn", Member: "SecretArn", Kind: "scalar"},
					},
				},
				{Property: "MountOptions", Member: "MountOptions", Kind: "structure",
					Fields: []Field{
						{Property: "Version", Member: "Version", Kind: "scalar"},
					},
				},
				{Property: "User", Member: "User", Kind: "scalar"},
			},
		},
	})
}
