// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::RDS::DBSubnetGroup": {
			Type:        "AWS::RDS::DBSubnetGroup",
			Protocol:    "awsQuery",
			SigningName: "rds",
			Complete:    true,
			Production:  true,
			Host:        "rds.{region}.amazonaws.com",
			Action:      "DescribeDBSubnetGroups",
			Version:     "2014-10-31",
			Wrapper:     "DescribeDBSubnetGroupsResult",
			Identifier: []Binding{
				{Property: "DBSubnetGroupName", Member: "DBSubnetGroupName", Location: "form", Name: "DBSubnetGroupName"},
			},
			AbsentErrors: []string{"DBSubnetGroupNotFoundFault"},
			PageToken:    []string{"Marker"},
			Response:     []Step{{Name: "DBSubnetGroups", List: true, Item: "DBSubnetGroup"}},
			Fields: []Field{
				{Property: "DBSubnetGroupArn", Member: "DBSubnetGroupArn", Kind: "scalar", XMLName: "DBSubnetGroupArn", Scalar: "string"},
				{Property: "DBSubnetGroupDescription", Member: "DBSubnetGroupDescription", Kind: "scalar", XMLName: "DBSubnetGroupDescription", Scalar: "string"},
				{Property: "DBSubnetGroupName", Member: "DBSubnetGroupName", Kind: "scalar", XMLName: "DBSubnetGroupName", Scalar: "string"},
				{Property: "SubnetIds", Member: "SubnetIdentifier", Kind: "scalar", Via: []Step{{Name: "Subnets", List: true, Item: "Subnet"}}, XMLName: "SubnetIdentifier", Scalar: "string"},
			},
			AbsentIDs: []string{"kraai-absent-probe-0123456789"},
			Capture: []Field{
				{Property: "Arn", Member: "DBSubnetGroupArn", Kind: "scalar", XMLName: "DBSubnetGroupArn", Scalar: "string"},
			},
			LifecycleComplete: true,
			MutationCaptures:  true,
			Create:            &MutationCall{Operation: "CreateDBSubnetGroup", Target: "AmazonRDSv19.CreateDBSubnetGroup", NameProperty: "DBSubnetGroupName", NameTag: "kraai:resource-name", Input: map[string]any{"DBSubnetGroupDescription": "{DBSubnetGroupDescription}", "DBSubnetGroupName": "{DBSubnetGroupName}", "SubnetIds": "{SubnetIds}", "Tags": "{Tags}"}, Properties: []string{"DBSubnetGroupDescription", "DBSubnetGroupName", "SubnetIds", "Tags"}, Identifier: map[string]string{"DBSubnetGroupName": "CreateDBSubnetGroupResult.DBSubnetGroup.DBSubnetGroupName"}, Form: map[string]FormStep{"DBSubnetGroupDescription": {Key: "DBSubnetGroupDescription", Kind: "scalar"}, "DBSubnetGroupName": {Key: "DBSubnetGroupName", Kind: "scalar"}, "SubnetIds": {Key: "SubnetIds", Kind: "list", Item: "SubnetIdentifier"}, "SubnetIds[]": {Key: "", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "Tag"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}},
			Delete:            &MutationCall{Operation: "DeleteDBSubnetGroup", Target: "AmazonRDSv19.DeleteDBSubnetGroup", Input: map[string]any{"DBSubnetGroupName": "{DBSubnetGroupName}"}, AbsentErrors: []string{"DBSubnetGroupNotFoundFault"}, Form: map[string]FormStep{"DBSubnetGroupName": {Key: "DBSubnetGroupName", Kind: "scalar"}}},
			Update: []MutationCall{
				MutationCall{Operation: "ModifyDBSubnetGroup", Target: "AmazonRDSv19.ModifyDBSubnetGroup", Input: map[string]any{"DBSubnetGroupDescription": "{DBSubnetGroupDescription}", "DBSubnetGroupName": "{DBSubnetGroupName}", "SubnetIds": "{SubnetIds}"}, Properties: []string{"DBSubnetGroupDescription", "SubnetIds"}, Form: map[string]FormStep{"DBSubnetGroupDescription": {Key: "DBSubnetGroupDescription", Kind: "scalar"}, "DBSubnetGroupName": {Key: "DBSubnetGroupName", Kind: "scalar"}, "SubnetIds": {Key: "SubnetIds", Kind: "list", Item: "SubnetIdentifier"}, "SubnetIds[]": {Key: "", Kind: "scalar"}}, Together: true, Required: []string{"SubnetIds"}},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "AddTagsToResource", Target: "AmazonRDSv19.AddTagsToResource", TagProperty: "Tags", Input: map[string]any{"ResourceName": "{Arn}", "Tags": "{added}"}, Form: map[string]FormStep{"ResourceName": {Key: "ResourceName", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "Tag"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}}, Remove: &MutationCall{Operation: "RemoveTagsFromResource", Target: "AmazonRDSv19.RemoveTagsFromResource", Input: map[string]any{"ResourceName": "{Arn}", "TagKeys": "{removed}"}, Form: map[string]FormStep{"ResourceName": {Key: "ResourceName", Kind: "scalar"}, "TagKeys": {Key: "TagKeys", Kind: "list", Item: "member"}, "TagKeys[]": {Key: "", Kind: "scalar"}}}},
			},
			Also: []Reader{
				{
					Type:        "AWS::RDS::DBSubnetGroup",
					Protocol:    "awsQuery",
					SigningName: "rds",
					Host:        "rds.{region}.amazonaws.com",
					Action:      "ListTagsForResource",
					Version:     "2014-10-31",
					Wrapper:     "ListTagsForResourceResult",
					Input: []Binding{
						Binding{Location: "form", Member: "ResourceName", Name: "ResourceName", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "TagList", Kind: "list", XMLName: "TagList", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
			},
			Mutable: true,
		},
	})
}
