// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CustomerProfiles::Domain": {
			Type:        "AWS::CustomerProfiles::Domain",
			Protocol:    "restJson1",
			SigningName: "profile",
			Host:        "profile.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/domains/{DomainName}",
			Identifier: []Binding{
				{Property: "DomainName", Member: "DomainName", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "CreatedAt", Kind: "timestamp"},
				{Property: "DataStore", Member: "DataStore", Kind: "structure",
					Fields: []Field{
						{Property: "Enabled", Member: "Enabled", Kind: "scalar"},
						{Property: "Readiness", Member: "Readiness", Kind: "structure",
							Fields: []Field{
								{Property: "Message", Member: "Message", Kind: "scalar"},
								{Property: "ProgressPercentage", Member: "ProgressPercentage", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "DeadLetterQueueUrl", Member: "DeadLetterQueueUrl", Kind: "scalar"},
				{Property: "DefaultEncryptionKey", Member: "DefaultEncryptionKey", Kind: "scalar"},
				{Property: "DefaultExpirationDays", Member: "DefaultExpirationDays", Kind: "scalar"},
				{Property: "DomainName", Member: "DomainName", Kind: "scalar"},
				{Property: "LastUpdatedAt", Member: "LastUpdatedAt", Kind: "timestamp"},
				{Property: "Matching", Member: "Matching", Kind: "structure",
					Fields: []Field{
						{Property: "AutoMerging", Member: "AutoMerging", Kind: "structure",
							Fields: []Field{
								{Property: "ConflictResolution", Member: "ConflictResolution", Kind: "structure",
									Fields: []Field{
										{Property: "ConflictResolvingModel", Member: "ConflictResolvingModel", Kind: "scalar"},
										{Property: "SourceName", Member: "SourceName", Kind: "scalar"},
									},
								},
								{Property: "Consolidation", Member: "Consolidation", Kind: "structure",
									Fields: []Field{
										{Property: "MatchingAttributesList", Member: "MatchingAttributesList", Kind: "list"},
									},
								},
								{Property: "Enabled", Member: "Enabled", Kind: "scalar"},
								{Property: "MinAllowedConfidenceScoreForMerging", Member: "MinAllowedConfidenceScoreForMerging", Kind: "scalar"},
							},
						},
						{Property: "Enabled", Member: "Enabled", Kind: "scalar"},
						{Property: "ExportingConfig", Member: "ExportingConfig", Kind: "structure",
							Fields: []Field{
								{Property: "S3Exporting", Member: "S3Exporting", Kind: "structure",
									Fields: []Field{
										{Property: "S3BucketName", Member: "S3BucketName", Kind: "scalar"},
										{Property: "S3KeyName", Member: "S3KeyName", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "JobSchedule", Member: "JobSchedule", Kind: "structure",
							Fields: []Field{
								{Property: "DayOfTheWeek", Member: "DayOfTheWeek", Kind: "scalar"},
								{Property: "Time", Member: "Time", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "RuleBasedMatching", Member: "RuleBasedMatching", Kind: "structure",
					Fields: []Field{
						{Property: "AttributeTypesSelector", Member: "AttributeTypesSelector", Kind: "structure",
							Fields: []Field{
								{Property: "Address", Member: "Address", Kind: "list"},
								{Property: "AttributeMatchingModel", Member: "AttributeMatchingModel", Kind: "scalar"},
								{Property: "EmailAddress", Member: "EmailAddress", Kind: "list"},
								{Property: "PhoneNumber", Member: "PhoneNumber", Kind: "list"},
							},
						},
						{Property: "ConflictResolution", Member: "ConflictResolution", Kind: "structure",
							Fields: []Field{
								{Property: "ConflictResolvingModel", Member: "ConflictResolvingModel", Kind: "scalar"},
								{Property: "SourceName", Member: "SourceName", Kind: "scalar"},
							},
						},
						{Property: "Enabled", Member: "Enabled", Kind: "scalar"},
						{Property: "ExportingConfig", Member: "ExportingConfig", Kind: "structure",
							Fields: []Field{
								{Property: "S3Exporting", Member: "S3Exporting", Kind: "structure",
									Fields: []Field{
										{Property: "S3BucketName", Member: "S3BucketName", Kind: "scalar"},
										{Property: "S3KeyName", Member: "S3KeyName", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "MatchingRules", Member: "MatchingRules", Kind: "list",
							Fields: []Field{
								{Property: "Rule", Member: "Rule", Kind: "list"},
							},
						},
						{Property: "MaxAllowedRuleLevelForMatching", Member: "MaxAllowedRuleLevelForMatching", Kind: "scalar"},
						{Property: "MaxAllowedRuleLevelForMerging", Member: "MaxAllowedRuleLevelForMerging", Kind: "scalar"},
						{Property: "Status", Member: "Status", Kind: "scalar"},
					},
				},
				{Property: "Stats", Member: "Stats", Kind: "structure",
					Fields: []Field{
						{Property: "MeteringProfileCount", Member: "MeteringProfileCount", Kind: "scalar"},
						{Property: "ObjectCount", Member: "ObjectCount", Kind: "scalar"},
						{Property: "ProfileCount", Member: "ProfileCount", Kind: "scalar"},
						{Property: "TotalSize", Member: "TotalSize", Kind: "scalar"},
					},
				},
			},
		},
	})
}
