// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SSM::Association": {
			Type:        "AWS::SSM::Association",
			Protocol:    "awsJson1_1",
			SigningName: "ssm",
			Host:        "ssm.{region}.amazonaws.com",
			Target:      "AmazonSSM.DescribeAssociation",
			Identifier: []Binding{
				{Property: "AssociationId", Member: "AssociationId", Location: "body"},
			},
			Response: []Step{{Name: "AssociationDescription"}},
			Fields: []Field{
				{Property: "ApplyOnlyAtCronInterval", Member: "ApplyOnlyAtCronInterval", Kind: "scalar"},
				{Property: "AssociationDispatchAssumeRole", Member: "AssociationDispatchAssumeRole", Kind: "scalar"},
				{Property: "AssociationId", Member: "AssociationId", Kind: "scalar"},
				{Property: "AssociationName", Member: "AssociationName", Kind: "scalar"},
				{Property: "AutomationTargetParameterName", Member: "AutomationTargetParameterName", Kind: "scalar"},
				{Property: "CalendarNames", Member: "CalendarNames", Kind: "list"},
				{Property: "ComplianceSeverity", Member: "ComplianceSeverity", Kind: "scalar"},
				{Property: "DocumentVersion", Member: "DocumentVersion", Kind: "scalar"},
				{Property: "InstanceId", Member: "InstanceId", Kind: "scalar"},
				{Property: "MaxConcurrency", Member: "MaxConcurrency", Kind: "scalar"},
				{Property: "MaxErrors", Member: "MaxErrors", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "OutputLocation", Member: "OutputLocation", Kind: "structure",
					Fields: []Field{
						{Property: "S3Location", Member: "S3Location", Kind: "structure",
							Fields: []Field{
								{Property: "OutputS3BucketName", Member: "OutputS3BucketName", Kind: "scalar"},
								{Property: "OutputS3KeyPrefix", Member: "OutputS3KeyPrefix", Kind: "scalar"},
								{Property: "OutputS3Region", Member: "OutputS3Region", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "Parameters", Member: "Parameters", Kind: "map"},
				{Property: "ScheduleExpression", Member: "ScheduleExpression", Kind: "scalar"},
				{Property: "ScheduleOffset", Member: "ScheduleOffset", Kind: "scalar"},
				{Property: "SyncCompliance", Member: "SyncCompliance", Kind: "scalar"},
				{Property: "Targets", Member: "Targets", Kind: "list",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar"},
						{Property: "Values", Member: "Values", Kind: "list"},
					},
				},
			},
		},
		"AWS::SSM::MaintenanceWindow": {
			Type:        "AWS::SSM::MaintenanceWindow",
			Protocol:    "awsJson1_1",
			SigningName: "ssm",
			Host:        "ssm.{region}.amazonaws.com",
			Target:      "AmazonSSM.GetMaintenanceWindow",
			Identifier: []Binding{
				{Property: "WindowId", Member: "WindowId", Location: "body"},
			},
			Fields: []Field{
				{Property: "AllowUnassociatedTargets", Member: "AllowUnassociatedTargets", Kind: "scalar"},
				{Property: "Cutoff", Member: "Cutoff", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Duration", Member: "Duration", Kind: "scalar"},
				{Property: "EndDate", Member: "EndDate", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Schedule", Member: "Schedule", Kind: "scalar"},
				{Property: "ScheduleOffset", Member: "ScheduleOffset", Kind: "scalar"},
				{Property: "ScheduleTimezone", Member: "ScheduleTimezone", Kind: "scalar"},
				{Property: "StartDate", Member: "StartDate", Kind: "scalar"},
				{Property: "WindowId", Member: "WindowId", Kind: "scalar"},
			},
		},
		"AWS::SSM::ServiceSetting": {
			Type:        "AWS::SSM::ServiceSetting",
			Protocol:    "awsJson1_1",
			SigningName: "ssm",
			Complete:    true,
			Host:        "ssm.{region}.amazonaws.com",
			Target:      "AmazonSSM.GetServiceSetting",
			Identifier: []Binding{
				{Property: "Arn", Member: "SettingId", Location: "body"},
			},
			Response: []Step{{Name: "ServiceSetting"}},
			Fields: []Field{
				{Property: "Arn", Member: "ARN", Kind: "scalar"},
				{Property: "LastModifiedDate", Member: "LastModifiedDate", Kind: "timestamp"},
				{Property: "LastModifiedUser", Member: "LastModifiedUser", Kind: "scalar"},
				{Property: "SettingId", Member: "SettingId", Kind: "scalar"},
				{Property: "SettingValue", Member: "SettingValue", Kind: "scalar"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
			},
		},
	})
}
