// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CertificateManager::AcmeExternalAccountBinding": {
			Type:        "AWS::CertificateManager::AcmeExternalAccountBinding",
			Protocol:    "awsJson1_1",
			SigningName: "acm",
			Host:        "acm.{region}.amazonaws.com",
			Target:      "CertificateManager.DescribeAcmeExternalAccountBinding",
			Identifier: []Binding{
				{Property: "AcmeExternalAccountBindingArn", Member: "AcmeExternalAccountBindingArn", Location: "body"},
			},
			Response: []Step{{Name: "ExternalAccountBinding"}},
			Fields: []Field{
				{Property: "AcmeEndpointArn", Member: "AcmeEndpointArn", Kind: "scalar"},
				{Property: "AcmeExternalAccountBindingArn", Member: "AcmeExternalAccountBindingArn", Kind: "scalar"},
				{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
			},
		},
	})
}
