// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::LakeFormation::Tag": {
			Type:        "AWS::LakeFormation::Tag",
			Protocol:    "restJson1",
			SigningName: "lakeformation",
			Complete:    true,
			Host:        "lakeformation.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/GetLFTag",
			Identifier: []Binding{
				{Property: "TagKey", Member: "TagKey", Location: "body"},
			},
			Fields: []Field{
				{Property: "CatalogId", Member: "CatalogId", Kind: "scalar"},
				{Property: "TagKey", Member: "TagKey", Kind: "scalar"},
				{Property: "TagValues", Member: "TagValues", Kind: "list"},
			},
		},
	})
}
