// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::GreengrassV2::ComponentVersion": {
			Type:        "AWS::GreengrassV2::ComponentVersion",
			Protocol:    "restJson1",
			SigningName: "greengrass",
			Complete:    true,
			Host:        "greengrass.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/greengrass/v2/components/{arn}/metadata",
			Identifier: []Binding{
				{Property: "Arn", Member: "arn", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "ComponentName", Member: "componentName", Kind: "scalar"},
				{Property: "ComponentVersion", Member: "componentVersion", Kind: "scalar"},
				{Property: "Tags", Member: "tags", Kind: "map"},
			},
		},
	})
}
