// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::PCS::Cluster": {
			Type:        "AWS::PCS::Cluster",
			Protocol:    "awsJson1_0",
			SigningName: "pcs",
			Host:        "pcs.{region}.amazonaws.com",
			Target:      "AWSParallelComputingService.GetCluster",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "clusterIdentifier", Value: "{Arn:arnName}"},
			},
			Response: []Step{{Name: "cluster"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Endpoints", Member: "endpoints", Kind: "list",
					Fields: []Field{
						{Property: "Ipv6Address", Member: "ipv6Address", Kind: "scalar"},
						{Property: "Port", Member: "port", Kind: "scalar"},
						{Property: "PrivateIpAddress", Member: "privateIpAddress", Kind: "scalar"},
						{Property: "PublicIpAddress", Member: "publicIpAddress", Kind: "scalar"},
						{Property: "Type", Member: "type", Kind: "scalar"},
					},
				},
				{Property: "ErrorInfo", Member: "errorInfo", Kind: "list",
					Fields: []Field{
						{Property: "Code", Member: "code", Kind: "scalar"},
						{Property: "Message", Member: "message", Kind: "scalar"},
					},
				},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Networking", Member: "networking", Kind: "structure",
					Fields: []Field{
						{Property: "NetworkType", Member: "networkType", Kind: "scalar"},
						{Property: "SecurityGroupIds", Member: "securityGroupIds", Kind: "list"},
						{Property: "SubnetIds", Member: "subnetIds", Kind: "list"},
					},
				},
				{Property: "Scheduler", Member: "scheduler", Kind: "structure",
					Fields: []Field{
						{Property: "Type", Member: "type", Kind: "scalar"},
						{Property: "Version", Member: "version", Kind: "scalar"},
					},
				},
				{Property: "Size", Member: "size", Kind: "scalar"},
				{Property: "SlurmConfiguration", Member: "slurmConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "Accounting", Member: "accounting", Kind: "structure",
							Fields: []Field{
								{Property: "DefaultPurgeTimeInDays", Member: "defaultPurgeTimeInDays", Kind: "scalar"},
								{Property: "Mode", Member: "mode", Kind: "scalar"},
							},
						},
						{Property: "AuthKey", Member: "authKey", Kind: "structure",
							Fields: []Field{
								{Property: "SecretArn", Member: "secretArn", Kind: "scalar"},
								{Property: "SecretVersion", Member: "secretVersion", Kind: "scalar"},
							},
						},
						{Property: "CgroupCustomSettings", Member: "cgroupCustomSettings", Kind: "list",
							Fields: []Field{
								{Property: "ParameterName", Member: "parameterName", Kind: "scalar"},
								{Property: "ParameterValue", Member: "parameterValue", Kind: "scalar"},
							},
						},
						{Property: "JwtAuth", Member: "jwtAuth", Kind: "structure",
							Fields: []Field{
								{Property: "JwtKey", Member: "jwtKey", Kind: "structure",
									Fields: []Field{
										{Property: "SecretArn", Member: "secretArn", Kind: "scalar"},
										{Property: "SecretVersion", Member: "secretVersion", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "ScaleDownIdleTimeInSeconds", Member: "scaleDownIdleTimeInSeconds", Kind: "scalar"},
						{Property: "SlurmCustomSettings", Member: "slurmCustomSettings", Kind: "list",
							Fields: []Field{
								{Property: "ParameterName", Member: "parameterName", Kind: "scalar"},
								{Property: "ParameterValue", Member: "parameterValue", Kind: "scalar"},
							},
						},
						{Property: "SlurmRest", Member: "slurmRest", Kind: "structure",
							Fields: []Field{
								{Property: "Mode", Member: "mode", Kind: "scalar"},
							},
						},
						{Property: "SlurmdbdCustomSettings", Member: "slurmdbdCustomSettings", Kind: "list",
							Fields: []Field{
								{Property: "ParameterName", Member: "parameterName", Kind: "scalar"},
								{Property: "ParameterValue", Member: "parameterValue", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
	})
}
