// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::S3Vectors::VectorBucket": {
			Type:        "AWS::S3Vectors::VectorBucket",
			Protocol:    "restJson1",
			SigningName: "s3vectors",
			Host:        "s3vectors.{region}.api.aws",
			Method:      "POST",
			URI:         "/GetVectorBucket",
			Identifier: []Binding{
				{Property: "VectorBucketArn", Member: "vectorBucketArn", Location: "body"},
			},
			Response: []Step{{Name: "vectorBucket"}},
			Fields: []Field{
				{Property: "CreationTime", Member: "creationTime", Kind: "timestamp"},
				{Property: "EncryptionConfiguration", Member: "encryptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyArn", Member: "kmsKeyArn", Kind: "scalar"},
						{Property: "SseType", Member: "sseType", Kind: "scalar"},
					},
				},
				{Property: "VectorBucketArn", Member: "vectorBucketArn", Kind: "scalar"},
				{Property: "VectorBucketName", Member: "vectorBucketName", Kind: "scalar"},
			},
		},
	})
}
