// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::HealthAgent::Domain": {
			Type:        "AWS::HealthAgent::Domain",
			Protocol:    "restJson1",
			SigningName: "health-agent",
			Host:        "health-agent.{region}.api.aws",
			Method:      "GET",
			URI:         "/domain/{domainId}",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "domainId", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "DomainId", Member: "domainId", Kind: "scalar"},
				{Property: "EncryptionContext", Member: "encryptionContext", Kind: "structure",
					Fields: []Field{
						{Property: "EncryptionType", Member: "encryptionType", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
	})
}
