// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SecurityHub::AggregatorV2": {
			Type:        "AWS::SecurityHub::AggregatorV2",
			Protocol:    "restJson1",
			SigningName: "securityhub",
			Host:        "securityhub.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/aggregatorv2/get/{AggregatorV2Arn+}",
			Identifier: []Binding{
				{Property: "AggregatorV2Arn", Member: "AggregatorV2Arn", Location: "label"},
			},
			Fields: []Field{
				{Property: "AggregationRegion", Member: "AggregationRegion", Kind: "scalar"},
				{Property: "AggregatorV2Arn", Member: "AggregatorV2Arn", Kind: "scalar"},
				{Property: "LinkedRegions", Member: "LinkedRegions", Kind: "list"},
				{Property: "RegionLinkingMode", Member: "RegionLinkingMode", Kind: "scalar"},
			},
		},
		"AWS::SecurityHub::FindingAggregator": {
			Type:        "AWS::SecurityHub::FindingAggregator",
			Protocol:    "restJson1",
			SigningName: "securityhub",
			Complete:    true,
			Host:        "securityhub.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/findingAggregator/get/{FindingAggregatorArn+}",
			Identifier: []Binding{
				{Property: "FindingAggregatorArn", Member: "FindingAggregatorArn", Location: "label"},
			},
			Fields: []Field{
				{Property: "FindingAggregationRegion", Member: "FindingAggregationRegion", Kind: "scalar"},
				{Property: "FindingAggregatorArn", Member: "FindingAggregatorArn", Kind: "scalar"},
				{Property: "RegionLinkingMode", Member: "RegionLinkingMode", Kind: "scalar"},
				{Property: "Regions", Member: "Regions", Kind: "list"},
			},
		},
	})
}
