// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ImageBuilder::LifecyclePolicy": {
			Type:        "AWS::ImageBuilder::LifecyclePolicy",
			Protocol:    "restJson1",
			SigningName: "imagebuilder",
			Complete:    true,
			Host:        "imagebuilder.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/GetLifecyclePolicy",
			Identifier: []Binding{
				{Property: "Arn", Member: "lifecyclePolicyArn", Location: "query", Name: "lifecyclePolicyArn"},
			},
			Response: []Step{{Name: "lifecyclePolicy"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "ExecutionRole", Member: "executionRole", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "PolicyDetails", Member: "policyDetails", Kind: "list",
					Fields: []Field{
						{Property: "Action", Member: "action", Kind: "structure",
							Fields: []Field{
								{Property: "IncludeResources", Member: "includeResources", Kind: "structure",
									Fields: []Field{
										{Property: "Amis", Member: "amis", Kind: "scalar"},
										{Property: "Containers", Member: "containers", Kind: "scalar"},
										{Property: "Snapshots", Member: "snapshots", Kind: "scalar"},
									},
								},
								{Property: "Type", Member: "type", Kind: "scalar"},
							},
						},
						{Property: "ExclusionRules", Member: "exclusionRules", Kind: "structure",
							Fields: []Field{
								{Property: "Amis", Member: "amis", Kind: "structure",
									Fields: []Field{
										{Property: "IsPublic", Member: "isPublic", Kind: "scalar"},
										{Property: "LastLaunched", Member: "lastLaunched", Kind: "structure",
											Fields: []Field{
												{Property: "Unit", Member: "unit", Kind: "scalar"},
												{Property: "Value", Member: "value", Kind: "scalar"},
											},
										},
										{Property: "Regions", Member: "regions", Kind: "list"},
										{Property: "SharedAccounts", Member: "sharedAccounts", Kind: "list"},
										{Property: "TagMap", Member: "tagMap", Kind: "map"},
									},
								},
								{Property: "TagMap", Member: "tagMap", Kind: "map"},
							},
						},
						{Property: "Filter", Member: "filter", Kind: "structure",
							Fields: []Field{
								{Property: "RetainAtLeast", Member: "retainAtLeast", Kind: "scalar"},
								{Property: "Type", Member: "type", Kind: "scalar"},
								{Property: "Unit", Member: "unit", Kind: "scalar"},
								{Property: "Value", Member: "value", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "ResourceSelection", Member: "resourceSelection", Kind: "structure",
					Fields: []Field{
						{Property: "Recipes", Member: "recipes", Kind: "list",
							Fields: []Field{
								{Property: "Name", Member: "name", Kind: "scalar"},
								{Property: "SemanticVersion", Member: "semanticVersion", Kind: "scalar"},
							},
						},
						{Property: "TagMap", Member: "tagMap", Kind: "map"},
					},
				},
				{Property: "ResourceType", Member: "resourceType", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "Tags", Member: "tags", Kind: "map"},
			},
		},
	})
}
