// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

var readers = map[string]Reader{
	"AWS::AppConfig::DeploymentStrategy": {
		Type:           "AWS::AppConfig::DeploymentStrategy",
		Protocol:       "restJson1",
		SigningName:    "appconfig",
		EndpointPrefix: "appconfig",
		Method:         "GET",
		URI:            "/deploymentstrategies/{DeploymentStrategyId}",
		Identifier: []Binding{
			{Property: "Id", Member: "DeploymentStrategyId", Location: "label"},
		},
		Fields: []Field{
			{Property: "DeploymentDurationInMinutes", Member: "DeploymentDurationInMinutes", Kind: "scalar"},
			{Property: "Description", Member: "Description", Kind: "scalar"},
			{Property: "FinalBakeTimeInMinutes", Member: "FinalBakeTimeInMinutes", Kind: "scalar"},
			{Property: "GrowthFactor", Member: "GrowthFactor", Kind: "scalar"},
			{Property: "GrowthType", Member: "GrowthType", Kind: "scalar"},
			{Property: "Id", Member: "Id", Kind: "scalar"},
			{Property: "Name", Member: "Name", Kind: "scalar"},
			{Property: "ReplicateTo", Member: "ReplicateTo", Kind: "scalar"},
		},
	},
	"AWS::AppRunner::AutoScalingConfiguration": {
		Type:           "AWS::AppRunner::AutoScalingConfiguration",
		Protocol:       "awsJson1_0",
		SigningName:    "apprunner",
		EndpointPrefix: "apprunner",
		Target:         "AppRunner.DescribeAutoScalingConfiguration",
		Identifier: []Binding{
			{Property: "AutoScalingConfigurationArn", Member: "AutoScalingConfigurationArn", Location: "body"},
		},
		Response: []string{"AutoScalingConfiguration"},
		Fields: []Field{
			{Property: "AutoScalingConfigurationArn", Member: "AutoScalingConfigurationArn", Kind: "scalar"},
			{Property: "AutoScalingConfigurationName", Member: "AutoScalingConfigurationName", Kind: "scalar"},
			{Property: "AutoScalingConfigurationRevision", Member: "AutoScalingConfigurationRevision", Kind: "scalar"},
			{Property: "Latest", Member: "Latest", Kind: "scalar"},
			{Property: "MaxConcurrency", Member: "MaxConcurrency", Kind: "scalar"},
			{Property: "MaxSize", Member: "MaxSize", Kind: "scalar"},
			{Property: "MinSize", Member: "MinSize", Kind: "scalar"},
		},
	},
	"AWS::Bedrock::IntelligentPromptRouter": {
		Type:           "AWS::Bedrock::IntelligentPromptRouter",
		Protocol:       "restJson1",
		SigningName:    "bedrock",
		EndpointPrefix: "bedrock",
		Method:         "GET",
		URI:            "/prompt-routers/{promptRouterArn}",
		Identifier: []Binding{
			{Property: "PromptRouterArn", Member: "promptRouterArn", Location: "label"},
		},
		Fields: []Field{
			{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
			{Property: "Description", Member: "description", Kind: "scalar"},
			{Property: "FallbackModel", Member: "fallbackModel", Kind: "structure",
				Fields: []Field{
					{Property: "ModelArn", Member: "modelArn", Kind: "scalar"},
				},
			},
			{Property: "Models", Member: "models", Kind: "list",
				Fields: []Field{
					{Property: "ModelArn", Member: "modelArn", Kind: "scalar"},
				},
			},
			{Property: "PromptRouterArn", Member: "promptRouterArn", Kind: "scalar"},
			{Property: "PromptRouterName", Member: "promptRouterName", Kind: "scalar"},
			{Property: "RoutingCriteria", Member: "routingCriteria", Kind: "structure",
				Fields: []Field{
					{Property: "ResponseQualityDifference", Member: "responseQualityDifference", Kind: "scalar"},
				},
			},
			{Property: "Status", Member: "status", Kind: "scalar"},
			{Property: "Type", Member: "type", Kind: "scalar"},
			{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
		},
	},
	"AWS::CodeDeploy::DeploymentConfig": {
		Type:           "AWS::CodeDeploy::DeploymentConfig",
		Protocol:       "awsJson1_1",
		SigningName:    "codedeploy",
		EndpointPrefix: "codedeploy",
		Target:         "CodeDeploy_20141006.GetDeploymentConfig",
		Identifier: []Binding{
			{Property: "DeploymentConfigName", Member: "deploymentConfigName", Location: "body"},
		},
		Response: []string{"deploymentConfigInfo"},
		Fields: []Field{
			{Property: "ComputePlatform", Member: "computePlatform", Kind: "scalar"},
			{Property: "DeploymentConfigName", Member: "deploymentConfigName", Kind: "scalar"},
			{Property: "MinimumHealthyHosts", Member: "minimumHealthyHosts", Kind: "structure",
				Fields: []Field{
					{Property: "Type", Member: "type", Kind: "scalar"},
					{Property: "Value", Member: "value", Kind: "scalar"},
				},
			},
			{Property: "TrafficRoutingConfig", Member: "trafficRoutingConfig", Kind: "structure",
				Fields: []Field{
					{Property: "TimeBasedCanary", Member: "timeBasedCanary", Kind: "structure",
						Fields: []Field{
							{Property: "CanaryInterval", Member: "canaryInterval", Kind: "scalar"},
							{Property: "CanaryPercentage", Member: "canaryPercentage", Kind: "scalar"},
						},
					},
					{Property: "TimeBasedLinear", Member: "timeBasedLinear", Kind: "structure",
						Fields: []Field{
							{Property: "LinearInterval", Member: "linearInterval", Kind: "scalar"},
							{Property: "LinearPercentage", Member: "linearPercentage", Kind: "scalar"},
						},
					},
					{Property: "Type", Member: "type", Kind: "scalar"},
				},
			},
			{Property: "ZonalConfig", Member: "zonalConfig", Kind: "structure",
				Fields: []Field{
					{Property: "FirstZoneMonitorDurationInSeconds", Member: "firstZoneMonitorDurationInSeconds", Kind: "scalar"},
					{Property: "MinimumHealthyHostsPerZone", Member: "minimumHealthyHostsPerZone", Kind: "structure",
						Fields: []Field{
							{Property: "Type", Member: "type", Kind: "scalar"},
							{Property: "Value", Member: "value", Kind: "scalar"},
						},
					},
					{Property: "MonitorDurationInSeconds", Member: "monitorDurationInSeconds", Kind: "scalar"},
				},
			},
		},
	},
	"AWS::XRay::Group": {
		Type:           "AWS::XRay::Group",
		Protocol:       "restJson1",
		SigningName:    "xray",
		EndpointPrefix: "xray",
		Method:         "POST",
		URI:            "/GetGroup",
		Identifier: []Binding{
			{Property: "GroupARN", Member: "GroupARN", Location: "body"},
		},
		Response: []string{"Group"},
		Fields: []Field{
			{Property: "FilterExpression", Member: "FilterExpression", Kind: "scalar"},
			{Property: "GroupARN", Member: "GroupARN", Kind: "scalar"},
			{Property: "GroupName", Member: "GroupName", Kind: "scalar"},
			{Property: "InsightsConfiguration", Member: "InsightsConfiguration", Kind: "structure",
				Fields: []Field{
					{Property: "InsightsEnabled", Member: "InsightsEnabled", Kind: "scalar"},
					{Property: "NotificationsEnabled", Member: "NotificationsEnabled", Kind: "scalar"},
				},
			},
		},
	},
}
