// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ServiceDiscovery::HttpNamespace": {
			Type:        "AWS::ServiceDiscovery::HttpNamespace",
			Protocol:    "awsJson1_1",
			SigningName: "servicediscovery",
			Host:        "servicediscovery.{region}.amazonaws.com",
			Target:      "Route53AutoNaming_v20170314.GetNamespace",
			Identifier: []Binding{
				{Property: "Id", Member: "Id", Location: "body"},
			},
			Response: []Step{{Name: "Namespace"}},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
			},
		},
	})
}
