// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::DynamoDB::Table": {
			Type:        "AWS::DynamoDB::Table",
			Protocol:    "awsJson1_0",
			SigningName: "dynamodb",
			Complete:    true,
			Host:        "dynamodb.{region}.amazonaws.com",
			Target:      "DynamoDB_20120810.DescribeTable",
			Identifier: []Binding{
				{Property: "TableName", Member: "TableName", Location: "body"},
			},
			Busy: []Condition{
				{Field: Field{Property: "GlobalSecondaryIndexes[].IndexStatus", Member: "IndexStatus", Kind: "scalar", Via: []Step{{Name: "GlobalSecondaryIndexes", List: true}}}, Values: []string{"CREATING", "UPDATING", "DELETING"}},
				{Field: Field{Property: "TableStatus", Member: "TableStatus", Kind: "scalar"}, Values: []string{"CREATING", "UPDATING", "DELETING", "ARCHIVING"}},
				{Field: Field{Property: "VectorIndexes[].IndexStatus", Member: "IndexStatus", Kind: "scalar", Via: []Step{{Name: "VectorIndexes", List: true}}}, Values: []string{"CREATING", "UPDATING", "DELETING"}},
			},
			Wait:         1200000000000,
			AbsentErrors: []string{"ResourceNotFoundException"},
			Response:     []Step{{Name: "Table"}},
			Fields: []Field{
				{Property: "Arn", Member: "TableArn", Kind: "scalar"},
				{Property: "AttributeDefinitions", Member: "AttributeDefinitions", Kind: "list",
					Fields: []Field{
						{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
						{Property: "AttributeType", Member: "AttributeType", Kind: "scalar"},
					},
				},
				{Property: "BillingMode", Member: "BillingMode", Kind: "scalar", Via: []Step{{Name: "BillingModeSummary"}}, Default: "PROVISIONED"},
				{Property: "DeletionProtectionEnabled", Member: "DeletionProtectionEnabled", Kind: "scalar"},
				{Property: "GlobalSecondaryIndexes", Member: "GlobalSecondaryIndexes", Kind: "list",
					Fields: []Field{
						{Property: "IndexName", Member: "IndexName", Kind: "scalar"},
						{Property: "KeySchema", Member: "KeySchema", Kind: "list",
							Fields: []Field{
								{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
								{Property: "KeyType", Member: "KeyType", Kind: "scalar"},
							},
						},
						{Property: "OnDemandThroughput", Member: "OnDemandThroughput", Kind: "structure",
							Fields: []Field{
								{Property: "MaxReadRequestUnits", Member: "MaxReadRequestUnits", Kind: "scalar"},
								{Property: "MaxWriteRequestUnits", Member: "MaxWriteRequestUnits", Kind: "scalar"},
							},
						},
						{Property: "Projection", Member: "Projection", Kind: "structure",
							Fields: []Field{
								{Property: "NonKeyAttributes", Member: "NonKeyAttributes", Kind: "list"},
								{Property: "ProjectionType", Member: "ProjectionType", Kind: "scalar"},
							},
						},
						{Property: "ProvisionedThroughput", Member: "ProvisionedThroughput", Kind: "structure", Unless: []Condition{{Field: Field{Property: "BillingMode"}, Values: []string{"PAY_PER_REQUEST"}}},
							Fields: []Field{
								{Property: "ReadCapacityUnits", Member: "ReadCapacityUnits", Kind: "scalar"},
								{Property: "WriteCapacityUnits", Member: "WriteCapacityUnits", Kind: "scalar"},
							},
						},
						{Property: "WarmThroughput", Member: "WarmThroughput", Kind: "structure",
							Fields: []Field{
								{Property: "ReadUnitsPerSecond", Member: "ReadUnitsPerSecond", Kind: "scalar"},
								{Property: "WriteUnitsPerSecond", Member: "WriteUnitsPerSecond", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "KeySchema", Member: "KeySchema", Kind: "list",
					Fields: []Field{
						{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
						{Property: "KeyType", Member: "KeyType", Kind: "scalar"},
					},
				},
				{Property: "LocalSecondaryIndexes", Member: "LocalSecondaryIndexes", Kind: "list",
					Fields: []Field{
						{Property: "IndexName", Member: "IndexName", Kind: "scalar"},
						{Property: "KeySchema", Member: "KeySchema", Kind: "list",
							Fields: []Field{
								{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
								{Property: "KeyType", Member: "KeyType", Kind: "scalar"},
							},
						},
						{Property: "Projection", Member: "Projection", Kind: "structure",
							Fields: []Field{
								{Property: "NonKeyAttributes", Member: "NonKeyAttributes", Kind: "list"},
								{Property: "ProjectionType", Member: "ProjectionType", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "OnDemandThroughput", Member: "OnDemandThroughput", Kind: "structure",
					Fields: []Field{
						{Property: "MaxReadRequestUnits", Member: "MaxReadRequestUnits", Kind: "scalar"},
						{Property: "MaxWriteRequestUnits", Member: "MaxWriteRequestUnits", Kind: "scalar"},
					},
				},
				{Property: "ProvisionedThroughput", Member: "ProvisionedThroughput", Kind: "structure", Unless: []Condition{{Field: Field{Property: "BillingMode"}, Values: []string{"PAY_PER_REQUEST"}}},
					Fields: []Field{
						{Property: "ReadCapacityUnits", Member: "ReadCapacityUnits", Kind: "scalar"},
						{Property: "WriteCapacityUnits", Member: "WriteCapacityUnits", Kind: "scalar"},
					},
				},
				{Property: "SSESpecification", Member: "SSEDescription", Kind: "structure", Default: map[string]any{"SSEEnabled": false},
					Fields: []Field{
						{Property: "KMSMasterKeyId", Member: "KMSMasterKeyArn", Kind: "scalar"},
						{Property: "SSEEnabled", Member: "Status", Kind: "scalar", TrueWhen: []string{"ENABLED", "UPDATING"}},
						{Property: "SSEType", Member: "SSEType", Kind: "scalar"},
					},
				},
				{Property: "StreamArn", Member: "LatestStreamArn", Kind: "scalar"},
				{Property: "StreamSpecification", Member: "StreamSpecification", Kind: "structure",
					Fields: []Field{
						{Property: "StreamViewType", Member: "StreamViewType", Kind: "scalar"},
					},
				},
				{Property: "TableClass", Member: "TableClass", Kind: "scalar", Via: []Step{{Name: "TableClassSummary"}}},
				{Property: "TableName", Member: "TableName", Kind: "scalar"},
				{Property: "VectorIndexes", Member: "VectorIndexes", Kind: "list",
					Fields: []Field{
						{Property: "Dimensions", Member: "Dimensions", Kind: "scalar"},
						{Property: "DistanceFunction", Member: "DistanceFunction", Kind: "scalar"},
						{Property: "IndexName", Member: "IndexName", Kind: "scalar"},
						{Property: "Projection", Member: "Projection", Kind: "structure",
							Fields: []Field{
								{Property: "NonKeyAttributes", Member: "NonKeyAttributes", Kind: "list"},
								{Property: "ProjectionType", Member: "ProjectionType", Kind: "scalar"},
							},
						},
						{Property: "SearchSchema", Member: "SearchSchema", Kind: "list",
							Fields: []Field{
								{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
								{Property: "SearchSchemaElementType", Member: "SearchSchemaElementType", Kind: "scalar"},
							},
						},
						{Property: "VectorAttribute", Member: "VectorAttribute", Kind: "structure",
							Fields: []Field{
								{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "WarmThroughput", Member: "WarmThroughput", Kind: "structure",
					Fields: []Field{
						{Property: "ReadUnitsPerSecond", Member: "ReadUnitsPerSecond", Kind: "scalar"},
						{Property: "WriteUnitsPerSecond", Member: "WriteUnitsPerSecond", Kind: "scalar"},
					},
				},
			},
			AbsentIDs: []string{"kraai-absent-probe-table"},
			Capture: []Field{
				{Property: "Arn", Member: "TableArn", Kind: "scalar"},
				{Property: "StreamArn", Member: "LatestStreamArn", Kind: "scalar"},
			},
			CreateOnly:       []string{"/properties/KeySchema", "/properties/LocalSecondaryIndexes"},
			Unsupported:      map[string]string{"ContributorInsightsSpecification": "no call sets it yet; UpdateContributorInsights takes an enum, not a boolean", "ImportSourceSpecification": "CreateTable has no member for it; a table is imported with ImportTable", "KinesisStreamSpecification": "enabling a destination is a separate call pair with no route yet", "StreamSpecification.ResourcePolicy": "a stream's policy is put by the stream's ARN, which no call here writes", "StreamSpecification.Tags": "a stream is tagged by its ARN, which no call here writes"},
			WriteOnly:        []string{"ImportSourceSpecification"},
			MutationCaptures: true,
			Create:           &MutationCall{Operation: "CreateTable", Target: "DynamoDB_20120810.CreateTable", NameProperty: "TableName", NameTag: "kraai:resource-name", NameMaxLength: 255, Input: map[string]any{"AttributeDefinitions": "{AttributeDefinitions}", "BillingMode": "{BillingMode}", "DeletionProtectionEnabled": "{DeletionProtectionEnabled}", "GlobalSecondaryIndexes": "{GlobalSecondaryIndexes}", "KeySchema": "{KeySchema}", "LocalSecondaryIndexes": "{LocalSecondaryIndexes}", "OnDemandThroughput": "{OnDemandThroughput}", "ProvisionedThroughput": "{ProvisionedThroughput}", "ResourcePolicy": "{ResourcePolicy.PolicyDocument:json}", "SSESpecification": map[string]any{"Enabled": "{SSESpecification.SSEEnabled}", "KMSMasterKeyId": "{SSESpecification.KMSMasterKeyId}", "SSEType": "{SSESpecification.SSEType}"}, "StreamSpecification": map[string]any{"StreamEnabled": true, "StreamViewType": "{StreamSpecification.StreamViewType}"}, "TableClass": "{TableClass}", "TableName": "{TableName}", "Tags": "{Tags}", "VectorIndexes": "{VectorIndexes}", "WarmThroughput": "{WarmThroughput}"}, Properties: []string{"AttributeDefinitions", "BillingMode", "DeletionProtectionEnabled", "GlobalSecondaryIndexes", "KeySchema", "LocalSecondaryIndexes", "OnDemandThroughput", "ProvisionedThroughput", "ResourcePolicy", "SSESpecification", "StreamSpecification", "TableClass", "TableName", "Tags", "VectorIndexes", "WarmThroughput"}, Identifier: map[string]string{"TableName": "TableDescription.TableName"}},
			Delete:           &MutationCall{Operation: "DeleteTable", Target: "DynamoDB_20120810.DeleteTable", Input: map[string]any{"TableName": "{TableName}"}, AbsentErrors: []string{"ResourceNotFoundException"}, RetryErrors: []string{"ResourceInUseException"}},
			Update: []MutationCall{
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"BillingMode": "{BillingMode}", "OnDemandThroughput": "{OnDemandThroughput}", "ProvisionedThroughput": "{ProvisionedThroughput}", "TableName": "{TableName}"}, Properties: []string{"BillingMode", "ProvisionedThroughput", "OnDemandThroughput"}},
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"SSESpecification": map[string]any{"Enabled": "{SSESpecification.SSEEnabled}", "KMSMasterKeyId": "{SSESpecification.KMSMasterKeyId}", "SSEType": "{SSESpecification.SSEType}"}, "TableName": "{TableName}"}, Properties: []string{"SSESpecification"}},
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"StreamSpecification": map[string]any{"StreamEnabled": true, "StreamViewType": "{StreamSpecification.StreamViewType}"}, "TableName": "{TableName}"}, Properties: []string{"StreamSpecification"}},
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"TableClass": "{TableClass}", "TableName": "{TableName}"}, Properties: []string{"TableClass"}},
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"DeletionProtectionEnabled": "{DeletionProtectionEnabled}", "TableName": "{TableName}"}, Properties: []string{"DeletionProtectionEnabled"}},
				MutationCall{Operation: "UpdateTable", Target: "DynamoDB_20120810.UpdateTable", Input: map[string]any{"TableName": "{TableName}", "WarmThroughput": "{WarmThroughput}"}, Properties: []string{"WarmThroughput"}},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "TagResource", Target: "DynamoDB_20120810.TagResource", TagProperty: "Tags", Input: map[string]any{"ResourceArn": "{Arn}", "Tags": "{added}"}}, Remove: &MutationCall{Operation: "UntagResource", Target: "DynamoDB_20120810.UntagResource", Input: map[string]any{"ResourceArn": "{Arn}", "TagKeys": "{removed}"}}},
				MutationCall{Operation: "PutResourcePolicy", Target: "DynamoDB_20120810.PutResourcePolicy", Input: map[string]any{"Policy": "{ResourcePolicy.PolicyDocument:json}", "ResourceArn": "{Arn}"}, Properties: []string{"ResourcePolicy"}},
				MutationCall{Operation: "UpdateContinuousBackups", Target: "DynamoDB_20120810.UpdateContinuousBackups", Input: map[string]any{"PointInTimeRecoverySpecification": "{PointInTimeRecoverySpecification}", "TableName": "{TableName}"}, RetryErrors: []string{"ContinuousBackupsUnavailableException"}, Properties: []string{"PointInTimeRecoverySpecification"}},
				MutationCall{Operation: "UpdateTimeToLive", Target: "DynamoDB_20120810.UpdateTimeToLive", Input: map[string]any{"TableName": "{TableName}", "TimeToLiveSpecification": "{TimeToLiveSpecification}"}, Properties: []string{"TimeToLiveSpecification"}},
			},
			Also: []Reader{
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.DescribeContinuousBackups",
					Identifier: []Binding{
						{Property: "TableName", Member: "TableName", Location: "body"},
					},
					Fields: []Field{
						{Property: "PointInTimeRecoverySpecification", Member: "PointInTimeRecoveryDescription", Kind: "structure", Via: []Step{{Name: "ContinuousBackupsDescription"}},
							Fields: []Field{
								{Property: "PointInTimeRecoveryEnabled", Member: "PointInTimeRecoveryStatus", Kind: "scalar", TrueWhen: []string{"ENABLED"}},
								{Property: "RecoveryPeriodInDays", Member: "RecoveryPeriodInDays", Kind: "scalar"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.DescribeTimeToLive",
					Identifier: []Binding{
						{Property: "TableName", Member: "TableName", Location: "body"},
					},
					Fields: []Field{
						{Property: "TimeToLiveSpecification", Member: "TimeToLiveDescription", Kind: "structure",
							Fields: []Field{
								{Property: "AttributeName", Member: "AttributeName", Kind: "scalar"},
								{Property: "Enabled", Member: "TimeToLiveStatus", Kind: "scalar", TrueWhen: []string{"ENABLED", "ENABLING"}},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.DescribeContributorInsights",
					Identifier: []Binding{
						{Property: "TableName", Member: "TableName", Location: "body"},
					},
					Fields: []Field{
						{Property: "ContributorInsightsSpecification", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "Enabled", Member: "ContributorInsightsStatus", Kind: "scalar", TrueWhen: []string{"ENABLED", "ENABLING"}},
								{Property: "Mode", Member: "ContributorInsightsMode", Kind: "scalar"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.DescribeContributorInsights",
					Identifier: []Binding{
						{Property: "TableName", Member: "TableName", Location: "body"},
					},
					Input: []Binding{
						Binding{Location: "body", Member: "IndexName", Value: "{IndexName}"},
					},
					Each: "GlobalSecondaryIndexes",
					Fields: []Field{
						{Property: "ContributorInsightsSpecification", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "Enabled", Member: "ContributorInsightsStatus", Kind: "scalar", TrueWhen: []string{"ENABLED", "ENABLING"}},
								{Property: "Mode", Member: "ContributorInsightsMode", Kind: "scalar"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.DescribeKinesisStreamingDestination",
					Identifier: []Binding{
						{Property: "TableName", Member: "TableName", Location: "body"},
					},
					Fields: []Field{
						{Property: "KinesisStreamSpecification", Member: ".", Kind: "structure", Via: []Step{{Name: "KinesisDataStreamDestinations", List: true, Where: "DestinationStatus", Equals: "ACTIVE"}},
							Fields: []Field{
								{Property: "ApproximateCreationDateTimePrecision", Member: "ApproximateCreationDateTimePrecision", Kind: "scalar"},
								{Property: "StreamArn", Member: "StreamArn", Kind: "scalar"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.ListTagsOfResource",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceArn", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.GetResourcePolicy",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceArn", Value: "{Arn}"},
					},
					AbsentErrors: []string{"PolicyNotFoundException"},
					Fields: []Field{
						{Property: "ResourcePolicy", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "PolicyDocument", Member: "Policy", Kind: "scalar", Transform: "json"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.GetResourcePolicy",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceArn", Value: "{StreamArn}"},
					},
					AbsentErrors: []string{"PolicyNotFoundException"},
					Each:         "StreamSpecification",
					Fields: []Field{
						{Property: "ResourcePolicy", Member: ".", Kind: "structure",
							Fields: []Field{
								{Property: "PolicyDocument", Member: "Policy", Kind: "scalar", Transform: "json"},
							},
						},
					},
				},
				{
					Type:        "AWS::DynamoDB::Table",
					Protocol:    "awsJson1_0",
					SigningName: "dynamodb",
					Host:        "dynamodb.{region}.amazonaws.com",
					Target:      "DynamoDB_20120810.ListTagsOfResource",
					Input: []Binding{
						Binding{Location: "body", Member: "ResourceArn", Value: "{StreamArn}"},
					},
					Each: "StreamSpecification",
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "list",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
	})
}
