// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::NovaAct::WorkflowDefinition": {
			Type:        "AWS::NovaAct::WorkflowDefinition",
			Protocol:    "restJson1",
			SigningName: "nova-act",
			Complete:    true,
			Host:        "nova-act.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/workflow-definitions/{workflowDefinitionName}",
			Identifier: []Binding{
				{Property: "Arn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "workflowDefinitionName", Value: "{Arn:arnName}"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "ExportConfig", Member: "exportConfig", Kind: "structure",
					Fields: []Field{
						{Property: "S3BucketName", Member: "s3BucketName", Kind: "scalar"},
						{Property: "S3KeyPrefix", Member: "s3KeyPrefix", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
			},
		},
	})
}
