// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Pinpoint::InAppTemplate": {
			Type:        "AWS::Pinpoint::InAppTemplate",
			Protocol:    "restJson1",
			SigningName: "mobiletargeting",
			Complete:    true,
			Host:        "pinpoint.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/templates/{TemplateName}/inapp",
			Identifier: []Binding{
				{Property: "TemplateName", Member: "TemplateName", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Content", Member: "Content", Kind: "list",
					Fields: []Field{
						{Property: "BackgroundColor", Member: "BackgroundColor", Kind: "scalar"},
						{Property: "BodyConfig", Member: "BodyConfig", Kind: "structure",
							Fields: []Field{
								{Property: "Alignment", Member: "Alignment", Kind: "scalar"},
								{Property: "Body", Member: "Body", Kind: "scalar"},
								{Property: "TextColor", Member: "TextColor", Kind: "scalar"},
							},
						},
						{Property: "HeaderConfig", Member: "HeaderConfig", Kind: "structure",
							Fields: []Field{
								{Property: "Alignment", Member: "Alignment", Kind: "scalar"},
								{Property: "Header", Member: "Header", Kind: "scalar"},
								{Property: "TextColor", Member: "TextColor", Kind: "scalar"},
							},
						},
						{Property: "ImageUrl", Member: "ImageUrl", Kind: "scalar"},
						{Property: "PrimaryBtn", Member: "PrimaryBtn", Kind: "structure",
							Fields: []Field{
								{Property: "Android", Member: "Android", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
								{Property: "DefaultConfig", Member: "DefaultConfig", Kind: "structure",
									Fields: []Field{
										{Property: "BackgroundColor", Member: "BackgroundColor", Kind: "scalar"},
										{Property: "BorderRadius", Member: "BorderRadius", Kind: "scalar"},
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
										{Property: "Text", Member: "Text", Kind: "scalar"},
										{Property: "TextColor", Member: "TextColor", Kind: "scalar"},
									},
								},
								{Property: "IOS", Member: "IOS", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
								{Property: "Web", Member: "Web", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "SecondaryBtn", Member: "SecondaryBtn", Kind: "structure",
							Fields: []Field{
								{Property: "Android", Member: "Android", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
								{Property: "DefaultConfig", Member: "DefaultConfig", Kind: "structure",
									Fields: []Field{
										{Property: "BackgroundColor", Member: "BackgroundColor", Kind: "scalar"},
										{Property: "BorderRadius", Member: "BorderRadius", Kind: "scalar"},
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
										{Property: "Text", Member: "Text", Kind: "scalar"},
										{Property: "TextColor", Member: "TextColor", Kind: "scalar"},
									},
								},
								{Property: "IOS", Member: "IOS", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
								{Property: "Web", Member: "Web", Kind: "structure",
									Fields: []Field{
										{Property: "ButtonAction", Member: "ButtonAction", Kind: "scalar"},
										{Property: "Link", Member: "Link", Kind: "scalar"},
									},
								},
							},
						},
					},
				},
				{Property: "CustomConfig", Member: "CustomConfig", Kind: "map"},
				{Property: "Layout", Member: "Layout", Kind: "scalar"},
				{Property: "Tags", Member: "tags", Kind: "map", JSONName: "tags"},
				{Property: "TemplateDescription", Member: "TemplateDescription", Kind: "scalar"},
				{Property: "TemplateName", Member: "TemplateName", Kind: "scalar"},
			},
		},
	})
}
