// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::MediaConnect::Bridge": {
			Type:        "AWS::MediaConnect::Bridge",
			Protocol:    "restJson1",
			SigningName: "mediaconnect",
			Complete:    true,
			Host:        "mediaconnect.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/bridges/{BridgeArn}",
			Identifier: []Binding{
				{Property: "BridgeArn", Member: "BridgeArn", Location: "label"},
			},
			Response: []Step{{Name: "bridge"}},
			Fields: []Field{
				{Property: "BridgeArn", Member: "BridgeArn", Kind: "scalar", JSONName: "bridgeArn"},
				{Property: "BridgeState", Member: "BridgeState", Kind: "scalar", JSONName: "bridgeState"},
				{Property: "EgressGatewayBridge", Member: "EgressGatewayBridge", Kind: "structure", JSONName: "egressGatewayBridge",
					Fields: []Field{
						{Property: "MaxBitrate", Member: "MaxBitrate", Kind: "scalar", JSONName: "maxBitrate"},
					},
				},
				{Property: "IngressGatewayBridge", Member: "IngressGatewayBridge", Kind: "structure", JSONName: "ingressGatewayBridge",
					Fields: []Field{
						{Property: "MaxBitrate", Member: "MaxBitrate", Kind: "scalar", JSONName: "maxBitrate"},
						{Property: "MaxOutputs", Member: "MaxOutputs", Kind: "scalar", JSONName: "maxOutputs"},
					},
				},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "Outputs", Member: "Outputs", Kind: "list", JSONName: "outputs",
					Fields: []Field{
						{Property: "NetworkOutput", Member: "NetworkOutput", Kind: "structure", JSONName: "networkOutput",
							Fields: []Field{
								{Property: "IpAddress", Member: "IpAddress", Kind: "scalar", JSONName: "ipAddress"},
								{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
								{Property: "NetworkName", Member: "NetworkName", Kind: "scalar", JSONName: "networkName"},
								{Property: "Port", Member: "Port", Kind: "scalar", JSONName: "port"},
								{Property: "Protocol", Member: "Protocol", Kind: "scalar", JSONName: "protocol"},
								{Property: "Ttl", Member: "Ttl", Kind: "scalar", JSONName: "ttl"},
							},
						},
					},
				},
				{Property: "PlacementArn", Member: "PlacementArn", Kind: "scalar", JSONName: "placementArn"},
				{Property: "SourceFailoverConfig", Member: "SourceFailoverConfig", Kind: "structure", JSONName: "sourceFailoverConfig",
					Fields: []Field{
						{Property: "FailoverMode", Member: "FailoverMode", Kind: "scalar", JSONName: "failoverMode"},
						{Property: "SourcePriority", Member: "SourcePriority", Kind: "structure", JSONName: "sourcePriority",
							Fields: []Field{
								{Property: "PrimarySource", Member: "PrimarySource", Kind: "scalar", JSONName: "primarySource"},
							},
						},
						{Property: "State", Member: "State", Kind: "scalar", JSONName: "state"},
					},
				},
				{Property: "Sources", Member: "Sources", Kind: "list", JSONName: "sources",
					Fields: []Field{
						{Property: "FlowSource", Member: "FlowSource", Kind: "structure", JSONName: "flowSource",
							Fields: []Field{
								{Property: "FlowArn", Member: "FlowArn", Kind: "scalar", JSONName: "flowArn"},
								{Property: "FlowVpcInterfaceAttachment", Member: "FlowVpcInterfaceAttachment", Kind: "structure", JSONName: "flowVpcInterfaceAttachment",
									Fields: []Field{
										{Property: "VpcInterfaceName", Member: "VpcInterfaceName", Kind: "scalar", JSONName: "vpcInterfaceName"},
									},
								},
								{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
							},
						},
						{Property: "NetworkSource", Member: "NetworkSource", Kind: "structure", JSONName: "networkSource",
							Fields: []Field{
								{Property: "MulticastIp", Member: "MulticastIp", Kind: "scalar", JSONName: "multicastIp"},
								{Property: "MulticastSourceSettings", Member: "MulticastSourceSettings", Kind: "structure", JSONName: "multicastSourceSettings",
									Fields: []Field{
										{Property: "MulticastSourceIp", Member: "MulticastSourceIp", Kind: "scalar", JSONName: "multicastSourceIp"},
									},
								},
								{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
								{Property: "NetworkName", Member: "NetworkName", Kind: "scalar", JSONName: "networkName"},
								{Property: "Port", Member: "Port", Kind: "scalar", JSONName: "port"},
								{Property: "Protocol", Member: "Protocol", Kind: "scalar", JSONName: "protocol"},
							},
						},
					},
				},
			},
		},
		"AWS::MediaConnect::Gateway": {
			Type:        "AWS::MediaConnect::Gateway",
			Protocol:    "restJson1",
			SigningName: "mediaconnect",
			Complete:    true,
			Host:        "mediaconnect.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/gateways/{GatewayArn}",
			Identifier: []Binding{
				{Property: "GatewayArn", Member: "GatewayArn", Location: "label"},
			},
			Response: []Step{{Name: "gateway"}},
			Fields: []Field{
				{Property: "EgressCidrBlocks", Member: "EgressCidrBlocks", Kind: "list", JSONName: "egressCidrBlocks"},
				{Property: "GatewayArn", Member: "GatewayArn", Kind: "scalar", JSONName: "gatewayArn"},
				{Property: "GatewayState", Member: "GatewayState", Kind: "scalar", JSONName: "gatewayState"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "Networks", Member: "Networks", Kind: "list", JSONName: "networks",
					Fields: []Field{
						{Property: "CidrBlock", Member: "CidrBlock", Kind: "scalar", JSONName: "cidrBlock"},
						{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
					},
				},
			},
		},
	})
}
