// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ElastiCache::SubnetGroup": {
			Type:        "AWS::ElastiCache::SubnetGroup",
			Protocol:    "awsQuery",
			SigningName: "elasticache",
			Complete:    true,
			Production:  true,
			Host:        "elasticache.{region}.amazonaws.com",
			Action:      "DescribeCacheSubnetGroups",
			Version:     "2015-02-02",
			Wrapper:     "DescribeCacheSubnetGroupsResult",
			Identifier: []Binding{
				{Property: "CacheSubnetGroupName", Member: "CacheSubnetGroupName", Location: "form", Name: "CacheSubnetGroupName"},
			},
			AbsentErrors: []string{"CacheSubnetGroupNotFoundFault"},
			PageToken:    []string{"Marker"},
			Response:     []Step{{Name: "CacheSubnetGroups", List: true, Item: "CacheSubnetGroup"}},
			Fields: []Field{
				{Property: "CacheSubnetGroupName", Member: "CacheSubnetGroupName", Kind: "scalar", XMLName: "CacheSubnetGroupName", Scalar: "string"},
				{Property: "Description", Member: "CacheSubnetGroupDescription", Kind: "scalar", XMLName: "CacheSubnetGroupDescription", Scalar: "string"},
				{Property: "SubnetIds", Member: "SubnetIdentifier", Kind: "scalar", Via: []Step{{Name: "Subnets", List: true, Item: "Subnet"}}, XMLName: "SubnetIdentifier", Scalar: "string"},
			},
			AbsentIDs: []string{"kraai-absent-probe-subnetgroup"},
			Capture: []Field{
				{Property: "Arn", Member: "ARN", Kind: "scalar", XMLName: "ARN", Scalar: "string"},
			},
			LifecycleComplete: true,
			MutationCaptures:  true,
			Create:            &MutationCall{Operation: "CreateCacheSubnetGroup", Target: "AmazonElastiCacheV9.CreateCacheSubnetGroup", NameProperty: "CacheSubnetGroupName", NameTag: "kraai:resource-name", Input: map[string]any{"CacheSubnetGroupDescription": "{Description}", "CacheSubnetGroupName": "{CacheSubnetGroupName}", "SubnetIds": "{SubnetIds}", "Tags": "{Tags}"}, Properties: []string{"CacheSubnetGroupName", "Description", "SubnetIds", "Tags"}, Identifier: map[string]string{"CacheSubnetGroupName": "CreateCacheSubnetGroupResult.CacheSubnetGroup.CacheSubnetGroupName"}, Form: map[string]FormStep{"CacheSubnetGroupDescription": {Key: "CacheSubnetGroupDescription", Kind: "scalar"}, "CacheSubnetGroupName": {Key: "CacheSubnetGroupName", Kind: "scalar"}, "SubnetIds": {Key: "SubnetIds", Kind: "list", Item: "SubnetIdentifier"}, "SubnetIds[]": {Key: "", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "Tag"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}},
			Delete:            &MutationCall{Operation: "DeleteCacheSubnetGroup", Target: "AmazonElastiCacheV9.DeleteCacheSubnetGroup", Input: map[string]any{"CacheSubnetGroupName": "{CacheSubnetGroupName}"}, AbsentErrors: []string{"CacheSubnetGroupNotFoundFault"}, Form: map[string]FormStep{"CacheSubnetGroupName": {Key: "CacheSubnetGroupName", Kind: "scalar"}}},
			Update: []MutationCall{
				MutationCall{Operation: "ModifyCacheSubnetGroup", Target: "AmazonElastiCacheV9.ModifyCacheSubnetGroup", Input: map[string]any{"CacheSubnetGroupDescription": "{Description}", "CacheSubnetGroupName": "{CacheSubnetGroupName}", "SubnetIds": "{SubnetIds}"}, Properties: []string{"Description", "SubnetIds"}, Form: map[string]FormStep{"CacheSubnetGroupDescription": {Key: "CacheSubnetGroupDescription", Kind: "scalar"}, "CacheSubnetGroupName": {Key: "CacheSubnetGroupName", Kind: "scalar"}, "SubnetIds": {Key: "SubnetIds", Kind: "list", Item: "SubnetIdentifier"}, "SubnetIds[]": {Key: "", Kind: "scalar"}}, Together: true},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "AddTagsToResource", Target: "AmazonElastiCacheV9.AddTagsToResource", TagProperty: "Tags", Input: map[string]any{"ResourceName": "{Arn}", "Tags": "{added}"}, Form: map[string]FormStep{"ResourceName": {Key: "ResourceName", Kind: "scalar"}, "Tags": {Key: "Tags", Kind: "list", Item: "Tag"}, "Tags[]": {Key: "", Kind: "structure"}, "Tags[].Key": {Key: "Key", Kind: "scalar"}, "Tags[].Value": {Key: "Value", Kind: "scalar"}}}, Remove: &MutationCall{Operation: "RemoveTagsFromResource", Target: "AmazonElastiCacheV9.RemoveTagsFromResource", Input: map[string]any{"ResourceName": "{Arn}", "TagKeys": "{removed}"}, Form: map[string]FormStep{"ResourceName": {Key: "ResourceName", Kind: "scalar"}, "TagKeys": {Key: "TagKeys", Kind: "list", Item: "member"}, "TagKeys[]": {Key: "", Kind: "scalar"}}}},
			},
			Also: []Reader{
				{
					Type:        "AWS::ElastiCache::SubnetGroup",
					Protocol:    "awsQuery",
					SigningName: "elasticache",
					Host:        "elasticache.{region}.amazonaws.com",
					Action:      "ListTagsForResource",
					Version:     "2015-02-02",
					Wrapper:     "ListTagsForResourceResult",
					Input: []Binding{
						Binding{Location: "form", Member: "ResourceName", Name: "ResourceName", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "TagList", Kind: "list", XMLName: "TagList", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
			},
			Mutable: true,
		},
	})
}
