// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::GlobalAccelerator::CrossAccountAttachment": {
			Type:        "AWS::GlobalAccelerator::CrossAccountAttachment",
			Protocol:    "awsJson1_1",
			SigningName: "globalaccelerator",
			Host:        "globalaccelerator.{region}.amazonaws.com",
			Target:      "GlobalAccelerator_V20180706.DescribeCrossAccountAttachment",
			Identifier: []Binding{
				{Property: "AttachmentArn", Member: "AttachmentArn", Location: "body"},
			},
			Response: []Step{{Name: "CrossAccountAttachment"}},
			Fields: []Field{
				{Property: "AttachmentArn", Member: "AttachmentArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Principals", Member: "Principals", Kind: "list"},
				{Property: "Resources", Member: "Resources", Kind: "list",
					Fields: []Field{
						{Property: "Cidr", Member: "Cidr", Kind: "scalar"},
						{Property: "EndpointId", Member: "EndpointId", Kind: "scalar"},
					},
				},
			},
		},
	})
}
