// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::LookoutEquipment::InferenceScheduler": {
			Type:        "AWS::LookoutEquipment::InferenceScheduler",
			Protocol:    "awsJson1_0",
			SigningName: "lookoutequipment",
			Host:        "lookoutequipment.{region}.amazonaws.com",
			Target:      "AWSLookoutEquipmentFrontendService.DescribeInferenceScheduler",
			Identifier: []Binding{
				{Property: "InferenceSchedulerName", Member: "InferenceSchedulerName", Location: "body"},
			},
			Fields: []Field{
				{Property: "DataDelayOffsetInMinutes", Member: "DataDelayOffsetInMinutes", Kind: "scalar"},
				{Property: "DataInputConfiguration", Member: "DataInputConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "InferenceInputNameConfiguration", Member: "InferenceInputNameConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "ComponentTimestampDelimiter", Member: "ComponentTimestampDelimiter", Kind: "scalar"},
								{Property: "TimestampFormat", Member: "TimestampFormat", Kind: "scalar"},
							},
						},
						{Property: "InputTimeZoneOffset", Member: "InputTimeZoneOffset", Kind: "scalar"},
						{Property: "S3InputConfiguration", Member: "S3InputConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "Bucket", Member: "Bucket", Kind: "scalar"},
								{Property: "Prefix", Member: "Prefix", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "DataOutputConfiguration", Member: "DataOutputConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "KmsKeyId", Member: "KmsKeyId", Kind: "scalar"},
						{Property: "S3OutputConfiguration", Member: "S3OutputConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "Bucket", Member: "Bucket", Kind: "scalar"},
								{Property: "Prefix", Member: "Prefix", Kind: "scalar"},
							},
						},
					},
				},
				{Property: "DataUploadFrequency", Member: "DataUploadFrequency", Kind: "scalar"},
				{Property: "InferenceSchedulerArn", Member: "InferenceSchedulerArn", Kind: "scalar"},
				{Property: "InferenceSchedulerName", Member: "InferenceSchedulerName", Kind: "scalar"},
				{Property: "ModelName", Member: "ModelName", Kind: "scalar"},
				{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
				{Property: "ServerSideKmsKeyId", Member: "ServerSideKmsKeyId", Kind: "scalar"},
			},
		},
	})
}
