// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Chatbot::CustomAction": {
			Type:        "AWS::Chatbot::CustomAction",
			Protocol:    "restJson1",
			SigningName: "chatbot",
			Host:        "chatbot.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/get-custom-action",
			Identifier: []Binding{
				{Property: "CustomActionArn", Member: "CustomActionArn", Location: "body"},
			},
			Response: []Step{{Name: "CustomAction"}},
			Fields: []Field{
				{Property: "ActionName", Member: "ActionName", Kind: "scalar"},
				{Property: "AliasName", Member: "AliasName", Kind: "scalar"},
				{Property: "Attachments", Member: "Attachments", Kind: "list",
					Fields: []Field{
						{Property: "ButtonText", Member: "ButtonText", Kind: "scalar"},
						{Property: "Criteria", Member: "Criteria", Kind: "list",
							Fields: []Field{
								{Property: "Operator", Member: "Operator", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
								{Property: "VariableName", Member: "VariableName", Kind: "scalar"},
							},
						},
						{Property: "NotificationType", Member: "NotificationType", Kind: "scalar"},
						{Property: "Variables", Member: "Variables", Kind: "map"},
					},
				},
				{Property: "CustomActionArn", Member: "CustomActionArn", Kind: "scalar"},
				{Property: "Definition", Member: "Definition", Kind: "structure",
					Fields: []Field{
						{Property: "CommandText", Member: "CommandText", Kind: "scalar"},
					},
				},
			},
		},
	})
}
