// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::M2::Application": {
			Type:        "AWS::M2::Application",
			Protocol:    "restJson1",
			SigningName: "m2",
			Complete:    true,
			Host:        "m2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/applications/{applicationId}",
			Identifier: []Binding{
				{Property: "ApplicationArn", Member: "applicationId", Location: "label"},
			},
			Fields: []Field{
				{Property: "ApplicationArn", Member: "applicationArn", Kind: "scalar"},
				{Property: "ApplicationId", Member: "applicationId", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "EngineType", Member: "engineType", Kind: "scalar"},
				{Property: "KmsKeyId", Member: "kmsKeyId", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "Tags", Member: "tags", Kind: "map"},
			},
		},
		"AWS::M2::Environment": {
			Type:        "AWS::M2::Environment",
			Protocol:    "restJson1",
			SigningName: "m2",
			Complete:    true,
			Host:        "m2.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/environments/{environmentId}",
			Identifier: []Binding{
				{Property: "EnvironmentArn", Member: "environmentId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "EngineType", Member: "engineType", Kind: "scalar"},
				{Property: "EngineVersion", Member: "engineVersion", Kind: "scalar"},
				{Property: "EnvironmentArn", Member: "environmentArn", Kind: "scalar"},
				{Property: "EnvironmentId", Member: "environmentId", Kind: "scalar"},
				{Property: "HighAvailabilityConfig", Member: "highAvailabilityConfig", Kind: "structure",
					Fields: []Field{
						{Property: "DesiredCapacity", Member: "desiredCapacity", Kind: "scalar"},
					},
				},
				{Property: "InstanceType", Member: "instanceType", Kind: "scalar"},
				{Property: "KmsKeyId", Member: "kmsKeyId", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "NetworkType", Member: "networkType", Kind: "scalar"},
				{Property: "PreferredMaintenanceWindow", Member: "preferredMaintenanceWindow", Kind: "scalar"},
				{Property: "PubliclyAccessible", Member: "publiclyAccessible", Kind: "scalar"},
				{Property: "SecurityGroupIds", Member: "securityGroupIds", Kind: "list"},
				{Property: "StorageConfigurations", Member: "storageConfigurations", Kind: "list"},
				{Property: "SubnetIds", Member: "subnetIds", Kind: "list"},
				{Property: "Tags", Member: "tags", Kind: "map"},
			},
		},
	})
}
