// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::EventSchemas::Discoverer": {
			Type:        "AWS::EventSchemas::Discoverer",
			Protocol:    "restJson1",
			SigningName: "schemas",
			Host:        "schemas.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/discoverers/id/{DiscovererId}",
			Identifier: []Binding{
				{Property: "DiscovererArn", Member: "DiscovererId", Location: "label"},
			},
			Fields: []Field{
				{Property: "CrossAccount", Member: "CrossAccount", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "DiscovererArn", Member: "DiscovererArn", Kind: "scalar"},
				{Property: "DiscovererId", Member: "DiscovererId", Kind: "scalar"},
				{Property: "SourceArn", Member: "SourceArn", Kind: "scalar"},
				{Property: "State", Member: "State", Kind: "scalar"},
			},
		},
		"AWS::EventSchemas::Registry": {
			Type:        "AWS::EventSchemas::Registry",
			Protocol:    "restJson1",
			SigningName: "schemas",
			Host:        "schemas.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v1/registries/name/{RegistryName}",
			Identifier: []Binding{
				{Property: "RegistryArn", Member: "RegistryName", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "RegistryArn", Member: "RegistryArn", Kind: "scalar"},
				{Property: "RegistryName", Member: "RegistryName", Kind: "scalar"},
			},
		},
	})
}
