// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Athena::DataCatalog": {
			Type:        "AWS::Athena::DataCatalog",
			Protocol:    "awsJson1_1",
			SigningName: "athena",
			Host:        "athena.{region}.amazonaws.com",
			Target:      "AmazonAthena.GetDataCatalog",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "body"},
			},
			Response: []Step{{Name: "DataCatalog"}},
			Fields: []Field{
				{Property: "ConnectionType", Member: "ConnectionType", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Error", Member: "Error", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Parameters", Member: "Parameters", Kind: "map"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
				{Property: "Type", Member: "Type", Kind: "scalar"},
			},
		},
		"AWS::Athena::NamedQuery": {
			Type:        "AWS::Athena::NamedQuery",
			Protocol:    "awsJson1_1",
			SigningName: "athena",
			Complete:    true,
			Host:        "athena.{region}.amazonaws.com",
			Target:      "AmazonAthena.GetNamedQuery",
			Identifier: []Binding{
				{Property: "NamedQueryId", Member: "NamedQueryId", Location: "body"},
			},
			Response: []Step{{Name: "NamedQuery"}},
			Fields: []Field{
				{Property: "Database", Member: "Database", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "NamedQueryId", Member: "NamedQueryId", Kind: "scalar"},
				{Property: "QueryString", Member: "QueryString", Kind: "scalar"},
				{Property: "WorkGroup", Member: "WorkGroup", Kind: "scalar"},
			},
		},
	})
}
