// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Outposts::Outpost": {
			Type:        "AWS::Outposts::Outpost",
			Protocol:    "restJson1",
			SigningName: "outposts",
			Host:        "outposts.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/outposts/{OutpostId}",
			Identifier: []Binding{
				{Property: "OutpostArn", Member: "OutpostId", Location: "label"},
			},
			Response: []Step{{Name: "Outpost"}},
			Fields: []Field{
				{Property: "AvailabilityZone", Member: "AvailabilityZone", Kind: "scalar"},
				{Property: "AvailabilityZoneId", Member: "AvailabilityZoneId", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "LifeCycleStatus", Member: "LifeCycleStatus", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "OutpostArn", Member: "OutpostArn", Kind: "scalar"},
				{Property: "OutpostId", Member: "OutpostId", Kind: "scalar"},
				{Property: "OwnerId", Member: "OwnerId", Kind: "scalar"},
				{Property: "SiteArn", Member: "SiteArn", Kind: "scalar"},
				{Property: "SiteId", Member: "SiteId", Kind: "scalar"},
				{Property: "SupportedHardwareType", Member: "SupportedHardwareType", Kind: "scalar"},
			},
		},
	})
}
