// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::HealthImaging::Datastore": {
			Type:        "AWS::HealthImaging::Datastore",
			Protocol:    "restJson1",
			SigningName: "medical-imaging",
			Host:        "medical-imaging.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/datastore/{datastoreId}",
			Identifier: []Binding{
				{Property: "DatastoreId", Member: "datastoreId", Location: "label"},
			},
			Response: []Step{{Name: "datastoreProperties"}},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "DatastoreArn", Member: "datastoreArn", Kind: "scalar"},
				{Property: "DatastoreId", Member: "datastoreId", Kind: "scalar"},
				{Property: "DatastoreName", Member: "datastoreName", Kind: "scalar"},
				{Property: "DatastoreStatus", Member: "datastoreStatus", Kind: "scalar"},
				{Property: "KmsKeyArn", Member: "kmsKeyArn", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
