// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ResilienceHubV2::Policy": {
			Type:        "AWS::ResilienceHubV2::Policy",
			Protocol:    "restJson1",
			SigningName: "resiliencehub",
			Host:        "resiliencehub.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v2/get-policy",
			Identifier: []Binding{
				{Property: "PolicyArn", Member: "policyArn", Location: "query", Name: "policyArn"},
			},
			Response: []Step{{Name: "policy"}},
			Fields: []Field{
				{Property: "AssociatedServiceCount", Member: "associatedServiceCount", Kind: "scalar"},
				{Property: "AvailabilitySlo", Member: "availabilitySlo", Kind: "structure",
					Fields: []Field{
						{Property: "Target", Member: "target", Kind: "scalar"},
					},
				},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "DataRecovery", Member: "dataRecovery", Kind: "structure",
					Fields: []Field{
						{Property: "TimeBetweenBackupsInMinutes", Member: "timeBetweenBackupsInMinutes", Kind: "scalar"},
					},
				},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "MultiAz", Member: "multiAz", Kind: "structure",
					Fields: []Field{
						{Property: "DisasterRecoveryApproach", Member: "disasterRecoveryApproach", Kind: "scalar"},
						{Property: "RpoInMinutes", Member: "rpoInMinutes", Kind: "scalar"},
						{Property: "RtoInMinutes", Member: "rtoInMinutes", Kind: "scalar"},
					},
				},
				{Property: "MultiRegion", Member: "multiRegion", Kind: "structure",
					Fields: []Field{
						{Property: "DisasterRecoveryApproach", Member: "disasterRecoveryApproach", Kind: "scalar"},
						{Property: "RpoInMinutes", Member: "rpoInMinutes", Kind: "scalar"},
						{Property: "RtoInMinutes", Member: "rtoInMinutes", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "PolicyArn", Member: "policyArn", Kind: "scalar"},
				{Property: "SharingEnabled", Member: "sharingEnabled", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
		"AWS::ResilienceHubV2::System": {
			Type:        "AWS::ResilienceHubV2::System",
			Protocol:    "restJson1",
			SigningName: "resiliencehub",
			Host:        "resiliencehub.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v2/get-system",
			Identifier: []Binding{
				{Property: "SystemArn", Member: "systemArn", Location: "query", Name: "systemArn"},
			},
			Response: []Step{{Name: "system"}},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "SharingEnabled", Member: "sharingEnabled", Kind: "scalar"},
				{Property: "SystemArn", Member: "systemArn", Kind: "scalar"},
				{Property: "SystemId", Member: "systemId", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
	})
}
