// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Route53RecoveryReadiness::Cell": {
			Type:        "AWS::Route53RecoveryReadiness::Cell",
			Protocol:    "restJson1",
			SigningName: "route53-recovery-readiness",
			Host:        "route53-recovery-readiness.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/cells/{CellName}",
			Identifier: []Binding{
				{Property: "CellName", Member: "CellName", Location: "label"},
			},
			Fields: []Field{
				{Property: "CellArn", Member: "CellArn", Kind: "scalar", JSONName: "cellArn"},
				{Property: "CellName", Member: "CellName", Kind: "scalar", JSONName: "cellName"},
				{Property: "Cells", Member: "Cells", Kind: "list", JSONName: "cells"},
				{Property: "ParentReadinessScopes", Member: "ParentReadinessScopes", Kind: "list", JSONName: "parentReadinessScopes"},
			},
		},
		"AWS::Route53RecoveryReadiness::RecoveryGroup": {
			Type:        "AWS::Route53RecoveryReadiness::RecoveryGroup",
			Protocol:    "restJson1",
			SigningName: "route53-recovery-readiness",
			Host:        "route53-recovery-readiness.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/recoverygroups/{RecoveryGroupName}",
			Identifier: []Binding{
				{Property: "RecoveryGroupName", Member: "RecoveryGroupName", Location: "label"},
			},
			Fields: []Field{
				{Property: "Cells", Member: "Cells", Kind: "list", JSONName: "cells"},
				{Property: "RecoveryGroupArn", Member: "RecoveryGroupArn", Kind: "scalar", JSONName: "recoveryGroupArn"},
				{Property: "RecoveryGroupName", Member: "RecoveryGroupName", Kind: "scalar", JSONName: "recoveryGroupName"},
			},
		},
		"AWS::Route53RecoveryReadiness::ResourceSet": {
			Type:        "AWS::Route53RecoveryReadiness::ResourceSet",
			Protocol:    "restJson1",
			SigningName: "route53-recovery-readiness",
			Host:        "route53-recovery-readiness.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/resourcesets/{ResourceSetName}",
			Identifier: []Binding{
				{Property: "ResourceSetName", Member: "ResourceSetName", Location: "label"},
			},
			Fields: []Field{
				{Property: "ResourceSetArn", Member: "ResourceSetArn", Kind: "scalar", JSONName: "resourceSetArn"},
				{Property: "ResourceSetName", Member: "ResourceSetName", Kind: "scalar", JSONName: "resourceSetName"},
				{Property: "ResourceSetType", Member: "ResourceSetType", Kind: "scalar", JSONName: "resourceSetType"},
				{Property: "Resources", Member: "Resources", Kind: "list", JSONName: "resources",
					Fields: []Field{
						{Property: "ComponentId", Member: "ComponentId", Kind: "scalar", JSONName: "componentId"},
						{Property: "DnsTargetResource", Member: "DnsTargetResource", Kind: "structure", JSONName: "dnsTargetResource",
							Fields: []Field{
								{Property: "DomainName", Member: "DomainName", Kind: "scalar", JSONName: "domainName"},
								{Property: "HostedZoneArn", Member: "HostedZoneArn", Kind: "scalar", JSONName: "hostedZoneArn"},
								{Property: "RecordSetId", Member: "RecordSetId", Kind: "scalar", JSONName: "recordSetId"},
								{Property: "RecordType", Member: "RecordType", Kind: "scalar", JSONName: "recordType"},
								{Property: "TargetResource", Member: "TargetResource", Kind: "structure", JSONName: "targetResource",
									Fields: []Field{
										{Property: "NLBResource", Member: "NLBResource", Kind: "structure", JSONName: "nLBResource",
											Fields: []Field{
												{Property: "Arn", Member: "Arn", Kind: "scalar", JSONName: "arn"},
											},
										},
										{Property: "R53Resource", Member: "R53Resource", Kind: "structure", JSONName: "r53Resource",
											Fields: []Field{
												{Property: "DomainName", Member: "DomainName", Kind: "scalar", JSONName: "domainName"},
												{Property: "RecordSetId", Member: "RecordSetId", Kind: "scalar", JSONName: "recordSetId"},
											},
										},
									},
								},
							},
						},
						{Property: "ReadinessScopes", Member: "ReadinessScopes", Kind: "list", JSONName: "readinessScopes"},
						{Property: "ResourceArn", Member: "ResourceArn", Kind: "scalar", JSONName: "resourceArn"},
					},
				},
			},
		},
	})
}
