// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ApiGatewayV2::Api": {
			Type:        "AWS::ApiGatewayV2::Api",
			Protocol:    "restJson1",
			SigningName: "apigateway",
			Host:        "apigateway.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/v2/apis/{ApiId}",
			Identifier: []Binding{
				{Property: "ApiId", Member: "ApiId", Location: "label"},
			},
			AbsentErrors: []string{"NotFoundException"},
			Fields: []Field{
				{Property: "ApiEndpoint", Member: "ApiEndpoint", Kind: "scalar", JSONName: "apiEndpoint"},
				{Property: "ApiId", Member: "ApiId", Kind: "scalar", JSONName: "apiId"},
				{Property: "ApiKeySelectionExpression", Member: "ApiKeySelectionExpression", Kind: "scalar", Unless: []Condition{{Field: Field{Property: "ProtocolType"}, Values: []string{"HTTP"}}}, JSONName: "apiKeySelectionExpression"},
				{Property: "CorsConfiguration", Member: "CorsConfiguration", Kind: "structure", JSONName: "corsConfiguration",
					Fields: []Field{
						{Property: "AllowCredentials", Member: "AllowCredentials", Kind: "scalar", JSONName: "allowCredentials"},
						{Property: "AllowHeaders", Member: "AllowHeaders", Kind: "list", JSONName: "allowHeaders"},
						{Property: "AllowMethods", Member: "AllowMethods", Kind: "list", JSONName: "allowMethods"},
						{Property: "AllowOrigins", Member: "AllowOrigins", Kind: "list", JSONName: "allowOrigins"},
						{Property: "ExposeHeaders", Member: "ExposeHeaders", Kind: "list", JSONName: "exposeHeaders"},
						{Property: "MaxAge", Member: "MaxAge", Kind: "scalar", JSONName: "maxAge"},
					},
				},
				{Property: "Description", Member: "Description", Kind: "scalar", JSONName: "description"},
				{Property: "DisableExecuteApiEndpoint", Member: "DisableExecuteApiEndpoint", Kind: "scalar", JSONName: "disableExecuteApiEndpoint"},
				{Property: "IpAddressType", Member: "IpAddressType", Kind: "scalar", JSONName: "ipAddressType"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "ProtocolType", Member: "ProtocolType", Kind: "scalar", JSONName: "protocolType"},
				{Property: "RouteSelectionExpression", Member: "RouteSelectionExpression", Kind: "scalar", JSONName: "routeSelectionExpression"},
				{Property: "Tags", Member: "Tags", Kind: "map", JSONName: "tags"},
				{Property: "Version", Member: "Version", Kind: "scalar", JSONName: "version"},
			},
			AbsentIDs: []string{"abcde12345"},
		},
	})
}
