// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::CleanRoomsML::ConfiguredModelAlgorithm": {
			Type:        "AWS::CleanRoomsML::ConfiguredModelAlgorithm",
			Protocol:    "restJson1",
			SigningName: "cleanrooms-ml",
			Host:        "cleanrooms-ml.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/configured-model-algorithms/{configuredModelAlgorithmArn}",
			Identifier: []Binding{
				{Property: "ConfiguredModelAlgorithmArn", Member: "configuredModelAlgorithmArn", Location: "label"},
			},
			Fields: []Field{
				{Property: "ConfiguredModelAlgorithmArn", Member: "configuredModelAlgorithmArn", Kind: "scalar"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "InferenceContainerConfig", Member: "inferenceContainerConfig", Kind: "structure",
					Fields: []Field{
						{Property: "ImageUri", Member: "imageUri", Kind: "scalar"},
					},
				},
				{Property: "KmsKeyArn", Member: "kmsKeyArn", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "TrainingContainerConfig", Member: "trainingContainerConfig", Kind: "structure",
					Fields: []Field{
						{Property: "Arguments", Member: "arguments", Kind: "list"},
						{Property: "Entrypoint", Member: "entrypoint", Kind: "list"},
						{Property: "ImageUri", Member: "imageUri", Kind: "scalar"},
						{Property: "MetricDefinitions", Member: "metricDefinitions", Kind: "list",
							Fields: []Field{
								{Property: "Name", Member: "name", Kind: "scalar"},
								{Property: "Regex", Member: "regex", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
		"AWS::CleanRoomsML::TrainingDataset": {
			Type:        "AWS::CleanRoomsML::TrainingDataset",
			Protocol:    "restJson1",
			SigningName: "cleanrooms-ml",
			Host:        "cleanrooms-ml.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/training-dataset/{trainingDatasetArn}",
			Identifier: []Binding{
				{Property: "TrainingDatasetArn", Member: "trainingDatasetArn", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "TrainingData", Member: "trainingData", Kind: "list",
					Fields: []Field{
						{Property: "InputConfig", Member: "inputConfig", Kind: "structure",
							Fields: []Field{
								{Property: "DataSource", Member: "dataSource", Kind: "structure",
									Fields: []Field{
										{Property: "GlueDataSource", Member: "glueDataSource", Kind: "structure",
											Fields: []Field{
												{Property: "CatalogId", Member: "catalogId", Kind: "scalar"},
												{Property: "DatabaseName", Member: "databaseName", Kind: "scalar"},
												{Property: "TableName", Member: "tableName", Kind: "scalar"},
											},
										},
									},
								},
								{Property: "Schema", Member: "schema", Kind: "list",
									Fields: []Field{
										{Property: "ColumnName", Member: "columnName", Kind: "scalar"},
										{Property: "ColumnTypes", Member: "columnTypes", Kind: "list"},
									},
								},
							},
						},
						{Property: "Type", Member: "type", Kind: "scalar"},
					},
				},
				{Property: "TrainingDatasetArn", Member: "trainingDatasetArn", Kind: "scalar"},
			},
		},
	})
}
