// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Lambda::CodeSigningConfig": {
			Type:        "AWS::Lambda::CodeSigningConfig",
			Protocol:    "restJson1",
			SigningName: "lambda",
			Host:        "lambda.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/2020-04-22/code-signing-configs/{CodeSigningConfigArn}",
			Identifier: []Binding{
				{Property: "CodeSigningConfigArn", Member: "CodeSigningConfigArn", Location: "label"},
			},
			Response: []Step{{Name: "CodeSigningConfig"}},
			Fields: []Field{
				{Property: "AllowedPublishers", Member: "AllowedPublishers", Kind: "structure",
					Fields: []Field{
						{Property: "SigningProfileVersionArns", Member: "SigningProfileVersionArns", Kind: "list"},
					},
				},
				{Property: "CodeSigningConfigArn", Member: "CodeSigningConfigArn", Kind: "scalar"},
				{Property: "CodeSigningConfigId", Member: "CodeSigningConfigId", Kind: "scalar"},
				{Property: "CodeSigningPolicies", Member: "CodeSigningPolicies", Kind: "structure",
					Fields: []Field{
						{Property: "UntrustedArtifactOnDeployment", Member: "UntrustedArtifactOnDeployment", Kind: "scalar"},
					},
				},
				{Property: "Description", Member: "Description", Kind: "scalar"},
			},
		},
		"AWS::Lambda::MicrovmImage": {
			Type:        "AWS::Lambda::MicrovmImage",
			Protocol:    "restJson1",
			SigningName: "lambda",
			Host:        "lambda.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/2025-09-09/microvm-images/{imageIdentifier}",
			Identifier: []Binding{
				{Property: "ImageArn", Member: "imageIdentifier", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "ImageArn", Member: "imageArn", Kind: "scalar"},
				{Property: "LatestActiveImageVersion", Member: "latestActiveImageVersion", Kind: "scalar"},
				{Property: "LatestFailedImageVersion", Member: "latestFailedImageVersion", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "State", Member: "state", Kind: "scalar"},
				{Property: "UpdatedAt", Member: "updatedAt", Kind: "timestamp"},
			},
		},
		"AWS::Lambda::Permission": {
			Type:        "AWS::Lambda::Permission",
			Protocol:    "restJson1",
			SigningName: "lambda",
			Complete:    true,
			Production:  true,
			Host:        "lambda.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/2015-03-31/functions/{FunctionName}/policy",
			Identifier: []Binding{
				{Property: "FunctionName", Member: "FunctionName", Location: "label"},
				{Property: "Id", Member: "", Location: "placeholder"},
			},
			AbsentErrors: []string{"ResourceNotFoundException"},
			Fields: []Field{
				{Property: "Action", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Action"}},
				{Property: "EventSourceToken", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Condition.StringEquals.lambda:EventSourceToken"}},
				{Property: "FunctionName", Member: "FunctionName", Kind: "identifier"},
				{Property: "FunctionUrlAuthType", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Condition.StringEquals.lambda:FunctionUrlAuthType"}},
				{Property: "Id", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Sid"}},
				{Property: "InvokedViaFunctionUrl", Member: "Policy", Kind: "scalar", Transform: "boolean", Extract: []string{"Statement[Sid={Id}].Condition.Bool.lambda:InvokedViaFunctionUrl"}},
				{Property: "Principal", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Principal.Service", "Statement[Sid={Id}].Principal.AWS"}},
				{Property: "PrincipalOrgID", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Condition.StringEquals.aws:PrincipalOrgID"}},
				{Property: "SourceAccount", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Condition.StringEquals.AWS:SourceAccount"}},
				{Property: "SourceArn", Member: "Policy", Kind: "scalar", Extract: []string{"Statement[Sid={Id}].Condition.ArnLike.AWS:SourceArn"}},
			},
			AbsentIDs: []string{"kraai-absent-probe|kraai-absent-statement"},
		},
		"AWS::Lambda::Url": {
			Type:        "AWS::Lambda::Url",
			Protocol:    "restJson1",
			SigningName: "lambda",
			Complete:    true,
			Production:  true,
			Host:        "lambda.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/2021-10-31/functions/{FunctionName}/url",
			Identifier: []Binding{
				{Property: "FunctionArn", Member: "FunctionName", Location: "label"},
			},
			AbsentErrors: []string{"ResourceNotFoundException"},
			Fields: []Field{
				{Property: "AuthType", Member: "AuthType", Kind: "scalar"},
				{Property: "Cors", Member: "Cors", Kind: "structure",
					Fields: []Field{
						{Property: "AllowCredentials", Member: "AllowCredentials", Kind: "scalar"},
						{Property: "AllowHeaders", Member: "AllowHeaders", Kind: "list"},
						{Property: "AllowMethods", Member: "AllowMethods", Kind: "list"},
						{Property: "AllowOrigins", Member: "AllowOrigins", Kind: "list"},
						{Property: "ExposeHeaders", Member: "ExposeHeaders", Kind: "list"},
						{Property: "MaxAge", Member: "MaxAge", Kind: "scalar"},
					},
				},
				{Property: "FunctionArn", Member: "FunctionArn", Kind: "scalar"},
				{Property: "FunctionUrl", Member: "FunctionUrl", Kind: "scalar"},
				{Property: "InvokeMode", Member: "InvokeMode", Kind: "scalar"},
				{Property: "Qualifier", Member: "FunctionArn", Kind: "scalar", Transform: "arnPart:7"},
				{Property: "TargetFunctionArn", Member: "FunctionArn", Kind: "scalar", Transform: "arnPart:6"},
			},
			AbsentIDs: []string{"arn:aws:lambda:{region}:{account}:function:kraai-absent-probe"},
		},
	})
}
