// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SSO::Application": {
			Type:        "AWS::SSO::Application",
			Protocol:    "awsJson1_1",
			SigningName: "sso",
			Host:        "sso.{region}.amazonaws.com",
			Target:      "SWBExternalService.DescribeApplication",
			Identifier: []Binding{
				{Property: "ApplicationArn", Member: "ApplicationArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "ApplicationArn", Member: "ApplicationArn", Kind: "scalar"},
				{Property: "ApplicationProviderArn", Member: "ApplicationProviderArn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "IdentityStoreArn", Member: "IdentityStoreArn", Kind: "scalar"},
				{Property: "InstanceArn", Member: "InstanceArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "PortalOptions", Member: "PortalOptions", Kind: "structure",
					Fields: []Field{
						{Property: "SignInOptions", Member: "SignInOptions", Kind: "structure",
							Fields: []Field{
								{Property: "ApplicationUrl", Member: "ApplicationUrl", Kind: "scalar"},
								{Property: "Origin", Member: "Origin", Kind: "scalar"},
							},
						},
						{Property: "Visibility", Member: "Visibility", Kind: "scalar"},
					},
				},
				{Property: "Status", Member: "Status", Kind: "scalar"},
			},
		},
		"AWS::SSO::Instance": {
			Type:        "AWS::SSO::Instance",
			Protocol:    "awsJson1_1",
			SigningName: "sso",
			Host:        "sso.{region}.amazonaws.com",
			Target:      "SWBExternalService.DescribeInstance",
			Identifier: []Binding{
				{Property: "InstanceArn", Member: "InstanceArn", Location: "body"},
			},
			Fields: []Field{
				{Property: "IdentityStoreId", Member: "IdentityStoreId", Kind: "scalar"},
				{Property: "InstanceArn", Member: "InstanceArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "OwnerAccountId", Member: "OwnerAccountId", Kind: "scalar"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
			},
		},
	})
}
