// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::B2BI::Profile": {
			Type:        "AWS::B2BI::Profile",
			Protocol:    "awsJson1_0",
			SigningName: "b2bi",
			Host:        "b2bi.{region}.amazonaws.com",
			Target:      "B2BI.GetProfile",
			Identifier: []Binding{
				{Property: "ProfileId", Member: "profileId", Location: "body"},
			},
			Fields: []Field{
				{Property: "BusinessName", Member: "businessName", Kind: "scalar"},
				{Property: "CreatedAt", Member: "createdAt", Kind: "timestamp"},
				{Property: "Email", Member: "email", Kind: "scalar"},
				{Property: "LogGroupName", Member: "logGroupName", Kind: "scalar"},
				{Property: "Logging", Member: "logging", Kind: "scalar"},
				{Property: "ModifiedAt", Member: "modifiedAt", Kind: "timestamp"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "Phone", Member: "phone", Kind: "scalar"},
				{Property: "ProfileArn", Member: "profileArn", Kind: "scalar"},
				{Property: "ProfileId", Member: "profileId", Kind: "scalar"},
			},
		},
	})
}
