// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::RDS::DBClusterParameterGroup": {
			Type:        "AWS::RDS::DBClusterParameterGroup",
			Protocol:    "awsQuery",
			SigningName: "rds",
			Complete:    true,
			Production:  true,
			Host:        "rds.{region}.amazonaws.com",
			Action:      "DescribeDBClusterParameterGroups",
			Version:     "2014-10-31",
			Wrapper:     "DescribeDBClusterParameterGroupsResult",
			Identifier: []Binding{
				{Property: "DBClusterParameterGroupName", Member: "DBClusterParameterGroupName", Location: "form", Name: "DBClusterParameterGroupName"},
			},
			AbsentErrors: []string{"DBParameterGroupNotFound"},
			PageToken:    []string{"Marker"},
			Response:     []Step{{Name: "DBClusterParameterGroups", List: true, Item: "DBClusterParameterGroup"}},
			Fields: []Field{
				{Property: "DBClusterParameterGroupName", Member: "DBClusterParameterGroupName", Kind: "scalar", XMLName: "DBClusterParameterGroupName", Scalar: "string"},
				{Property: "Description", Member: "Description", Kind: "scalar", XMLName: "Description", Scalar: "string"},
				{Property: "Family", Member: "DBParameterGroupFamily", Kind: "scalar", XMLName: "DBParameterGroupFamily", Scalar: "string"},
			},
			AbsentIDs: []string{"kraai-absent-probe"},
			Capture: []Field{
				{Property: "Arn", Member: "DBClusterParameterGroupArn", Kind: "scalar", XMLName: "DBClusterParameterGroupArn", Scalar: "string"},
			},
			Also: []Reader{
				{
					Type:        "AWS::RDS::DBClusterParameterGroup",
					Protocol:    "awsQuery",
					SigningName: "rds",
					Host:        "rds.{region}.amazonaws.com",
					Action:      "DescribeDBClusterParameters",
					Version:     "2014-10-31",
					Wrapper:     "DescribeDBClusterParametersResult",
					Identifier: []Binding{
						{Property: "DBClusterParameterGroupName", Member: "DBClusterParameterGroupName", Location: "form", Name: "DBClusterParameterGroupName"},
					},
					Input: []Binding{
						Binding{Location: "form", Member: "Source", Name: "Source", Value: "user"},
					},
					PageToken: []string{"Marker"},
					Fields: []Field{
						{Property: "Parameters", Member: "Parameters", Kind: "list", Keyed: []string{"ParameterName", "ParameterValue"}, XMLName: "Parameters", Item: "Parameter"},
					},
				},
				{
					Type:        "AWS::RDS::DBClusterParameterGroup",
					Protocol:    "awsQuery",
					SigningName: "rds",
					Host:        "rds.{region}.amazonaws.com",
					Action:      "ListTagsForResource",
					Version:     "2014-10-31",
					Wrapper:     "ListTagsForResourceResult",
					Input: []Binding{
						Binding{Location: "form", Member: "ResourceName", Name: "ResourceName", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "TagList", Kind: "list", XMLName: "TagList", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
			},
		},
		"AWS::RDS::DBSubnetGroup": {
			Type:        "AWS::RDS::DBSubnetGroup",
			Protocol:    "awsQuery",
			SigningName: "rds",
			Complete:    true,
			Production:  true,
			Host:        "rds.{region}.amazonaws.com",
			Action:      "DescribeDBSubnetGroups",
			Version:     "2014-10-31",
			Wrapper:     "DescribeDBSubnetGroupsResult",
			Identifier: []Binding{
				{Property: "DBSubnetGroupName", Member: "DBSubnetGroupName", Location: "form", Name: "DBSubnetGroupName"},
			},
			AbsentErrors: []string{"DBSubnetGroupNotFoundFault"},
			PageToken:    []string{"Marker"},
			Response:     []Step{{Name: "DBSubnetGroups", List: true, Item: "DBSubnetGroup"}},
			Fields: []Field{
				{Property: "DBSubnetGroupArn", Member: "DBSubnetGroupArn", Kind: "scalar", XMLName: "DBSubnetGroupArn", Scalar: "string"},
				{Property: "DBSubnetGroupDescription", Member: "DBSubnetGroupDescription", Kind: "scalar", XMLName: "DBSubnetGroupDescription", Scalar: "string"},
				{Property: "DBSubnetGroupName", Member: "DBSubnetGroupName", Kind: "scalar", XMLName: "DBSubnetGroupName", Scalar: "string"},
				{Property: "SubnetIds", Member: "SubnetIdentifier", Kind: "scalar", Via: []Step{{Name: "Subnets", List: true, Item: "Subnet"}}, XMLName: "SubnetIdentifier", Scalar: "string"},
			},
			AbsentIDs: []string{"kraai-absent-probe-0123456789"},
			Capture: []Field{
				{Property: "Arn", Member: "DBSubnetGroupArn", Kind: "scalar", XMLName: "DBSubnetGroupArn", Scalar: "string"},
			},
			Also: []Reader{
				{
					Type:        "AWS::RDS::DBSubnetGroup",
					Protocol:    "awsQuery",
					SigningName: "rds",
					Host:        "rds.{region}.amazonaws.com",
					Action:      "ListTagsForResource",
					Version:     "2014-10-31",
					Wrapper:     "ListTagsForResourceResult",
					Input: []Binding{
						Binding{Location: "form", Member: "ResourceName", Name: "ResourceName", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "TagList", Kind: "list", XMLName: "TagList", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
			},
		},
	})
}
