// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::EMR::SecurityConfiguration": {
			Type:        "AWS::EMR::SecurityConfiguration",
			Protocol:    "awsJson1_1",
			SigningName: "elasticmapreduce",
			Complete:    true,
			Host:        "elasticmapreduce.{region}.amazonaws.com",
			Target:      "ElasticMapReduce.DescribeSecurityConfiguration",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "body"},
			},
			Fields: []Field{
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "SecurityConfiguration", Member: "SecurityConfiguration", Kind: "scalar"},
			},
		},
	})
}
