// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Wickr::Network": {
			Type:        "AWS::Wickr::Network",
			Protocol:    "restJson1",
			SigningName: "wickr",
			Complete:    true,
			Host:        "admin.wickr.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/networks/{networkId}",
			Identifier: []Binding{
				{Property: "NetworkArn", Member: "", Location: "placeholder"},
			},
			Input: []Binding{
				Binding{Location: "label", Member: "networkId", Value: "{NetworkArn:arnName}"},
			},
			Fields: []Field{
				{Property: "AccessLevel", Member: "accessLevel", Kind: "scalar"},
				{Property: "AwsAccountId", Member: "awsAccountId", Kind: "scalar"},
				{Property: "MigrationState", Member: "migrationState", Kind: "scalar"},
				{Property: "NetworkArn", Member: "networkArn", Kind: "scalar"},
				{Property: "NetworkId", Member: "networkId", Kind: "scalar"},
				{Property: "NetworkName", Member: "networkName", Kind: "scalar"},
				{Property: "Standing", Member: "standing", Kind: "scalar"},
			},
		},
	})
}
