// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Backup::RestoreTestingPlan": {
			Type:        "AWS::Backup::RestoreTestingPlan",
			Protocol:    "restJson1",
			SigningName: "backup",
			Host:        "backup.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/restore-testing/plans/{RestoreTestingPlanName}",
			Identifier: []Binding{
				{Property: "RestoreTestingPlanName", Member: "RestoreTestingPlanName", Location: "label"},
			},
			Response: []Step{{Name: "RestoreTestingPlan"}},
			Fields: []Field{
				{Property: "RecoveryPointSelection", Member: "RecoveryPointSelection", Kind: "structure",
					Fields: []Field{
						{Property: "Algorithm", Member: "Algorithm", Kind: "scalar"},
						{Property: "ExcludeVaults", Member: "ExcludeVaults", Kind: "list"},
						{Property: "IncludeVaults", Member: "IncludeVaults", Kind: "list"},
						{Property: "RecoveryPointTypes", Member: "RecoveryPointTypes", Kind: "list"},
						{Property: "SelectionWindowDays", Member: "SelectionWindowDays", Kind: "scalar"},
					},
				},
				{Property: "RestoreTestingPlanArn", Member: "RestoreTestingPlanArn", Kind: "scalar"},
				{Property: "RestoreTestingPlanName", Member: "RestoreTestingPlanName", Kind: "scalar"},
				{Property: "ScheduleExpression", Member: "ScheduleExpression", Kind: "scalar"},
				{Property: "ScheduleExpressionTimezone", Member: "ScheduleExpressionTimezone", Kind: "scalar"},
				{Property: "StartWindowHours", Member: "StartWindowHours", Kind: "scalar"},
			},
		},
	})
}
