// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Route53Profiles::Profile": {
			Type:        "AWS::Route53Profiles::Profile",
			Protocol:    "restJson1",
			SigningName: "route53profiles",
			Host:        "route53profiles.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/profile/{ProfileId}",
			Identifier: []Binding{
				{Property: "Id", Member: "ProfileId", Location: "label"},
			},
			Response: []Step{{Name: "Profile"}},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "ClientToken", Member: "ClientToken", Kind: "scalar"},
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ShareStatus", Member: "ShareStatus", Kind: "scalar"},
			},
		},
		"AWS::Route53Profiles::ProfileAssociation": {
			Type:        "AWS::Route53Profiles::ProfileAssociation",
			Protocol:    "restJson1",
			SigningName: "route53profiles",
			Host:        "route53profiles.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/profileassociation/{ProfileAssociationId}",
			Identifier: []Binding{
				{Property: "Id", Member: "ProfileAssociationId", Location: "label"},
			},
			Response: []Step{{Name: "ProfileAssociation"}},
			Fields: []Field{
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ProfileId", Member: "ProfileId", Kind: "scalar"},
				{Property: "ResourceId", Member: "ResourceId", Kind: "scalar"},
			},
		},
		"AWS::Route53Profiles::ProfileResourceAssociation": {
			Type:        "AWS::Route53Profiles::ProfileResourceAssociation",
			Protocol:    "restJson1",
			SigningName: "route53profiles",
			Complete:    true,
			Host:        "route53profiles.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/profileresourceassociation/{ProfileResourceAssociationId}",
			Identifier: []Binding{
				{Property: "Id", Member: "ProfileResourceAssociationId", Location: "label"},
			},
			Response: []Step{{Name: "ProfileResourceAssociation"}},
			Fields: []Field{
				{Property: "Id", Member: "Id", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ProfileId", Member: "ProfileId", Kind: "scalar"},
				{Property: "ResourceArn", Member: "ResourceArn", Kind: "scalar"},
				{Property: "ResourceProperties", Member: "ResourceProperties", Kind: "scalar"},
				{Property: "ResourceType", Member: "ResourceType", Kind: "scalar"},
			},
		},
	})
}
