// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::SQS::Queue": {
			Type:        "AWS::SQS::Queue",
			Protocol:    "awsJson1_0",
			SigningName: "sqs",
			Complete:    true,
			Production:  true,
			Host:        "sqs.{region}.amazonaws.com",
			Target:      "AmazonSQS.GetQueueAttributes",
			Identifier: []Binding{
				{Property: "QueueUrl", Member: "QueueUrl", Location: "body"},
			},
			Input: []Binding{
				Binding{Location: "body", Member: "AttributeNames", Structured: []any{"All"}},
			},
			AbsentErrors: []string{"QueueDoesNotExist"},
			Fields: []Field{
				{Property: "Arn", Member: "Attributes", Kind: "scalar", Key: "QueueArn"},
				{Property: "ContentBasedDeduplication", Member: "Attributes", Kind: "scalar", Transform: "boolean", Key: "ContentBasedDeduplication"},
				{Property: "DeduplicationScope", Member: "Attributes", Kind: "scalar", Key: "DeduplicationScope"},
				{Property: "DelaySeconds", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "DelaySeconds"},
				{Property: "FifoQueue", Member: "Attributes", Kind: "scalar", Transform: "boolean", Key: "FifoQueue"},
				{Property: "FifoThroughputLimit", Member: "Attributes", Kind: "scalar", Key: "FifoThroughputLimit"},
				{Property: "KmsDataKeyReusePeriodSeconds", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "KmsDataKeyReusePeriodSeconds"},
				{Property: "KmsMasterKeyId", Member: "Attributes", Kind: "scalar", Key: "KmsMasterKeyId"},
				{Property: "MaximumMessageSize", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "MaximumMessageSize"},
				{Property: "MessageRetentionPeriod", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "MessageRetentionPeriod"},
				{Property: "QueueName", Member: "Attributes", Kind: "scalar", Transform: "arnResource", Key: "QueueArn"},
				{Property: "QueueUrl", Member: "QueueUrl", Kind: "identifier"},
				{Property: "ReceiveMessageWaitTimeSeconds", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "ReceiveMessageWaitTimeSeconds"},
				{Property: "RedriveAllowPolicy", Member: "Attributes", Kind: "scalar", Transform: "json", Key: "RedriveAllowPolicy"},
				{Property: "RedrivePolicy", Member: "Attributes", Kind: "scalar", Transform: "json", Key: "RedrivePolicy"},
				{Property: "SqsManagedSseEnabled", Member: "Attributes", Kind: "scalar", Transform: "boolean", Key: "SqsManagedSseEnabled"},
				{Property: "VisibilityTimeout", Member: "Attributes", Kind: "scalar", Transform: "number", Key: "VisibilityTimeout"},
			},
			AbsentIDs:         []string{"https://sqs.{region}.amazonaws.com/{account}/kraai-absent-probe"},
			LifecycleComplete: true,
			Create:            &MutationCall{Operation: "CreateQueue", Target: "AmazonSQS.CreateQueue", NameProperty: "QueueName", NameTag: "kraai:resource-name", Input: map[string]any{"Attributes": map[string]any{"ContentBasedDeduplication": "{ContentBasedDeduplication:string}", "DeduplicationScope": "{DeduplicationScope}", "DelaySeconds": "{DelaySeconds:string}", "FifoQueue": "{FifoQueue:string}", "FifoThroughputLimit": "{FifoThroughputLimit}", "KmsDataKeyReusePeriodSeconds": "{KmsDataKeyReusePeriodSeconds:string}", "KmsMasterKeyId": "{KmsMasterKeyId}", "MaximumMessageSize": "{MaximumMessageSize:string}", "MessageRetentionPeriod": "{MessageRetentionPeriod:string}", "ReceiveMessageWaitTimeSeconds": "{ReceiveMessageWaitTimeSeconds:string}", "RedriveAllowPolicy": "{RedriveAllowPolicy:json}", "RedrivePolicy": "{RedrivePolicy:json}", "SqsManagedSseEnabled": "{SqsManagedSseEnabled:string}", "VisibilityTimeout": "{VisibilityTimeout:string}"}, "QueueName": "{QueueName}", "tags": "{Tags:entries}"}, RetryErrors: []string{"QueueDeletedRecently"}, Identifier: map[string]string{"QueueUrl": "QueueUrl"}},
			Delete:            &MutationCall{Operation: "DeleteQueue", Target: "AmazonSQS.DeleteQueue", Input: map[string]any{"QueueUrl": "{QueueUrl}"}, AbsentErrors: []string{"QueueDoesNotExist"}},
			Update: []MutationCall{
				MutationCall{Operation: "SetQueueAttributes", Target: "AmazonSQS.SetQueueAttributes", Input: map[string]any{"Attributes": map[string]any{"ContentBasedDeduplication": "{ContentBasedDeduplication:string}", "DeduplicationScope": "{DeduplicationScope}", "DelaySeconds": "{DelaySeconds:string}", "FifoThroughputLimit": "{FifoThroughputLimit}", "KmsDataKeyReusePeriodSeconds": "{KmsDataKeyReusePeriodSeconds:string}", "KmsMasterKeyId": "{KmsMasterKeyId}", "MaximumMessageSize": "{MaximumMessageSize:string}", "MessageRetentionPeriod": "{MessageRetentionPeriod:string}", "ReceiveMessageWaitTimeSeconds": "{ReceiveMessageWaitTimeSeconds:string}", "RedriveAllowPolicy": "{RedriveAllowPolicy:json}", "RedrivePolicy": "{RedrivePolicy:json}", "SqsManagedSseEnabled": "{SqsManagedSseEnabled:string}", "VisibilityTimeout": "{VisibilityTimeout:string}"}, "QueueUrl": "{QueueUrl}"}, Properties: []string{"ContentBasedDeduplication", "DeduplicationScope", "DelaySeconds", "FifoThroughputLimit", "KmsDataKeyReusePeriodSeconds", "KmsMasterKeyId", "MaximumMessageSize", "MessageRetentionPeriod", "ReceiveMessageWaitTimeSeconds", "RedriveAllowPolicy", "RedrivePolicy", "SqsManagedSseEnabled", "VisibilityTimeout"}},
				MutationCall{TagProperty: "Tags", Add: &MutationCall{Operation: "TagQueue", Target: "AmazonSQS.TagQueue", Input: map[string]any{"QueueUrl": "{QueueUrl}", "Tags": "{added:entries}"}}, Remove: &MutationCall{Operation: "UntagQueue", Target: "AmazonSQS.UntagQueue", Input: map[string]any{"QueueUrl": "{QueueUrl}", "TagKeys": "{removed}"}}},
			},
			Also: []Reader{
				{
					Type:        "AWS::SQS::Queue",
					Protocol:    "awsJson1_0",
					SigningName: "sqs",
					Host:        "sqs.{region}.amazonaws.com",
					Target:      "AmazonSQS.ListQueueTags",
					Identifier: []Binding{
						{Property: "QueueUrl", Member: "QueueUrl", Location: "body"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "Tags", Kind: "map", Entries: []string{"Key", "Value"}},
					},
				},
			},
			Mutable: true,
		},
	})
}
