// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IoT::CustomMetric": {
			Type:        "AWS::IoT::CustomMetric",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/custom-metric/{metricName}",
			Identifier: []Binding{
				{Property: "MetricName", Member: "metricName", Location: "label"},
			},
			Fields: []Field{
				{Property: "DisplayName", Member: "displayName", Kind: "scalar"},
				{Property: "MetricArn", Member: "metricArn", Kind: "scalar"},
				{Property: "MetricName", Member: "metricName", Kind: "scalar"},
				{Property: "MetricType", Member: "metricType", Kind: "scalar"},
			},
		},
		"AWS::IoT::Dimension": {
			Type:        "AWS::IoT::Dimension",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/dimensions/{name}",
			Identifier: []Binding{
				{Property: "Name", Member: "name", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
				{Property: "StringValues", Member: "stringValues", Kind: "list"},
				{Property: "Type", Member: "type", Kind: "scalar"},
			},
		},
		"AWS::IoT::FleetMetric": {
			Type:        "AWS::IoT::FleetMetric",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/fleet-metric/{metricName}",
			Identifier: []Binding{
				{Property: "MetricName", Member: "metricName", Location: "label"},
			},
			Fields: []Field{
				{Property: "AggregationField", Member: "aggregationField", Kind: "scalar"},
				{Property: "AggregationType", Member: "aggregationType", Kind: "structure",
					Fields: []Field{
						{Property: "Name", Member: "name", Kind: "scalar"},
						{Property: "Values", Member: "values", Kind: "list"},
					},
				},
				{Property: "CreationDate", Member: "creationDate", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "IndexName", Member: "indexName", Kind: "scalar"},
				{Property: "LastModifiedDate", Member: "lastModifiedDate", Kind: "timestamp"},
				{Property: "MetricArn", Member: "metricArn", Kind: "scalar"},
				{Property: "MetricName", Member: "metricName", Kind: "scalar"},
				{Property: "Period", Member: "period", Kind: "scalar"},
				{Property: "QueryString", Member: "queryString", Kind: "scalar"},
				{Property: "QueryVersion", Member: "queryVersion", Kind: "scalar"},
				{Property: "Unit", Member: "unit", Kind: "scalar"},
				{Property: "Version", Member: "version", Kind: "scalar"},
			},
		},
		"AWS::IoT::RoleAlias": {
			Type:        "AWS::IoT::RoleAlias",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/role-aliases/{roleAlias}",
			Identifier: []Binding{
				{Property: "RoleAlias", Member: "roleAlias", Location: "label"},
			},
			Response: []Step{{Name: "roleAliasDescription"}},
			Fields: []Field{
				{Property: "CredentialDurationSeconds", Member: "credentialDurationSeconds", Kind: "scalar"},
				{Property: "RoleAlias", Member: "roleAlias", Kind: "scalar"},
				{Property: "RoleAliasArn", Member: "roleAliasArn", Kind: "scalar"},
				{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
			},
		},
		"AWS::IoT::ScheduledAudit": {
			Type:        "AWS::IoT::ScheduledAudit",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/audit/scheduledaudits/{scheduledAuditName}",
			Identifier: []Binding{
				{Property: "ScheduledAuditName", Member: "scheduledAuditName", Location: "label"},
			},
			Fields: []Field{
				{Property: "DayOfMonth", Member: "dayOfMonth", Kind: "scalar"},
				{Property: "DayOfWeek", Member: "dayOfWeek", Kind: "scalar"},
				{Property: "Frequency", Member: "frequency", Kind: "scalar"},
				{Property: "ScheduledAuditArn", Member: "scheduledAuditArn", Kind: "scalar"},
				{Property: "ScheduledAuditName", Member: "scheduledAuditName", Kind: "scalar"},
				{Property: "TargetCheckNames", Member: "targetCheckNames", Kind: "list"},
			},
		},
		"AWS::IoT::SoftwarePackage": {
			Type:        "AWS::IoT::SoftwarePackage",
			Protocol:    "restJson1",
			SigningName: "iot",
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/packages/{packageName}",
			Identifier: []Binding{
				{Property: "PackageName", Member: "packageName", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "PackageArn", Member: "packageArn", Kind: "scalar"},
				{Property: "PackageName", Member: "packageName", Kind: "scalar"},
			},
		},
		"AWS::IoT::TopicRuleDestination": {
			Type:        "AWS::IoT::TopicRuleDestination",
			Protocol:    "restJson1",
			SigningName: "iot",
			Complete:    true,
			Host:        "iot.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/destinations/{arn+}",
			Identifier: []Binding{
				{Property: "Arn", Member: "arn", Location: "label"},
			},
			Response: []Step{{Name: "topicRuleDestination"}},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "HttpUrlProperties", Member: "httpUrlProperties", Kind: "structure",
					Fields: []Field{
						{Property: "ConfirmationUrl", Member: "confirmationUrl", Kind: "scalar"},
					},
				},
				{Property: "InfluxDBProperties", Member: "influxDBProperties", Kind: "structure",
					Fields: []Field{
						{Property: "Endpoint", Member: "endpoint", Kind: "scalar"},
						{Property: "InfluxDBVersion", Member: "influxDBVersion", Kind: "scalar"},
						{Property: "SecretId", Member: "secretId", Kind: "scalar"},
						{Property: "SecretKey", Member: "secretKey", Kind: "scalar"},
						{Property: "SecretType", Member: "secretType", Kind: "scalar"},
					},
				},
				{Property: "Status", Member: "status", Kind: "scalar"},
				{Property: "StatusReason", Member: "statusReason", Kind: "scalar"},
				{Property: "VpcProperties", Member: "vpcProperties", Kind: "structure",
					Fields: []Field{
						{Property: "RoleArn", Member: "roleArn", Kind: "scalar"},
						{Property: "SecurityGroups", Member: "securityGroups", Kind: "list"},
						{Property: "SubnetIds", Member: "subnetIds", Kind: "list"},
						{Property: "VpcId", Member: "vpcId", Kind: "scalar"},
					},
				},
			},
		},
	})
}
