// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::LicenseManager::Grant": {
			Type:        "AWS::LicenseManager::Grant",
			Protocol:    "awsJson1_1",
			SigningName: "license-manager",
			Host:        "license-manager.{region}.amazonaws.com",
			Target:      "AWSLicenseManager.GetGrant",
			Identifier: []Binding{
				{Property: "GrantArn", Member: "GrantArn", Location: "body"},
			},
			Response: []Step{{Name: "Grant"}},
			Fields: []Field{
				{Property: "GrantArn", Member: "GrantArn", Kind: "scalar"},
				{Property: "GrantName", Member: "GrantName", Kind: "scalar"},
				{Property: "HomeRegion", Member: "HomeRegion", Kind: "scalar"},
				{Property: "LicenseArn", Member: "LicenseArn", Kind: "scalar"},
				{Property: "Version", Member: "Version", Kind: "scalar"},
			},
		},
		"AWS::LicenseManager::License": {
			Type:        "AWS::LicenseManager::License",
			Protocol:    "awsJson1_1",
			SigningName: "license-manager",
			Host:        "license-manager.{region}.amazonaws.com",
			Target:      "AWSLicenseManager.GetLicense",
			Identifier: []Binding{
				{Property: "LicenseArn", Member: "LicenseArn", Location: "body"},
			},
			Response: []Step{{Name: "License"}},
			Fields: []Field{
				{Property: "Beneficiary", Member: "Beneficiary", Kind: "scalar"},
				{Property: "ConsumptionConfiguration", Member: "ConsumptionConfiguration", Kind: "structure",
					Fields: []Field{
						{Property: "BorrowConfiguration", Member: "BorrowConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "AllowEarlyCheckIn", Member: "AllowEarlyCheckIn", Kind: "scalar"},
								{Property: "MaxTimeToLiveInMinutes", Member: "MaxTimeToLiveInMinutes", Kind: "scalar"},
							},
						},
						{Property: "ProvisionalConfiguration", Member: "ProvisionalConfiguration", Kind: "structure",
							Fields: []Field{
								{Property: "MaxTimeToLiveInMinutes", Member: "MaxTimeToLiveInMinutes", Kind: "scalar"},
							},
						},
						{Property: "RenewType", Member: "RenewType", Kind: "scalar"},
					},
				},
				{Property: "Entitlements", Member: "Entitlements", Kind: "list",
					Fields: []Field{
						{Property: "AllowCheckIn", Member: "AllowCheckIn", Kind: "scalar"},
						{Property: "MaxCount", Member: "MaxCount", Kind: "scalar"},
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "Overage", Member: "Overage", Kind: "scalar"},
						{Property: "Unit", Member: "Unit", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "HomeRegion", Member: "HomeRegion", Kind: "scalar"},
				{Property: "Issuer", Member: "Issuer", Kind: "structure",
					Fields: []Field{
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "SignKey", Member: "SignKey", Kind: "scalar"},
					},
				},
				{Property: "LicenseArn", Member: "LicenseArn", Kind: "scalar"},
				{Property: "LicenseMetadata", Member: "LicenseMetadata", Kind: "list",
					Fields: []Field{
						{Property: "Name", Member: "Name", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
				{Property: "LicenseName", Member: "LicenseName", Kind: "scalar"},
				{Property: "ProductName", Member: "ProductName", Kind: "scalar"},
				{Property: "ProductSKU", Member: "ProductSKU", Kind: "scalar"},
				{Property: "Status", Member: "Status", Kind: "scalar"},
				{Property: "Validity", Member: "Validity", Kind: "structure",
					Fields: []Field{
						{Property: "Begin", Member: "Begin", Kind: "scalar"},
						{Property: "End", Member: "End", Kind: "scalar"},
					},
				},
				{Property: "Version", Member: "Version", Kind: "scalar"},
			},
		},
		"AWS::LicenseManager::LicenseAssetGroup": {
			Type:        "AWS::LicenseManager::LicenseAssetGroup",
			Protocol:    "awsJson1_1",
			SigningName: "license-manager",
			Host:        "license-manager.{region}.amazonaws.com",
			Target:      "AWSLicenseManager.GetLicenseAssetGroup",
			Identifier: []Binding{
				{Property: "LicenseAssetGroupArn", Member: "LicenseAssetGroupArn", Location: "body"},
			},
			Response: []Step{{Name: "LicenseAssetGroup"}},
			Fields: []Field{
				{Property: "AssociatedLicenseAssetRulesetARNs", Member: "AssociatedLicenseAssetRulesetARNs", Kind: "list"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "LicenseAssetGroupArn", Member: "LicenseAssetGroupArn", Kind: "scalar"},
				{Property: "LicenseAssetGroupConfigurations", Member: "LicenseAssetGroupConfigurations", Kind: "list",
					Fields: []Field{
						{Property: "UsageDimension", Member: "UsageDimension", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Properties", Member: "Properties", Kind: "list",
					Fields: []Field{
						{Property: "Key", Member: "Key", Kind: "scalar"},
						{Property: "Value", Member: "Value", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::LicenseManager::LicenseAssetRuleSet": {
			Type:        "AWS::LicenseManager::LicenseAssetRuleSet",
			Protocol:    "awsJson1_1",
			SigningName: "license-manager",
			Host:        "license-manager.{region}.amazonaws.com",
			Target:      "AWSLicenseManager.GetLicenseAssetRuleset",
			Identifier: []Binding{
				{Property: "LicenseAssetRulesetArn", Member: "LicenseAssetRulesetArn", Location: "body"},
			},
			Response: []Step{{Name: "LicenseAssetRuleset"}},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "LicenseAssetRulesetArn", Member: "LicenseAssetRulesetArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Rules", Member: "Rules", Kind: "list",
					Fields: []Field{
						{Property: "RuleStatement", Member: "RuleStatement", Kind: "structure",
							Fields: []Field{
								{Property: "InstanceRuleStatement", Member: "InstanceRuleStatement", Kind: "structure",
									Fields: []Field{
										{Property: "AndRuleStatement", Member: "AndRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
										{Property: "MatchingRuleStatement", Member: "MatchingRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
												{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
												{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
											},
										},
										{Property: "OrRuleStatement", Member: "OrRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
									},
								},
								{Property: "LicenseConfigurationRuleStatement", Member: "LicenseConfigurationRuleStatement", Kind: "structure",
									Fields: []Field{
										{Property: "AndRuleStatement", Member: "AndRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
										{Property: "MatchingRuleStatement", Member: "MatchingRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
												{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
												{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
											},
										},
										{Property: "OrRuleStatement", Member: "OrRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
									},
								},
								{Property: "LicenseRuleStatement", Member: "LicenseRuleStatement", Kind: "structure",
									Fields: []Field{
										{Property: "AndRuleStatement", Member: "AndRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
										{Property: "MatchingRuleStatement", Member: "MatchingRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
												{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
												{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
											},
										},
										{Property: "OrRuleStatement", Member: "OrRuleStatement", Kind: "structure",
											Fields: []Field{
												{Property: "MatchingRuleStatements", Member: "MatchingRuleStatements", Kind: "list",
													Fields: []Field{
														{Property: "Constraint", Member: "Constraint", Kind: "scalar"},
														{Property: "KeyToMatch", Member: "KeyToMatch", Kind: "scalar"},
														{Property: "ValueToMatch", Member: "ValueToMatch", Kind: "list"},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	})
}
