// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ElastiCache::SubnetGroup": {
			Type:        "AWS::ElastiCache::SubnetGroup",
			Protocol:    "awsQuery",
			SigningName: "elasticache",
			Complete:    true,
			Production:  true,
			Host:        "elasticache.{region}.amazonaws.com",
			Action:      "DescribeCacheSubnetGroups",
			Version:     "2015-02-02",
			Wrapper:     "DescribeCacheSubnetGroupsResult",
			Identifier: []Binding{
				{Property: "CacheSubnetGroupName", Member: "CacheSubnetGroupName", Location: "form", Name: "CacheSubnetGroupName"},
			},
			AbsentErrors: []string{"CacheSubnetGroupNotFoundFault"},
			PageToken:    []string{"Marker"},
			Response:     []Step{{Name: "CacheSubnetGroups", List: true, Item: "CacheSubnetGroup"}},
			Fields: []Field{
				{Property: "CacheSubnetGroupName", Member: "CacheSubnetGroupName", Kind: "scalar", XMLName: "CacheSubnetGroupName", Scalar: "string"},
				{Property: "Description", Member: "CacheSubnetGroupDescription", Kind: "scalar", XMLName: "CacheSubnetGroupDescription", Scalar: "string"},
				{Property: "SubnetIds", Member: "SubnetIdentifier", Kind: "scalar", Via: []Step{{Name: "Subnets", List: true, Item: "Subnet"}}, XMLName: "SubnetIdentifier", Scalar: "string"},
			},
			AbsentIDs: []string{"kraai-absent-probe-subnetgroup"},
			Capture: []Field{
				{Property: "Arn", Member: "ARN", Kind: "scalar", XMLName: "ARN", Scalar: "string"},
			},
			Also: []Reader{
				{
					Type:        "AWS::ElastiCache::SubnetGroup",
					Protocol:    "awsQuery",
					SigningName: "elasticache",
					Host:        "elasticache.{region}.amazonaws.com",
					Action:      "ListTagsForResource",
					Version:     "2015-02-02",
					Wrapper:     "ListTagsForResourceResult",
					Input: []Binding{
						Binding{Location: "form", Member: "ResourceName", Name: "ResourceName", Value: "{Arn}"},
					},
					Fields: []Field{
						{Property: "Tags", Member: "TagList", Kind: "list", XMLName: "TagList", Item: "Tag",
							Fields: []Field{
								{Property: "Key", Member: "Key", Kind: "scalar", XMLName: "Key", Scalar: "string"},
								{Property: "Value", Member: "Value", Kind: "scalar", XMLName: "Value", Scalar: "string"},
							},
						},
					},
				},
			},
		},
	})
}
