// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IoTTwinMaker::Workspace": {
			Type:        "AWS::IoTTwinMaker::Workspace",
			Protocol:    "restJson1",
			SigningName: "iottwinmaker",
			Host:        "iottwinmaker.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/workspaces/{workspaceId}",
			Identifier: []Binding{
				{Property: "WorkspaceId", Member: "workspaceId", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "CreationDateTime", Member: "creationDateTime", Kind: "timestamp"},
				{Property: "Description", Member: "description", Kind: "scalar"},
				{Property: "Role", Member: "role", Kind: "scalar"},
				{Property: "S3Location", Member: "s3Location", Kind: "scalar"},
				{Property: "UpdateDateTime", Member: "updateDateTime", Kind: "timestamp"},
				{Property: "WorkspaceId", Member: "workspaceId", Kind: "scalar"},
			},
		},
	})
}
