// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::ServerlessRepo::Application": {
			Type:        "AWS::ServerlessRepo::Application",
			Protocol:    "restJson1",
			SigningName: "serverlessrepo",
			Complete:    true,
			Host:        "serverlessrepo.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/applications/{ApplicationId}",
			Identifier: []Binding{
				{Property: "ApplicationId", Member: "ApplicationId", Location: "label"},
			},
			Fields: []Field{
				{Property: "ApplicationId", Member: "ApplicationId", Kind: "scalar", JSONName: "applicationId"},
				{Property: "Author", Member: "Author", Kind: "scalar", JSONName: "author"},
				{Property: "CreationTime", Member: "CreationTime", Kind: "scalar", JSONName: "creationTime"},
				{Property: "Description", Member: "Description", Kind: "scalar", JSONName: "description"},
				{Property: "HomePageUrl", Member: "HomePageUrl", Kind: "scalar", JSONName: "homePageUrl"},
				{Property: "IsVerifiedAuthor", Member: "IsVerifiedAuthor", Kind: "scalar", JSONName: "isVerifiedAuthor"},
				{Property: "Labels", Member: "Labels", Kind: "list", JSONName: "labels"},
				{Property: "Name", Member: "Name", Kind: "scalar", JSONName: "name"},
				{Property: "SpdxLicenseId", Member: "SpdxLicenseId", Kind: "scalar", JSONName: "spdxLicenseId"},
			},
		},
	})
}
