// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Cases::Domain": {
			Type:        "AWS::Cases::Domain",
			Protocol:    "restJson1",
			SigningName: "cases",
			Host:        "cases.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/domains/{domainId}",
			Identifier: []Binding{
				{Property: "DomainArn", Member: "domainId", Location: "label"},
			},
			Fields: []Field{
				{Property: "CreatedTime", Member: "createdTime", Kind: "timestamp"},
				{Property: "DomainArn", Member: "domainArn", Kind: "scalar"},
				{Property: "DomainId", Member: "domainId", Kind: "scalar"},
				{Property: "DomainStatus", Member: "domainStatus", Kind: "scalar"},
				{Property: "Name", Member: "name", Kind: "scalar"},
			},
		},
	})
}
