// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::IVSChat::Room": {
			Type:        "AWS::IVSChat::Room",
			Protocol:    "restJson1",
			SigningName: "ivschat",
			Host:        "ivschat.{region}.amazonaws.com",
			Method:      "POST",
			URI:         "/GetRoom",
			Identifier: []Binding{
				{Property: "Arn", Member: "identifier", Location: "body"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "arn", Kind: "scalar"},
				{Property: "Id", Member: "id", Kind: "scalar"},
				{Property: "LoggingConfigurationIdentifiers", Member: "loggingConfigurationIdentifiers", Kind: "list"},
				{Property: "MaximumMessageLength", Member: "maximumMessageLength", Kind: "scalar"},
				{Property: "MaximumMessageRatePerSecond", Member: "maximumMessageRatePerSecond", Kind: "scalar"},
				{Property: "MessageReviewHandler", Member: "messageReviewHandler", Kind: "structure",
					Fields: []Field{
						{Property: "FallbackResult", Member: "fallbackResult", Kind: "scalar"},
						{Property: "Uri", Member: "uri", Kind: "scalar"},
					},
				},
				{Property: "Name", Member: "name", Kind: "scalar"},
			},
		},
	})
}
