// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::DataBrew::Project": {
			Type:        "AWS::DataBrew::Project",
			Protocol:    "restJson1",
			SigningName: "databrew",
			Host:        "databrew.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/projects/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "DatasetName", Member: "DatasetName", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "RecipeName", Member: "RecipeName", Kind: "scalar"},
				{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
				{Property: "Sample", Member: "Sample", Kind: "structure",
					Fields: []Field{
						{Property: "Size", Member: "Size", Kind: "scalar"},
						{Property: "Type", Member: "Type", Kind: "scalar"},
					},
				},
			},
		},
		"AWS::DataBrew::Recipe": {
			Type:        "AWS::DataBrew::Recipe",
			Protocol:    "restJson1",
			SigningName: "databrew",
			Host:        "databrew.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/recipes/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "Steps", Member: "Steps", Kind: "list",
					Fields: []Field{
						{Property: "Action", Member: "Action", Kind: "structure",
							Fields: []Field{
								{Property: "Operation", Member: "Operation", Kind: "scalar"},
								{Property: "Parameters", Member: "Parameters", Kind: "map"},
							},
						},
						{Property: "ConditionExpressions", Member: "ConditionExpressions", Kind: "list",
							Fields: []Field{
								{Property: "Condition", Member: "Condition", Kind: "scalar"},
								{Property: "TargetColumn", Member: "TargetColumn", Kind: "scalar"},
								{Property: "Value", Member: "Value", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
		"AWS::DataBrew::Schedule": {
			Type:        "AWS::DataBrew::Schedule",
			Protocol:    "restJson1",
			SigningName: "databrew",
			Host:        "databrew.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/schedules/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "CronExpression", Member: "CronExpression", Kind: "scalar"},
				{Property: "JobNames", Member: "JobNames", Kind: "list"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
			},
		},
	})
}
