// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::Scheduler::Schedule": {
			Type:        "AWS::Scheduler::Schedule",
			Protocol:    "restJson1",
			SigningName: "scheduler",
			Complete:    true,
			Host:        "scheduler.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/schedules/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "Description", Member: "Description", Kind: "scalar"},
				{Property: "EndDate", Member: "EndDate", Kind: "timestamp"},
				{Property: "FlexibleTimeWindow", Member: "FlexibleTimeWindow", Kind: "structure",
					Fields: []Field{
						{Property: "MaximumWindowInMinutes", Member: "MaximumWindowInMinutes", Kind: "scalar"},
						{Property: "Mode", Member: "Mode", Kind: "scalar"},
					},
				},
				{Property: "GroupName", Member: "GroupName", Kind: "scalar"},
				{Property: "KmsKeyArn", Member: "KmsKeyArn", Kind: "scalar"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "ScheduleExpression", Member: "ScheduleExpression", Kind: "scalar"},
				{Property: "ScheduleExpressionTimezone", Member: "ScheduleExpressionTimezone", Kind: "scalar"},
				{Property: "StartDate", Member: "StartDate", Kind: "timestamp"},
				{Property: "State", Member: "State", Kind: "scalar"},
				{Property: "Target", Member: "Target", Kind: "structure",
					Fields: []Field{
						{Property: "Arn", Member: "Arn", Kind: "scalar"},
						{Property: "DeadLetterConfig", Member: "DeadLetterConfig", Kind: "structure",
							Fields: []Field{
								{Property: "Arn", Member: "Arn", Kind: "scalar"},
							},
						},
						{Property: "EcsParameters", Member: "EcsParameters", Kind: "structure",
							Fields: []Field{
								{Property: "CapacityProviderStrategy", Member: "CapacityProviderStrategy", Kind: "list",
									Fields: []Field{
										{Property: "Base", Member: "base", Kind: "scalar"},
										{Property: "CapacityProvider", Member: "capacityProvider", Kind: "scalar"},
										{Property: "Weight", Member: "weight", Kind: "scalar"},
									},
								},
								{Property: "EnableECSManagedTags", Member: "EnableECSManagedTags", Kind: "scalar"},
								{Property: "EnableExecuteCommand", Member: "EnableExecuteCommand", Kind: "scalar"},
								{Property: "Group", Member: "Group", Kind: "scalar"},
								{Property: "LaunchType", Member: "LaunchType", Kind: "scalar"},
								{Property: "NetworkConfiguration", Member: "NetworkConfiguration", Kind: "structure",
									Fields: []Field{
										{Property: "AwsvpcConfiguration", Member: "awsvpcConfiguration", Kind: "structure",
											Fields: []Field{
												{Property: "AssignPublicIp", Member: "AssignPublicIp", Kind: "scalar"},
												{Property: "SecurityGroups", Member: "SecurityGroups", Kind: "list"},
												{Property: "Subnets", Member: "Subnets", Kind: "list"},
											},
										},
									},
								},
								{Property: "PlacementConstraints", Member: "PlacementConstraints", Kind: "list",
									Fields: []Field{
										{Property: "Expression", Member: "expression", Kind: "scalar"},
										{Property: "Type", Member: "type", Kind: "scalar"},
									},
								},
								{Property: "PlacementStrategy", Member: "PlacementStrategy", Kind: "list",
									Fields: []Field{
										{Property: "Field", Member: "field", Kind: "scalar"},
										{Property: "Type", Member: "type", Kind: "scalar"},
									},
								},
								{Property: "PlatformVersion", Member: "PlatformVersion", Kind: "scalar"},
								{Property: "PropagateTags", Member: "PropagateTags", Kind: "scalar"},
								{Property: "ReferenceId", Member: "ReferenceId", Kind: "scalar"},
								{Property: "Tags", Member: "Tags", Kind: "list"},
								{Property: "TaskCount", Member: "TaskCount", Kind: "scalar"},
								{Property: "TaskDefinitionArn", Member: "TaskDefinitionArn", Kind: "scalar"},
							},
						},
						{Property: "EventBridgeParameters", Member: "EventBridgeParameters", Kind: "structure",
							Fields: []Field{
								{Property: "DetailType", Member: "DetailType", Kind: "scalar"},
								{Property: "Source", Member: "Source", Kind: "scalar"},
							},
						},
						{Property: "Input", Member: "Input", Kind: "scalar"},
						{Property: "KinesisParameters", Member: "KinesisParameters", Kind: "structure",
							Fields: []Field{
								{Property: "PartitionKey", Member: "PartitionKey", Kind: "scalar"},
							},
						},
						{Property: "RetryPolicy", Member: "RetryPolicy", Kind: "structure",
							Fields: []Field{
								{Property: "MaximumEventAgeInSeconds", Member: "MaximumEventAgeInSeconds", Kind: "scalar"},
								{Property: "MaximumRetryAttempts", Member: "MaximumRetryAttempts", Kind: "scalar"},
							},
						},
						{Property: "RoleArn", Member: "RoleArn", Kind: "scalar"},
						{Property: "SageMakerPipelineParameters", Member: "SageMakerPipelineParameters", Kind: "structure",
							Fields: []Field{
								{Property: "PipelineParameterList", Member: "PipelineParameterList", Kind: "list",
									Fields: []Field{
										{Property: "Name", Member: "Name", Kind: "scalar"},
										{Property: "Value", Member: "Value", Kind: "scalar"},
									},
								},
							},
						},
						{Property: "SqsParameters", Member: "SqsParameters", Kind: "structure",
							Fields: []Field{
								{Property: "MessageGroupId", Member: "MessageGroupId", Kind: "scalar"},
							},
						},
					},
				},
			},
		},
		"AWS::Scheduler::ScheduleGroup": {
			Type:        "AWS::Scheduler::ScheduleGroup",
			Protocol:    "restJson1",
			SigningName: "scheduler",
			Host:        "scheduler.{region}.amazonaws.com",
			Method:      "GET",
			URI:         "/schedule-groups/{Name}",
			Identifier: []Binding{
				{Property: "Name", Member: "Name", Location: "label"},
			},
			Fields: []Field{
				{Property: "Arn", Member: "Arn", Kind: "scalar"},
				{Property: "CreationDate", Member: "CreationDate", Kind: "timestamp"},
				{Property: "LastModificationDate", Member: "LastModificationDate", Kind: "timestamp"},
				{Property: "Name", Member: "Name", Kind: "scalar"},
				{Property: "State", Member: "State", Kind: "scalar"},
			},
		},
	})
}
