// Code generated by generate_main.go from overrides/, lock.json, models/ and schemas/. DO NOT EDIT.

package direct

func init() {
	register(map[string]Reader{
		"AWS::PaymentCryptography::Alias": {
			Type:        "AWS::PaymentCryptography::Alias",
			Protocol:    "awsJson1_0",
			SigningName: "payment-cryptography",
			Complete:    true,
			Host:        "controlplane.payment-cryptography.{region}.amazonaws.com",
			Target:      "PaymentCryptographyControlPlane.GetAlias",
			Identifier: []Binding{
				{Property: "AliasName", Member: "AliasName", Location: "body"},
			},
			Response: []Step{{Name: "Alias"}},
			Fields: []Field{
				{Property: "AliasName", Member: "AliasName", Kind: "scalar"},
				{Property: "KeyArn", Member: "KeyArn", Kind: "scalar"},
			},
		},
	})
}
