package awsschema

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// Generate emits a Go source file declaring one package-level ResourceType
// literal per entry in types, plus a Types map keyed by TypeName, into
// package pkg.
//
// Deterministic: types is sorted by TypeName before anything is emitted,
// every map this package builds along the way (Handlers, and
// PropertiesSchema's own canonicalization in schema.go) is walked in sorted
// key order, and the only non-literal step is gofmt (go/format), which is
// itself deterministic on identical input. Same schemas in, byte-identical
// Go out — see this package's own tests for the round-trip check this
// claim rests on.
func Generate(pkg string, types []ResourceType) ([]byte, error) {
	sorted := append([]ResourceType(nil), types...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].TypeName < sorted[j].TypeName })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/generate/awsschema/cmd/gen-lambda-schema. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	for _, rt := range sorted {
		writeResourceTypeVar(&buf, rt)
	}

	buf.WriteString("// Types indexes every generated ResourceType by its CloudFormation TypeName.\n")
	buf.WriteString("var Types = map[string]ResourceType{\n")
	for _, rt := range sorted {
		fmt.Fprintf(&buf, "\t%q: %s,\n", rt.TypeName, varName(rt.TypeName))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n---\n%s", err, buf.String())
	}
	return formatted, nil
}

// varName derives a Go identifier from a CloudFormation TypeName —
// "AWS::Lambda::Function" becomes "AWSLambdaFunction" — by dropping "::"
// separators. Collision-free for AWS's own vocabulary: TypeName is globally
// unique per the CloudFormation registry itself, and "::" never appears
// inside a single segment.
func varName(typeName string) string {
	return strings.ReplaceAll(typeName, "::", "")
}

func writeResourceTypeVar(buf *bytes.Buffer, rt ResourceType) {
	name := varName(rt.TypeName)
	fmt.Fprintf(buf, "// %s is the generated snapshot of %s's CloudFormation\n// resource provider schema.\n", name, rt.TypeName)
	fmt.Fprintf(buf, "var %s = ResourceType{\n", name)
	fmt.Fprintf(buf, "\tTypeName: %q,\n", rt.TypeName)
	if rt.Description != "" {
		fmt.Fprintf(buf, "\tDescription: %s,\n", backtickOrQuote(rt.Description))
	}
	writeStringSlice(buf, "PrimaryIdentifier", rt.PrimaryIdentifier)
	writeStringSlice(buf, "CreateOnlyProperties", rt.CreateOnlyProperties)
	writeStringSlice(buf, "ConditionalCreateOnlyProperties", rt.ConditionalCreateOnlyProperties)
	writeStringSlice(buf, "ReadOnlyProperties", rt.ReadOnlyProperties)
	writeStringSlice(buf, "WriteOnlyProperties", rt.WriteOnlyProperties)
	writeStringSlice(buf, "Required", rt.Required)
	fmt.Fprintf(buf, "\tAdditionalProperties: %v,\n", rt.AdditionalProperties)

	fmt.Fprintf(buf, "\tTagging: Tagging{\n")
	fmt.Fprintf(buf, "\t\tTaggable: %v,\n", rt.Tagging.Taggable)
	fmt.Fprintf(buf, "\t\tTagOnCreate: %v,\n", rt.Tagging.TagOnCreate)
	fmt.Fprintf(buf, "\t\tTagUpdatable: %v,\n", rt.Tagging.TagUpdatable)
	if rt.Tagging.TagProperty != "" {
		fmt.Fprintf(buf, "\t\tTagProperty: %q,\n", rt.Tagging.TagProperty)
	}
	writeStringSliceIndented(buf, "\t\t", "Permissions", rt.Tagging.Permissions)
	fmt.Fprintf(buf, "\t\tCloudFormationSystemTags: %v,\n", rt.Tagging.CloudFormationSystemTags)
	buf.WriteString("\t},\n")

	if len(rt.Handlers) > 0 {
		buf.WriteString("\tHandlers: map[string]Handler{\n")
		for _, verb := range sortedKeys(rt.Handlers) {
			h := rt.Handlers[verb]
			fmt.Fprintf(buf, "\t\t%q: {\n", verb)
			writeStringSliceIndented(buf, "\t\t\t", "Permissions", h.Permissions)
			writeStringSliceIndented(buf, "\t\t\t", "HandlerSchemaRequired", h.HandlerSchemaRequired)
			buf.WriteString("\t\t},\n")
		}
		buf.WriteString("\t},\n")
	}

	if rt.PropertiesSchema != "" {
		fmt.Fprintf(buf, "\tPropertiesSchema: %s,\n", backtickOrQuote(rt.PropertiesSchema))
	}
	buf.WriteString("}\n\n")
}

func writeStringSlice(buf *bytes.Buffer, field string, values []string) {
	writeStringSliceIndented(buf, "\t", field, values)
}

func writeStringSliceIndented(buf *bytes.Buffer, indent, field string, values []string) {
	if len(values) == 0 {
		return
	}
	// Order matters for some of these fields (primaryIdentifier's own
	// compound-identifier ordering, in particular) — not sorted, emitted
	// exactly as the schema declared it. Determinism instead comes from the
	// schema itself: DescribeType returns these arrays in a stable order for
	// a given schema version, and Generate never reorders a slice value it
	// did not itself construct (only PropertiesSchema's own map traversal,
	// and this function's own map-keyed callers like Handlers, need sorting
	// to guarantee it).
	fmt.Fprintf(buf, "%s%s: []string{\n", indent, field)
	for _, v := range values {
		fmt.Fprintf(buf, "%s\t%q,\n", indent, v)
	}
	fmt.Fprintf(buf, "%s},\n", indent)
}

// backtickOrQuote renders s as a raw Go backtick string when s contains
// none (safe for schema text: JSON Schema property text may contain
// double quotes and backslashes, which a backtick string needs no escaping
// for), falling back to a regular escaped string literal when it does.
func backtickOrQuote(s string) string {
	if !strings.Contains(s, "`") && !strings.ContainsRune(s, '\r') {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}
