package awsschema

import (
	"bytes"
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func loadFixtures(t *testing.T) []ResourceType {
	t.Helper()
	paths := []string{"testdata/lambda_function.json", "testdata/lambda_permission.json", "testdata/lambda_url.json"}
	var out []ResourceType
	for _, p := range paths {
		out = append(out, mustParseFixture(t, p))
	}
	return out
}

func TestGenerate_Deterministic(t *testing.T) {
	types := loadFixtures(t)

	first, err := Generate("awsl1", types)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	second, err := Generate("awsl1", types)
	if err != nil {
		t.Fatalf("Generate (second run): %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("Generate produced different output for identical input across two runs")
	}
}

// TestGenerate_OrderIndependent confirms Generate sorts by TypeName
// internally, so the order the caller happened to fetch or hand it types in
// does not leak into the generated source — part of the "same schemas in,
// byte-identical Go out" determinism claim.
func TestGenerate_OrderIndependent(t *testing.T) {
	types := loadFixtures(t)
	reversed := make([]ResourceType, len(types))
	for i, rt := range types {
		reversed[len(types)-1-i] = rt
	}

	inOrder, err := Generate("awsl1", types)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	reversedOrder, err := Generate("awsl1", reversed)
	if err != nil {
		t.Fatalf("Generate (reversed): %v", err)
	}
	if !bytes.Equal(inOrder, reversedOrder) {
		t.Fatal("Generate's output depends on input slice order; it should not")
	}
}

func TestGenerate_ValidGoSyntax(t *testing.T) {
	types := loadFixtures(t)
	src, err := Generate("awsl1", types)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "lambda_gen.go", src, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse as Go: %v\n---\n%s", err, src)
	}
}

func TestGenerate_ContainsExpectedDeclarations(t *testing.T) {
	types := loadFixtures(t)
	src, err := Generate("awsl1", types)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	s := string(src)

	for _, want := range []string{
		"Code generated by",
		"DO NOT EDIT",
		"package awsl1",
		"var AWSLambdaFunction = ResourceType{",
		"var AWSLambdaPermission = ResourceType{",
		"var AWSLambdaUrl = ResourceType{",
		`"AWS::Lambda::Function":`,
		`AWSLambdaFunction,`,
		`"AWS::Lambda::Permission":`,
		`AWSLambdaPermission,`,
		`"AWS::Lambda::Url":`,
		`AWSLambdaUrl,`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated source missing expected fragment: %q", want)
		}
	}
}

func TestVarName(t *testing.T) {
	cases := map[string]string{
		"AWS::Lambda::Function":  "AWSLambdaFunction",
		"AWS::Lambda::Url":       "AWSLambdaUrl",
		"AWS::S3::Bucket":        "AWSS3Bucket",
		"AWS::ApiGatewayV2::Api": "AWSApiGatewayV2Api",
	}
	for in, want := range cases {
		if got := varName(in); got != want {
			t.Errorf("varName(%q) = %q, want %q", in, got, want)
		}
	}
}
